#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# PART 1: RTL Languages (Urdu, Sindhi, Arabic, Persian, Pashto)

ur = {
  "title": "آزاد ماسٹر",
  "subtitle": "محفوظ درزی کھاتہ اور کٹنگ رجسٹر",
  "appSubtitle": "پیشہ ورانہ درزی ڈیجیٹل کلاؤڈ رجسٹر",
  "defaultMasterTitle": "ماسٹر صاحب",
  "masterNameLabel": "ماسٹر کا نام:",
  "masterPhotoLabel": "ماسٹر فوٹو لگائیں:",
  "masterDefaultName": "ماسٹر صاحب",
  "navHome": "ہوم",
  "navSettings": "سیٹنگز",
  "navAdd": "ناپ درج کریں",
  "searchPlaceholder": "گاہک کا نام یا فون نمبر تلاش کریں...",
  "searchAction": "تلاش",
  "clear": "صاف کریں",
  "recentSearches": "پچھلی تلاشیں",
  "clearHistory": "ہسٹری صاف کریں",
  "openSlip": "سلپ کھولیں",
  "addMeasurementBtn": "ناپ درج کریں",
  "photoOcrBtn": "پرچہ / کپڑا فوٹو",
  "cuttingMode": "✂️ کٹنگ موڈ",
  "normalMode": "نارمل موڈ",
  "voiceInput": "آواز سے درج کریں",
  "chatbot": "آزاد ماسٹر اسسٹنٹ",
  "assistant": "اسسٹنٹ",
  "settings": "سیٹنگز و پروفائل",
  "privacy": "رازداری پالیسی",
  "logout": "لاگ آؤٹ",
  "customerSlipsHeading": "گاہکوں کی کٹنگ سلپس:",
  "statusFiltersHeading": "آرڈر اسٹیٹس فلٹرز:",
  "showingCount": "موجودہ:",
  "allFilter": "سب",
  "statusPending": "زیرِ کار",
  "statusCutting": "کٹنگ",
  "statusStitching": "سلائی جاری",
  "statusReady": "تیار ہے",
  "statusDelivered": "حوالے کر دیا",
  "todayDelivery": "آج کی ڈیلیوری:",
  "lateOrders": "تاخیر شدہ آرڈرز:",
  "totalCustomers": "کل گاہک",
  "quickStats": "خلاصہ",
  "recentOrders": "حالیہ آرڈرز (فوری نظارہ)",
  "recentOrdersCount": "تازہ ترین",
  "show": "دکھائیں",
  "hide": "چھپائیں",
  "noRecords": "کوئی ریکارڈ نہیں ملا۔",
  "noCustomerFound": "کوئی گاہک نہیں ملا",
  "noCustomersSaved": "ابھی تک کوئی گاہک محفوظ نہیں کیا گیا",
  "searchHintEmpty": "کسی اور نام یا فون نمبر سے تلاش کر کے دیکھیں۔",
  "addFirstCustomerHint": "پہلا کسٹمر شامل کرنے کے لیے نیچے بٹن دبائیں۔",
  "addFirstCustomer": "پہلا گاہک درج کریں",
  "tapToAdd": "نیا ناپ درج کرنے کے لیے نیچے (+) بٹن دبائیں۔",
  "tapToAddCustomer": "نیا گاہک شامل کرنے کے لیے یہاں کلک کریں۔",
  "addAsNewCustomer": "بطور نیا گاہک",
  "unnamedCustomer": "نامعلوم گاہک",
  "date": "تاریخ:",
  "delivery": "ڈیلیوری:",
  "balance": "بقایا:",
  "cleared": "مکمل ادا",
  "syncing": "سنک ہو رہا ہے...",
  "cloudSynced": "کلاؤڈ پر محفوظ",
  "syncNow": "ابھی سنک کریں",
  "cloudSyncError": "کلاؤڈ خرابی",
  "online": "آن لائن",
  "selectPhotoSource": "پرچے یا کپڑے کی تصویر منتخب کریں",
  "camera": "کیمرہ",
  "gallery": "گیلری",
  "fillManually": "فارم خود بھریں",
  "uploadPhotoTitle": "کاغذی پرچے کی تصویر:",
  "galleryBtn": "🖼️ گیلری",
  "cameraBtn": "📸 کیمرہ",
  "removePhoto": "تصویر ہٹائیں",
  "extractingOcr": "تصویر سے ناپ پڑھا جا رہا ہے...",
  "addSlip": "نیا ناپ درج کریں",
  "editSlip": "ناپ میں ترمیم کریں",
  "customerName": "گاہک کا نام *",
  "phoneNumber": "واٹس ایپ نمبر (اختیاری)",
  "countryCodeLabel": "ملکی کوڈ",
  "suitTypeLabel": "سوٹ کی قسم",
  "suitGents": "مردانہ سوٹ (شلوار قمیض)",
  "suitKurtaPajama": "کرتا پاجامہ",
  "suitSafari": "سفاری سوٹ",
  "suitWaistcoat": "واسکوٹ",
  "suitSherwani": "شیروانی",
  "deliveryDateLabel": "تاریخ واپسی (ڈیلیوری)",
  "quickToday": "آج",
  "quickTomorrow": "کل",
  "quick3Days": "3 دن",
  "quick1Week": "1 ہفتہ",
  "quick10Days": "10 دن",
  "orderStatusLabel": "آرڈر اسٹیٹس:",
  "orderLockedNotice": "یہ آرڈر مکمل (Delivered) ہو چکا ہے اور لاک ہے۔ کیا آپ واقعی اسے دوبارہ ان لاک کر کے اسٹیٹس تبدیل کرنا چاہتے ہیں؟",
  "orderLockedBadge": "🔒 لاک شدہ",
  "orderUnlockedBadge": "🔓 تبدیل ہو سکتا ہے",
  "dueTodayBadge": "⚡ آج کی ڈیلیوری",
  "lateOrderBadge": "⚠️ تاخیر شدہ",
  "upcomingBadge": "📅 آئندہ",
  "lengthLabel": "لمبائی",
  "shoulderLabel": "تیرا",
  "sleevesLabel": "بازو",
  "chestLabel": "چھاتی",
  "waistLabel": "کمر",
  "daamanLabel": "دامن / گھیر",
  "collarLabel": "کالر / بین",
  "shalwarLabel": "شلوار",
  "panchaLabel": "پانچہ",
  "pocketLabel": "جیب",
  "specialNotesLabel": "خصوصی نوٹ / ہدایات",
  "notesPlaceholder": "مثلاً گول دامن، بین کالر، سنگل سلائی...",
  "billingHeading": "سلائی کھاتہ و بل:",
  "totalAmountLabel": "کل رقم",
  "advanceAmountLabel": "وصول پیشگی (ایڈوانس)",
  "balanceAmountLabel": "بقایا رقم",
  "fullyPaidBadge": "✓ مکمل ادا شدہ",
  "balanceDueBadge": "⏳ بقایا واجب الادا",
  "saveDone": "محفوظ کریں اور مکمل",
  "saveClose": "محفوظ کریں اور بند کریں",
  "cancel": "منسوخ",
  "close": "مکمل / بند کریں",
  "back": "پیچھے",
  "digitalSlip": "ڈیجیٹل کٹنگ سلپ",
  "editMode": "ترمیم / کٹنگ موڈ",
  "sendWhatsapp": "واٹس ایپ پر سلپ بھیجیں",
  "copySlip": "سلپ کاپی کریں",
  "printSlip": "پرنٹ نکالیں",
  "delete": "حذف کریں",
  "copySuccess": "سلپ کلپ بورڈ پر کاپی ہو گئی!",
  "bookedDateLabel": "بکنگ:",
  "deliveryDatePrefix": "تاریخ ڈیلیوری:",
  "tailorStamp": "ماسٹر درزی مہر",
  "customerDetailsHeading": "گاہک کی معلومات",
  "measurementsHeading": "ناپ کی تفصیل",
  "accountSummaryHeading": "بل و کھاتہ خلاصہ",
  "menuTitle": "آزاد ماسٹر مینو",
  "profileSettings": "پروفائل و ترتیبات",
  "changeLanguage": "زبان تبدیل کریں",
  "dataBackup": "کلاؤڈ بیک اپ اور سنک",
  "helpSupport": "رہنمائی اور طریقہ استعمال",
  "developerInfo": "ڈویلپر کی معلومات",
  "settingsTitle": "پروفائل اور ایپ ترتیبات",
  "selectAppLanguage": "ایپ کی زبان",
  "allSupportedLanguages": "تمام 22 زبانیں:",
  "aiVoiceAssistant": "آزاد ماسٹر اسسٹنٹ",
  "aiVoiceAssistantSub": "ناپ بولیں یا لکھیں، خودکار کٹنگ حساب",
  "appGuide": "استعمال کا طریقہ (رہنمائی)",
  "appGuideSub": "ناپ درج کرنا، OCR پرچہ، ٹریکنگ اور واٹس ایپ",
  "cloudAutoSave": "کلاؤڈ آٹو سیو (Firebase Cloud Auto-Save)",
  "cloudAutoSaveLive": "فعال و محفوظ",
  "cloudDatabaseLabel": "کلاؤڈ ڈیٹا بیس:",
  "cloudRecordsLabel": "کلاؤڈ ریکارڈز:",
  "lastSyncedLabel": "آخری سنک:",
  "syncAllNow": "تمام ڈیٹا کلاؤڈ پر محفوظ کریں",
  "syncingToCloud": "کلاؤڈ پر محفوظ ہو رہا ہے...",
  "dataBackupRestore": "ڈیٹا بیک اپ اور بحالی",
  "recordsCount": "ریکارڈز",
  "backupData": "بیک اپ بنائیں (JSON)",
  "restoreData": "بحال کریں (JSON)",
  "developerCredit": "ڈویلپر: نسیب ایس ای او (پیر بخش)",
  "copyrightNotice": "تمام جملہ حقوق محفوظ ہیں © 2026 آزاد ماسٹر",
  "resetAllRecords": "تمام کٹنگ سلپس صاف کریں",
  "resetRecordsConfirm": "کیا آپ تمام گاہکوں کا ریکارڈ ختم کرنا چاہتے ہیں؟",
  "savedSuccess": "محفوظ ہو گیا!",
  "cloudSyncSuccess": "ریکارڈز کلاؤڈ پر کامیابی سے محفوظ ہو گئے!",
  "noRecordsToBackup": "بیک اپ کے لیے کوئی ریکارڈ موجود نہیں!",
  "backupFileDownloaded": "بیک اپ فائل کامیابی سے محفوظ ہو گئی!",
  "recordsRestoredSuccess": "ریکارڈز کامیابی سے بحال ہو گئے!",
  "noValidRecordsFound": "فائل میں کوئی درست ریکارڈ نہیں ملا۔",
  "invalidBackupFile": "غلط بیک اپ فائل۔ برائے مہربانی درست JSON فائل منتخب کریں۔",
  "needHelpTitle": "مدد چاہیے؟ / سپورٹ",
  "contactWhatsApp": "واٹس ایپ پر رابطہ کریں",
  "contactEmail": "ای میل سپورٹ",
  "appGuideTitle": "آزاد ماسٹر استعمال کرنے کا طریقہ",
  "guideStep1Title": "1. نیا ناپ درج کرنا",
  "guideStep1Desc": "نیچے دیے گئے پلس (+) یا 'ناپ درج کریں' بٹن پر کلک کر کے کسٹمر کا نام، نمبر اور ناپ لکھیں۔",
  "guideStep2Title": "2. ✂️ کٹنگ موڈ کا جادو",
  "guideStep2Desc": "کٹنگ ٹیبل پر کام کرتے ہوئے 'کٹنگ موڈ' آن کریں۔ ناپ بڑی اور نمایاں ہو جائے گی تاکہ فاصلے سے بھی باآسانی نظر آئے۔",
  "guideStep3Title": "3. پرچہ / کپڑا فوٹو اور AI اسکین",
  "guideStep3Desc": "اگر کسٹمر کا پرانا کاغذی پرچہ یا کپڑا ہے تو کیمرے سے تصویر کھینچیں۔ AI خودکار ناپ نکال لے گا۔",
  "guideStep4Title": "4. ڈیجیٹل کٹنگ سلپ اور کلاؤڈ",
  "guideStep4Desc": "ایک کلک میں کسٹمر کو واٹس ایپ پر مکمل سلپ بھیجیں۔ آپ کا تمام ڈیٹا کلاؤڈ پر 100% محفوظ رہتا ہے۔",
  "closeGuide": "سمجھ آ گئی / بند کریں",
  "privacyModalTitle": "رازداری اور ڈیٹا پروٹیکشن",
  "privacyPolicyP1": "آزاد ماسٹر میں آپ کے تمام کسٹمرز کے ناپ، رابطے اور مالیاتی حسابات آپ کے ذاتی اکاؤنٹ میں محفوظ رہتے ہیں۔",
  "privacyPolicyP2": "کوئی بھی غیر متعلقہ شخص آپ کے ناپ کا ڈیٹا نہیں دیکھ سکتا۔ تمام ڈیٹا انکرپٹڈ اور نجی ہے۔",
  "closePrivacy": "ٹھیک ہے، سمجھ گیا",
  "secureStorage100": "100% محفوظ کلاؤڈ اسٹوریج",
  "safeBadge": "محفوظ",
  "chatbotHeaderTitle": "آزاد ماسٹر اسسٹنٹ",
  "chatbotHeaderSub": "آن لائن کٹنگ و درزی اسسٹنٹ",
  "voiceReplyActive": "آواز جواب فعال",
  "voiceReplyMuted": "آواز بند ہے",
  "typingInputPlaceholder": "ناپ لکھیں یا درزی سوال پوچھیں...",
  "detectedMeasurementsHeading": "پہچانے گئے ناپ",
  "confirmAndApplySlip": "تصدیق کر کے سلپ میں لگائیں",
  "confirmedMeasurement": "تصدیق شدہ",
  "micListeningState": "سن رہا ہوں... فرمائیے",
  "micStartState": "بولیں",
  "voiceScreenTitle": "آزاد وائس اسسٹنٹ",
  "voiceScreenSub": "براہِ راست گفتگو",
  "tapToSpeak": "بولنے کے لیے ٹیپ کریں",
  "listeningVoice": "سن رہا ہوں...",
  "processingVoice": "پروسیسنگ ہو رہی ہے...",
  "botSpeaking": "جواب بول رہا ہے...",
  "closeVoiceMode": "وائس موڈ بند کریں",
  "browserNoVoice": "اس براؤزر میں آواز کی شناخت کی سہولت موجود نہیں۔",
  "chatbotGreeting": "السلام علیکم! میں آزاد ماسٹر اسسٹنٹ ہوں۔ آپ ناپ بول کر یا لکھ کر بتا سکتے ہیں (لمبائی، تیرا، بازو، چھاتی، کمر، دامن، کالر، شلوار، پانچہ)۔ میں ناپ ترتیب دے کر سلپ میں درج کروا دوں گا۔",
  "quickPrompt1": "لمبائی 42، تیرا 18.5، بازو 23، چھاتی 38، دامن 24، کالر 15.5، شلوار 38، پانچہ 8.5",
  "quickPrompt2": "مردانہ سوٹ کے لیے کتنا کپڑا درکار ہوتا ہے؟",
  "quickPrompt3": "تیرا اور موڈھا (آرم ہول) نکالنے کا فارمولا کیا ہے؟",
  "quickPrompt4": "کالر اور بین کا ہالہ صحیح کیسے کاٹا جائے؟",
  "login": "لاگ ان",
  "codePlaceholder": "واٹس ایپ نمبر یا کوڈ لکھیں...",
  "pinHint": "ڈیفالٹ پن: 123456 (یا داخل ہونے کے لیے خالی چھوڑیں)",
  "signingIn": "سائن ان ہو رہا ہے...",
  "signInWithGoogle": "Google اکاؤنٹ سے محفوظ لاگ ان",
  "openInNewTab": "نئی ونڈو میں کھولیں",
  "tryRedirectLogin": "ری ڈائریکٹ لاگ ان آزمائیں",
  "openInNewWindow": "براہ راست نئی ونڈو میں لاگ ان",
  "secureRecords": "100% محفوظ اور نجی ریکارڈز",
  "loginPrivacyNotice": "ہر درزی ماسٹر اپنے گوگل اکاؤنٹ سے لاگ ان ہوتا ہے اور اس کے کسٹمرز کے ناپ بالکل نجی اور محفوظ رہتے ہیں۔",
  "currentDomainLabel": "موجودہ ڈومین (Firebase Authorized Domains):",
  "copyDomainBtn": "ڈومین کاپی کریں",
  "copiedDomainMsg": "کاپی ہو گیا!",
  "authorizedDomainTip": "اس ڈومین کو Firebase Console > Authentication > Settings > Authorized Domains میں شامل کریں۔",
  "deleteConfirm": "کیا آپ واقعی یہ سلپ حذف کرنا چاہتے ہیں؟",
  "deleteSuccess": "کسٹمر سلپ کامیابی سے حذف کر دی گئی۔",
  "saveSuccess": "کسٹمر سلپ کامیابی سے محفوظ ہو گئی۔",
  "syncSuccess": "تمام ریکارڈز کلاؤڈ پر محفوظ ہو گئے۔"
}

# SINDHI (sd)
sd = {
  "title": "آزاد ماسٽر",
  "subtitle": "محفوظ درزي کاتو ۽ ڪٽنگ رجسٽر",
  "appSubtitle": "پيشيور درزي ڊجيٽل ڪلائوڊ رجسٽر",
  "defaultMasterTitle": "استاد صاحب",
  "masterNameLabel": "استاد جو نالو:",
  "masterPhotoLabel": "استاد جو فوٽو لڳايو:",
  "masterDefaultName": "استاد صاحب",
  "navHome": "هوم",
  "navSettings": "سيٽنگون",
  "navAdd": "ماپ لکو",
  "searchPlaceholder": "گراهڪ جو نالو يا فون نمبر ڳولهيو...",
  "searchAction": "ڳولها",
  "clear": "صاف ڪريو",
  "recentSearches": "تازيون ڳولهائون",
  "clearHistory": "هسٽري صاف ڪريو",
  "openSlip": "سلپ کوليو",
  "addMeasurementBtn": "ماپ لکو",
  "photoOcrBtn": "پرچو / ڪپڙي جو فوٽو",
  "cuttingMode": "✂️ ڪٽنگ موڊ",
  "normalMode": "عام موڊ",
  "voiceInput": "آواز سان ماپ داخل ڪريو",
  "chatbot": "آزاد ماسٽر اسسٽنٽ",
  "assistant": "اسسٽنٽ",
  "settings": "سيٽنگون ۽ پروفائل",
  "privacy": "رازداري پاليسي",
  "logout": "لاگ آئوٽ",
  "customerSlipsHeading": "گراهڪن جون ڪٽنگ سلپون:",
  "statusFiltersHeading": "آرڊر حالت فلٽر:",
  "showingCount": "ڏيکاريل:",
  "allFilter": "سڀ",
  "statusPending": "ڪم هيٺ",
  "statusCutting": "ڪٽنگ",
  "statusStitching": "سبائي جاري",
  "statusReady": "يار آهي",
  "statusDelivered": "حوالي ڪيو ويو",
  "todayDelivery": "اڄوڪي پهچائڻ:",
  "lateOrders": "دير ٿيل آرڊر:",
  "totalCustomers": "ڪل گراهڪ",
  "quickStats": "خلاصو",
  "recentOrders": "تازا آرڊر (جلدي ڏسو)",
  "recentOrdersCount": "تازا ترين",
  "show": "ڏيکاريو",
  "hide": "لڪايو",
  "noRecords": "ڪوبه رڪارڊ نه مليو.",
  "noCustomerFound": "ڪوبه گراهڪ نه مليو",
  "noCustomersSaved": "اڃا تائين ڪوبه گراهڪ محفوظ ناهي ٿيو",
  "searchHintEmpty": "ڪنهن ٻئي نالي يا فون نمبر سان ڳولها ڪريو.",
  "addFirstCustomerHint": "پهريون گراهڪ داخل ڪرڻ لاءِ هيٺيون بٽڻ دٻايو.",
  "addFirstCustomer": "پهريون گراهڪ داخل ڪريو",
  "tapToAdd": "نئين ماپ درج ڪرڻ لاءِ هيٺين (+) بٽڻ تي ٽيپ ڪريو.",
  "tapToAddCustomer": "نئون گراهڪ شامل ڪرڻ لاءِ هتي ڪلڪ ڪريو.",
  "addAsNewCustomer": "بطور نئون گراهڪ",
  "unnamedCustomer": "اڻڄاتل گراهڪ",
  "date": "تاريخ:",
  "delivery": "واپسي:",
  "balance": "باقي:",
  "cleared": "مڪمل ادائگي",
  "syncing": "سنڪ ٿي رهيو آهي...",
  "cloudSynced": "ڪلائوڊ تي محفوظ",
  "syncNow": "هاڻي سنڪ ڪريو",
  "cloudSyncError": "ڪلائوڊ غلطي",
  "online": "آن لائين",
  "selectPhotoSource": "پرچي يا ڪپڙي جو فوٽو چونڊيو",
  "camera": "ڪيمرا",
  "gallery": "گيلري",
  "fillManually": "پاڻ فارم ڀريو",
  "uploadPhotoTitle": "ڪاغذي پرچي جو فوٽو:",
  "galleryBtn": "🖼️ گيلري",
  "cameraBtn": "📸 ڪيمرا",
  "removePhoto": "فوٽو هٽايو",
  "extractingOcr": "فوٽو مان ماپ پڙهي پئي وڃي...",
  "addSlip": "نئين ماپ داخل ڪريو",
  "editSlip": "ماپ ۾ ڦيرڦار ڪريو",
  "customerName": "گراهڪ جو نالو *",
  "phoneNumber": "واٽس ايپ نمبر (اختياري)",
  "countryCodeLabel": "ملڪ جو ڪوڊ",
  "suitTypeLabel": "سُوٽ جو قسم",
  "suitGents": "مردانو سوٽ (شلوار قميص)",
  "suitKurtaPajama": "ڪرتا پاجامو",
  "suitSafari": "سفاري سوٽ",
  "suitWaistcoat": "واسڪوٽ",
  "suitSherwani": "شيرواني",
  "deliveryDateLabel": "واپسي جي تاريخ",
  "quickToday": "اڄ",
  "quickTomorrow": "سڀاڻي",
  "quick3Days": "3 ڏينهن",
  "quick1Week": "1 هفتو",
  "quick10Days": "10 ڏينهن",
  "orderStatusLabel": "آرڊر اسٽيٽس:",
  "orderLockedNotice": "هي آرڊر مڪمل ٿيل ۽ لاڪ آهي. ڇا اوهان واقعي کيس ان لاڪ ڪرڻ چاهيو ٿا؟",
  "orderLockedBadge": "🔒 لاڪ ٿيل",
  "orderUnlockedBadge": "🔓 کليل",
  "dueTodayBadge": "⚡ اڄ جي پهچائڻ",
  "lateOrderBadge": "⚠️ دير ٿيل",
  "upcomingBadge": "📅 اڳيان ايندڙ",
  "lengthLabel": "ڊيگهه",
  "shoulderLabel": "ٽيرو",
  "sleevesLabel": "ٻانهن",
  "chestLabel": "ڇاتي",
  "waistLabel": "چيلهه / چيلھ",
  "daamanLabel": "گھيرو / دامن",
  "collarLabel": "ڪالر / بين",
  "shalwarLabel": "شلوار",
  "panchaLabel": "پانچو",
  "pocketLabel": "کيسو / جيب",
  "specialNotesLabel": "خاص نوٽ / هدايتون",
  "notesPlaceholder": "مثال گول گهيرو، بين ڪالر، سنواريل سلائي...",
  "billingHeading": "سبائي کاتو ۽ بِل:",
  "totalAmountLabel": "ڪل رقم",
  "advanceAmountLabel": "اڳواٽ مليل (ايڊوانس)",
  "balanceAmountLabel": "باقي رقم",
  "fullyPaidBadge": "✓ سڀ ادا ٿيل",
  "balanceDueBadge": "⏳ باقي رهيل رقم",
  "saveDone": "محفوظ ڪريو ۽ مڪمل",
  "saveClose": "محفوظ ڪريو ۽ بند ڪريو",
  "cancel": "رد ڪريو",
  "close": "ٿي ويو / بند",
  "back": "پوئتي",
  "digitalSlip": "ڊجيٽل ڪٽنگ سلپ",
  "editMode": "ڦيرڦار / ڪٽنگ موڊ",
  "sendWhatsapp": "واٽس ايپ تي سلپ موڪليو",
  "copySlip": "سلپ ڪاپي ڪريو",
  "printSlip": "پرنٽ ڪڍو",
  "delete": "ڊليٽ ڪريو",
  "copySuccess": "سلپ ڪلپ بورڊ تي ڪاپي ٿي وئي!",
  "bookedDateLabel": "بڪنگ:",
  "deliveryDatePrefix": "واپسي جي تاريخ:",
  "tailorStamp": "استاد درزي جي مهر",
  "customerDetailsHeading": "گراهڪ جا تفصيل",
  "measurementsHeading": "ماپ جا تفصيل",
  "accountSummaryHeading": "بِل جو خلاصو",
  "menuTitle": "آزاد ماسٽر مينيو",
  "profileSettings": "پروفائل ۽ ترتيبون",
  "changeLanguage": "ٻولي تبديل ڪريو",
  "dataBackup": "ڪلائوڊ بيڪ اپ ۽ سنڪ",
  "helpSupport": "رهنمائي ۽ استعمال جو طريقو",
  "developerInfo": "ڊولپر جي ڄاڻ",
  "settingsTitle": "پروفائل ۽ ايپ سيٽنگون",
  "selectAppLanguage": "ايپ جي ٻولي",
  "allSupportedLanguages": "سڀ 22 ٻوليون:",
  "aiVoiceAssistant": "آزاد اي آءِ وائيس اسسٽنٽ",
  "aiVoiceAssistantSub": "ماپ ڳالهايو يا لکو، خودڪار ڪٽنگ حساب",
  "appGuide": "استعمال جو طريقو (رهنمائي)",
  "appGuideSub": "ماپ داخل ڪرڻ، OCR پرچو، ٽريڪنگ ۽ واٽس ايپ",
  "cloudAutoSave": "ڪلائوڊ آٽو سيو (Firebase Cloud)",
  "cloudAutoSaveLive": "فعال ۽ محفوظ",
  "cloudDatabaseLabel": "ڪلائوڊ ڊيٽابيس:",
  "cloudRecordsLabel": "ڪلائوڊ رڪارڊ:",
  "lastSyncedLabel": "آخري سنڪ:",
  "syncAllNow": "سڀ ڊيٽا ڪلائوڊ تي هاڻي محفوظ ڪريو",
  "syncingToCloud": "ڪلائوڊ تي محفوظ ٿي رهيو آهي...",
  "dataBackupRestore": "ڊيٽا بيڪ اپ ۽ بحالي",
  "recordsCount": "رڪارڊ",
  "backupData": "بيڪ اپ ٺاهيو (JSON)",
  "restoreData": "بحال ڪريو (JSON)",
  "developerCredit": "ڊولپر: نصيب ايس اي او (پير بخش)",
  "copyrightNotice": "سڀ حق ۽ واسطا محفوظ آهن © 2026 آزاد ماسٽر",
  "resetAllRecords": "سڀ ڪٽنگ سلپون ختم ڪريو",
  "resetRecordsConfirm": "ڇا اوهان واقعي سڀني گراهڪن جو رڪارڊ ختم ڪرڻ چاهيو ٿا؟",
  "savedSuccess": "محفوظ ٿي ويو!",
  "cloudSyncSuccess": "رڪارڊ ڪلائوڊ تي ڪاميابي سان محفوظ ٿيا!",
  "noRecordsToBackup": "بيڪ اپ لاءِ ڪوبه رڪارڊ موجود ناهي!",
  "backupFileDownloaded": "بيڪ اپ فائل ڪاميابي سان ڊائونلوڊ ٿي وئي!",
  "recordsRestoredSuccess": "رڪارڊ ڪاميابي سان بحال ٿي ويا!",
  "noValidRecordsFound": "فائل ۾ ڪوبه درست رڪارڊ نه مليو.",
  "invalidBackupFile": "غلط فائل. مهرباني ڪري صحيح JSON فائل چونڊيو.",
  "needHelpTitle": "مدد گهرجي؟ / سهڪار",
  "contactWhatsApp": "واٽس ايپ تي رابطو ڪريو",
  "contactEmail": "اي ميل تي رابطو",
  "appGuideTitle": "آزاد ماسٽر استعمال ڪرڻ جو طريقو",
  "guideStep1Title": "1. نئين ماپ داخل ڪرڻ",
  "guideStep1Desc": "هيٺ ڏنل پلس (+) بٽڻ تي ڪلڪ ڪري گراهڪ جو نالو، فون ۽ ناپ لکو.",
  "guideStep2Title": "2. ✂️ ڪٽنگ موڊ جو جادو",
  "guideStep2Desc": "ڪٽنگ ٽيبل تي ڪم ڪندي ڪٽنگ موڊ آن ڪريو جنهن سان ماپون وڏيون ۽ چٽيون نظر اينديون.",
  "guideStep3Title": "3. پرچو / ڪپڙي جو فوٽو ۽ اي آءِ اسڪين",
  "guideStep3Desc": "گراهڪ جي پراڻي ڪاغذي پرچي جو فوٽو ڪڍو، اي آءِ پاڻمرادو ماپون ڪڍي ڏيندو.",
  "guideStep4Title": "4. ڊجيٽل واٽس ايپ سلپ ۽ ڪلائوڊ",
  "guideStep4Desc": "هڪ ڪلڪ سان گراهڪ کي واٽس ايپ تي مڪمل سلپ موڪليو ۽ ڊيٽا ڪلائوڊ تي محفوظ رکو.",
  "closeGuide": "سمجهه ۾ اچي ويو / بند ڪريو",
  "privacyModalTitle": "رازداري ۽ ڊيٽا پروٽيڪشن",
  "privacyPolicyP1": "آزاد ماسٽر ۾ اوهان جي سڀني گراهڪن جون ماپون، رابطا ۽ کاتا اوهان جي ذاتي اڪائونٽ ۾ محفوظ آهن.",
  "privacyPolicyP2": "ڪوبه ٻيو شخص اوهان جو درزي رڪارڊ نٿو ڏسي سگهي. سڀ ڊيٽا انڪرپٽ ۽ نِجي آهي.",
  "closePrivacy": "ٺيڪ آهي، سمجهي ويس",
  "secureStorage100": "100% محفوظ ڪلائوڊ اسٽوريج",
  "safeBadge": "محفوظ",
  "chatbotHeaderTitle": "آزاد ماسٽر اسسٽنٽ",
  "chatbotHeaderSub": "آن لائين درزي ۽ ڪٽنگ اسسٽنٽ",
  "voiceReplyActive": "آواز جواب آن",
  "voiceReplyMuted": "آواز بند آهي",
  "typingInputPlaceholder": "ماپ لکو يا ڪٽنگ بابت سوال پڇو...",
  "detectedMeasurementsHeading": "سڃاتل ماپون",
  "confirmAndApplySlip": "تصديق ڪري سلپ ۾ لڳايو",
  "confirmedMeasurement": "تصديق ٿيل",
  "micListeningState": "ٻڌي رهيو آهيان... فرمايو",
  "micStartState": "ڳالهايو",
  "voiceScreenTitle": "آزاد وائيس اسسٽنٽ",
  "voiceScreenSub": "سڌو سنئون ڳالهه ٻولهه",
  "tapToSpeak": "ڳالهائڻ لاءِ ٽيپ ڪريو",
  "listeningVoice": "ٻڌي رهيو آهيان...",
  "processingVoice": "پروسيس ٿي رهيو آهي...",
  "botSpeaking": "جواب ڳالهائي رهيو آهي...",
  "closeVoiceMode": "وائيس موڊ بند ڪريو",
  "browserNoVoice": "هن برائوزر ۾ آواز سڃاڻڻ جي سهولت ناهي.",
  "chatbotGreeting": "اسلام عليڪم! مان آزاد ماسٽر اسسٽنٽ آهيان. اوهان ماپ ڳالهائي يا لکي سگهو ٿا (ڊيگهه، ٽيرو، ٻانهن، ڇاتي، چيلهه، گهيرو، ڪالر، شلوار، پانچو). مان ماپ ترتيب ڏئي محفوظ ڪرائيندس.",
  "quickPrompt1": "ڊيگهه 42، ٽيرو 18.5، ٻانهن 23، ڇاتي 38، گهيرو 24، ڪالر 15.5، شلوار 38",
  "quickPrompt2": "مرداني سوٽ لاءِ ڪيترو ڪپڙو کپندو؟",
  "quickPrompt3": "ٽيرو ۽ مڍو ڪٽڻ جو ڪهڙو فارمولو آهي؟",
  "quickPrompt4": "ڪالر ۽ بين جي ڪٽائي صحيح ڪيئن ڪجي؟",
  "login": "لاگ ان",
  "codePlaceholder": "واٽس ايپ نمبر يا ڪوڊ لکو...",
  "pinHint": "ڊفالٽ پن: 123456 (يا ائين ئي داخل ٿيو)",
  "signingIn": "سائن ان ٿي رهيو آهي...",
  "signInWithGoogle": "Google اڪائونٽ سان محفوظ لاگ ان",
  "openInNewTab": "نئين ٽئب ۾ کوليو",
  "tryRedirectLogin": "ري ڊائريڪٽ لاگ ان آزمايو",
  "openInNewWindow": "سڌو نئين ونڊو ۾ کوليو",
  "secureRecords": "100% محفوظ ۽ نِجي رڪارڊ",
  "loginPrivacyNotice": "هر درزي ماسٽر پنهنجي گوگل اڪائونٽ سان داخل ٿئي ٿو ۽ سندس ماپون مڪمل نِجي رهن ٿيون.",
  "currentDomainLabel": "موجوده ڊومين (Firebase Authorized Domains):",
  "copyDomainBtn": "ڊومين ڪاپي ڪريو",
  "copiedDomainMsg": "ڪاپي ٿي ويو!",
  "authorizedDomainTip": "هن ڊومين کي Firebase Console > Authentication > Settings > Authorized Domains ۾ شامل ڪريو.",
  "deleteConfirm": "ڇا اوهان واقعي هي سلپ ڊليٽ ڪرڻ چاهيو ٿا؟",
  "deleteSuccess": "گراهڪ جي سلپ ڪاميابي سان ڊليٽ ٿي وئي.",
  "saveSuccess": "گراهڪ جي سلپ ڪاميابي سان محفوظ ٿي وئي.",
  "syncSuccess": "سڀ رڪارڊ ڪلائوڊ تي محفوظ ٿي ويا."
}

# ARABIC (ar)
ar = {
  "title": "أستاذ آزاد",
  "subtitle": "إدارة الخياطة والقياسات الرقمية الآمنة",
  "appSubtitle": "سجل الخياط المحترف السحابي الرقمي",
  "defaultMasterTitle": "المعلم الخياط",
  "masterNameLabel": "اسم الخياط المعلم:",
  "masterPhotoLabel": "تحميل صورة المعلم:",
  "masterDefaultName": "المعلم الخياط",
  "navHome": "الرئيسية",
  "navSettings": "الإعدادات",
  "navAdd": "إضافة قياس",
  "searchPlaceholder": "ابحث بالاسم أو برقم الهاتف...",
  "searchAction": "بحث",
  "clear": "مسح",
  "recentSearches": "عمليات البحث الأخيرة",
  "clearHistory": "مسح السجل",
  "openSlip": "فتح البطاقة",
  "addMeasurementBtn": "إضافة قياس",
  "photoOcrBtn": "صورة الورقة / القماش",
  "cuttingMode": "✂️ وضع القص",
  "normalMode": "الوضع العادي",
  "voiceInput": "إدخال صوتي",
  "chatbot": "مساعد أستاذ آزاد",
  "assistant": "المساعد",
  "settings": "الإعدادات والملف الشخصي",
  "privacy": "سياسة الخصوصية",
  "logout": "تسجيل الخروج",
  "customerSlipsHeading": "بطاقات قياس العملاء:",
  "statusFiltersHeading": "تصفية حالة الطلب:",
  "showingCount": "المعروض:",
  "allFilter": "الكل",
  "statusPending": "قيد الانتظار",
  "statusCutting": "جارٍ القص",
  "statusStitching": "جارٍ الخياطة",
  "statusReady": "جاهز للاستلام",
  "statusDelivered": "تم التسليم",
  "todayDelivery": "تسليمات اليوم:",
  "lateOrders": "طلبات متأخرة:",
  "totalCustomers": "إجمالي العملاء",
  "quickStats": "نظرة عامة",
  "recentOrders": "الطلبات الأخيرة (عرض سريع)",
  "recentOrdersCount": "الأحدث",
  "show": "إظهار",
  "hide": "إخفاء",
  "noRecords": "لم يتم العثور على سجلات.",
  "noCustomerFound": "لم يتم العثور على أي عميل",
  "noCustomersSaved": "لم يتم حفظ أي عميل بعد",
  "searchHintEmpty": "جرب البحث باسم أو رقم هاتف آخر.",
  "addFirstCustomerHint": "اضغط على الزر أدناه لإضافة أول بطاقة قياس.",
  "addFirstCustomer": "إضافة أول عميل",
  "tapToAdd": "اضغط على زر (+) أدناه لإضافة بطاقة قياس جديدة.",
  "tapToAddCustomer": "اضغط هنا لإضافة عميل جديد.",
  "addAsNewCustomer": "كعميل جديد",
  "unnamedCustomer": "عميل غير مسمى",
  "date": "التاريخ:",
  "delivery": "التسليم:",
  "balance": "المتبقي:",
  "cleared": "مدفوع بالكامل",
  "syncing": "جارٍ المزامنة...",
  "cloudSynced": "تم الحفظ بالسحاب",
  "syncNow": "مزامنة الآن",
  "cloudSyncError": "خطأ في المزامنة",
  "online": "متصل",
  "selectPhotoSource": "اختر صورة بطاقة القياس أو القماش",
  "camera": "الكاميرا",
  "gallery": "المعرض",
  "fillManually": "تعبئة يدوية",
  "uploadPhotoTitle": "صورة الورقة التقليدية:",
  "galleryBtn": "🖼️ المعرض",
  "cameraBtn": "📸 الكاميرا",
  "removePhoto": "إزالة الصورة",
  "extractingOcr": "جارٍ استخراج القياسات بالذكاء الاصطناعي...",
  "addSlip": "إضافة بطاقة قياس جديدة",
  "editSlip": "تعديل بطاقة القياس",
  "customerName": "اسم العميل *",
  "phoneNumber": "رقم الواتساب (اختياري)",
  "countryCodeLabel": "رمز الدولة",
  "suitTypeLabel": "نوع الثوب",
  "suitGents": "ثوب رجالي (دشداشة / قميص)",
  "suitKurtaPajama": "كورتا وبيجامة",
  "suitSafari": "بدلة سفاري",
  "suitWaistcoat": "سديري / صدار",
  "suitSherwani": "شرواني رسمي",
  "deliveryDateLabel": "تاريخ التسليم",
  "quickToday": "اليوم",
  "quickTomorrow": "غداً",
  "quick3Days": "3 أيام",
  "quick1Week": "أسبوع",
  "quick10Days": "10 أيام",
  "orderStatusLabel": "حالة الطلب:",
  "orderLockedNotice": "هذا الطلب مكتمل ومقفل. هل تريد فعلاً إلغاء القفل وتغيير الحالة؟",
  "orderLockedBadge": "🔒 مقفل",
  "orderUnlockedBadge": "🔓 قابل للتغيير",
  "dueTodayBadge": "⚡ تسليم اليوم",
  "lateOrderBadge": "⚠️ متأخر",
  "upcomingBadge": "📅 قادم",
  "lengthLabel": "الطول",
  "shoulderLabel": "الكتف",
  "sleevesLabel": "الكم",
  "chestLabel": "الصدر",
  "waistLabel": "الخصر",
  "daamanLabel": "الحاشية / الوسع",
  "collarLabel": "الياقة / الرقبة",
  "shalwarLabel": "السروال",
  "panchaLabel": "فتحة السروال / البانشا",
  "pocketLabel": "الجيب",
  "specialNotesLabel": "ملاحظات وتعليمات خاصة",
  "notesPlaceholder": "مثلاً: قصة سليم، ياقة فرنسية، جيب قلاب...",
  "billingHeading": "الحساب والدفع:",
  "totalAmountLabel": "المبلغ الإجمالي",
  "advanceAmountLabel": "الدفعة المقدمة (عربون)",
  "balanceAmountLabel": "المبلغ المتبقي",
  "fullyPaidBadge": "✓ مدفوع بالكامل",
  "balanceDueBadge": "⏳ متبقٍ مستحق",
  "saveDone": "حفظ وإنهاء",
  "saveClose": "حفظ وإغلاق",
  "cancel": "إلغاء",
  "close": "تم / إغلاق",
  "back": "رجوع",
  "digitalSlip": "بطاقة القص الرقمية",
  "editMode": "تعديل / وضع القص",
  "sendWhatsapp": "إرسال البطاقة عبر واتساب",
  "copySlip": "نسخ البطاقة",
  "printSlip": "طباعة البطاقة",
  "delete": "حذف",
  "copySuccess": "تم نسخ البطاقة بنجاح!",
  "bookedDateLabel": "تاريخ الحجز:",
  "deliveryDatePrefix": "تاريخ التسليم:",
  "tailorStamp": "ختم الخياط المعلم",
  "customerDetailsHeading": "بيانات العميل",
  "measurementsHeading": "تفاصيل القياسات",
  "accountSummaryHeading": "ملخص الحساب",
  "menuTitle": "قائمة أستاذ آزاد",
  "profileSettings": "الملف الشخصي والإعدادات",
  "changeLanguage": "تغيير اللغة",
  "dataBackup": "النسخ الاحتياطي والمزامنة السحابية",
  "helpSupport": "دليل الاستخدام والتعليمات",
  "developerInfo": "معلومات المطور",
  "settingsTitle": "الملف الشخصي وإعدادات التطبيق",
  "selectAppLanguage": "لغة التطبيق",
  "allSupportedLanguages": "جميع اللغات الـ 22 المدعومة:",
  "aiVoiceAssistant": "المساعد الصوتي الذكي",
  "aiVoiceAssistantSub": "تحدث أو اكتب القياسات لحساب القص التلقائي",
  "appGuide": "دليل الاستخدام",
  "appGuideSub": "إدخال القياسات، مسح الصور، التتبع والواتساب",
  "cloudAutoSave": "الحفظ السحابي التلقائي (Firebase Cloud)",
  "cloudAutoSaveLive": "نشط وآمن",
  "cloudDatabaseLabel": "قاعدة البيانات السحابية:",
  "cloudRecordsLabel": "السجلات السحابية:",
  "lastSyncedLabel": "آخر مزامنة:",
  "syncAllNow": "مزامنة جميع البيانات إلى السحابة الآن",
  "syncingToCloud": "جارٍ المزامنة السحابية...",
  "dataBackupRestore": "النسخ الاحتياطي واستعادة البيانات",
  "recordsCount": "سجلات",
  "backupData": "إنشاء نسخة احتياطية (JSON)",
  "restoreData": "استعادة البيانات (JSON)",
  "developerCredit": "تطوير: نسيب سيو (بير بخش)",
  "copyrightNotice": "جميع الحقوق محفوظة © 2026 أستاذ آزاد",
  "resetAllRecords": "مسح جميع سجلات القياسات",
  "resetRecordsConfirm": "هل أنت متأكد من رغبتك في حذف جميع سجلات العملاء؟",
  "savedSuccess": "تم الحفظ بنجاح!",
  "cloudSyncSuccess": "سجلات تمت مزامنتها بنجاح إلى السحابة!",
  "noRecordsToBackup": "لا توجد سجلات للنسخ الاحتياطي!",
  "backupFileDownloaded": "تم تنزيل ملف النسخة الاحتياطية بنجاح!",
  "recordsRestoredSuccess": "تمت استعادة السجلات بنجاح!",
  "noValidRecordsFound": "لم يتم العثور على سجلات صالحة في الملف.",
  "invalidBackupFile": "ملف غير صالح. يرجى اختيار ملف JSON صحيح.",
  "needHelpTitle": "هل تحتاج مساعدة؟ / الدعم الفني",
  "contactWhatsApp": "تواصل عبر واتساب",
  "contactEmail": "الدعم عبر البريد الإلكتروني",
  "appGuideTitle": "كيفية استخدام أستاذ آزاد",
  "guideStep1Title": "1. إضافة قياس جديد",
  "guideStep1Desc": "اضغط على زر (+) أو 'إضافة قياس' لإدخال اسم العميل وهاتفه وتفاصيل مقاساته وتاريخ التسليم.",
  "guideStep2Title": "2. ✂️ سحر وضع القص",
  "guideStep2Desc": "فعل وضع القص عند طاولة التفصيل لعرض الأرقام بخط كبير وواضح يسهل قراءته من مسافة بعيدة.",
  "guideStep3Title": "3. صورة الورقة وقراءة الذكاء الاصطناعي",
  "guideStep3Desc": "التقط صورة لورقة القياس التقليدية وسيقوم الذكاء الاصطناعي بقراءة وتعبئة القياسات تلقائياً.",
  "guideStep4Title": "4. بطاقة الواتساب الرقمية والسحابة",
  "guideStep4Desc": "أرسل بطاقة القياس الرقمية للعميل بنقرة واحدة على واتساب مع حفظ مشفر على السحابة.",
  "closeGuide": "فهمت / إغلاق الدليل",
  "privacyModalTitle": "سياسة الخصوصية وحماية البيانات",
  "privacyPolicyP1": "جميع قياسات عملائك وتفاصيل الاتصال وحساباتك المالية مخزنة بأمان فائق في حسابك السحابي الخاص.",
  "privacyPolicyP2": "لا يمكن لأي طرف ثالث الوصول إلى بيانات خياطتك. جميع البيانات مشفرة وخاصة بتسجيل دخولك.",
  "closePrivacy": "موافق وإغلاق",
  "secureStorage100": "تخزين سحابي آمن 100%",
  "safeBadge": "آمن ومحمي",
  "chatbotHeaderTitle": "مساعد أستاذ آزاد",
  "chatbotHeaderSub": "مساعد التفصيل والخياطة الذكي",
  "voiceReplyActive": "الرد الصوتي مفعّل",
  "voiceReplyMuted": "الرد الصوتي صامت",
  "typingInputPlaceholder": "اكتب القياسات أو اسأل سؤالاً حول الخياطة...",
  "detectedMeasurementsHeading": "القياسات المكتشفة",
  "confirmAndApplySlip": "تأكيد وتطبيق في البطاقة",
  "confirmedMeasurement": "تم التأكيد",
  "micListeningState": "أستمع إليك... تفضل بالتحدث",
  "micStartState": "تحدث",
  "voiceScreenTitle": "المساعد الصوتي آزاد",
  "voiceScreenSub": "محادثة صوتية حية",
  "tapToSpeak": "اضغط للتحدث",
  "listeningVoice": "جارٍ الاستماع...",
  "processingVoice": "جارٍ المعالجة...",
  "botSpeaking": "جارٍ نطق الرد...",
  "closeVoiceMode": "إنهاء الوضع الصوتي",
  "browserNoVoice": "التعرف على الصوت غير مدعوم في هذا المتصفح.",
  "chatbotGreeting": "مرحباً بك! أنا مساعد أستاذ آزاد. يمكنك نطق أو كتابة المقاسات (الطول، الكتف، الكم، الصدر، الخصر، الحاشية، الياقة، السروال). سأقوم بترتيبها وتأكيدها قبل الحفظ.",
  "quickPrompt1": "الطول 42، الكتف 18.5، الكم 23، الصدر 38، الوسع 24، الياقة 15.5، السروال 38",
  "quickPrompt2": "كم ياردة قماش تلزم لخياطة ثوب رجالي؟",
  "quickPrompt3": "ما هي معادلة قص حرملة الكم والكتف؟",
  "quickPrompt4": "كيفية قص حردة الياقة بدقة متناهية؟",
  "login": "تسجيل الدخول",
  "codePlaceholder": "أدخل رقم الواتساب أو الرمز...",
  "pinHint": "الرمز الافتراضي: 123456 (أو اتركه فارغاً للدخول)",
  "signingIn": "جارٍ تسجيل الدخول...",
  "signInWithGoogle": "تسجيل الدخول الآمن بحساب Google",
  "openInNewTab": "فتح في نافذة جديدة",
  "tryRedirectLogin": "تجربة تسجيل الدخول بإعادة التوجيه",
  "openInNewWindow": "فتح تسجيل الدخول مباشرة في نافذة جديدة",
  "secureRecords": "سجلات خاصة وآمنة 100%",
  "loginPrivacyNotice": "يسجل كل خياط الدخول بحسابه الخاص على Google، وتظل قياسات عملائه وسجلاته سرية ومشفرة تماماً.",
  "currentDomainLabel": "النطاق الحالي (Firebase Authorized Domains):",
  "copyDomainBtn": "نسخ النطاق",
  "copiedDomainMsg": "تم النسخ!",
  "authorizedDomainTip": "أضف هذا النطاق في: Firebase Console > Authentication > Settings > Authorized Domains.",
  "deleteConfirm": "هل أنت متأكد من رغبتك في حذف هذه البطاقة؟",
  "deleteSuccess": "تم حذف بطاقة العميل بنجاح.",
  "saveSuccess": "تم حفظ بطاقة العميل بنجاح.",
  "syncSuccess": "تمت مزامنة جميع السجلات إلى السحابة."
}

# PERSIAN (fa)
fa = {
  "title": "استاد آزاد",
  "subtitle": "مدیریت امن خیاطی و دفتر برش دیجیتال",
  "appSubtitle": "دفتر کل ابری دیجیتال خیاط حرفه‌ای",
  "defaultMasterTitle": "استاد خیاط",
  "masterNameLabel": "نام استاد:",
  "masterPhotoLabel": "تصویر استاد:",
  "masterDefaultName": "استاد خیاط",
  "navHome": "خانه",
  "navSettings": "تنظیمات",
  "navAdd": "ثبت اندازه",
  "searchPlaceholder": "جستجوی نام یا شماره مشتری...",
  "searchAction": "جستجو",
  "clear": "پاک کردن",
  "recentSearches": "جستجوهای اخیر",
  "clearHistory": "پاک کردن تاریخچه",
  "openSlip": "باز کردن برگه",
  "addMeasurementBtn": "ثبت اندازه",
  "photoOcrBtn": "عکس برگه / پارچه",
  "cuttingMode": "✂️ حالت برش",
  "normalMode": "حالت عادی",
  "voiceInput": "ورودی صوتی",
  "chatbot": "دستیار استاد آزاد",
  "assistant": "دستیار",
  "settings": "تنظیمات و نمایه",
  "privacy": "سیاست حفظ حریم خصوصی",
  "logout": "خروج",
  "customerSlipsHeading": "برگه‌های اندازه‌گیری مشتریان:",
  "statusFiltersHeading": "فیلتر وضعیت سفارش:",
  "showingCount": "نمایش:",
  "allFilter": "همه",
  "statusPending": "در انتظار",
  "statusCutting": "در حال برش",
  "statusStitching": "در حال دوخت",
  "statusReady": "آماده تحویل",
  "statusDelivered": "تحویل داده شده",
  "todayDelivery": "تحویل‌های امروز:",
  "lateOrders": "سفارش‌های معوق:",
  "totalCustomers": "کل مشتریان",
  "quickStats": "نمای کلی",
  "recentOrders": "سفارش‌های اخیر (نمای سریع)",
  "recentOrdersCount": "جدیدترین",
  "show": "نمایش",
  "hide": "پنهان کردن",
  "noRecords": "هیچ رکوردی یافت نشد.",
  "noCustomerFound": "مشتری یافت نشد",
  "noCustomersSaved": "هنوز هیچ مشتری ذخیره نشده است",
  "searchHintEmpty": "با نام یا شماره دیگری جستجو کنید.",
  "addFirstCustomerHint": "برای افزودن اولین برگه اندازه، روی دکمه زیر ضربه بزنید.",
  "addFirstCustomer": "افزودن اولین مشتری",
  "tapToAdd": "برای ثبت اندازه جدید روی دکمه (+) زیر ضربه بزنید.",
  "tapToAddCustomer": "برای افزودن مشتری جدید اینجا کلیک کنید.",
  "addAsNewCustomer": "به عنوان مشتری جدید",
  "unnamedCustomer": "مشتری بدون نام",
  "date": "تاریخ:",
  "delivery": "تحویل:",
  "balance": "مانده:",
  "cleared": "تسویه کامل",
  "syncing": "در حال همگام‌سازی...",
  "cloudSynced": "ذخیره در ابری",
  "syncNow": "همگام‌سازی اکنون",
  "cloudSyncError": "خطای همگام‌سازی",
  "online": "آنلاین",
  "selectPhotoSource": "انتخاب تصویر برگه یا پارچه",
  "camera": "دوربین",
  "gallery": "گالری",
  "fillManually": "تکمیل دستی فرم",
  "uploadPhotoTitle": "عکس برگه کاغذی:",
  "galleryBtn": "🖼️ گالری",
  "cameraBtn": "📸 دوربین",
  "removePhoto": "حذف عکس",
  "extractingOcr": "استخراج خودکار اندازه‌ها با هوش مصنوعی...",
  "addSlip": "ثبت برگه اندازه جدید",
  "editSlip": "ویرایش برگه اندازه",
  "customerName": "نام مشتری *",
  "phoneNumber": "شماره واتساپ (اختیاری)",
  "countryCodeLabel": "کد کشور",
  "suitTypeLabel": "نوع لباس",
  "suitGents": "لباس مردانه (شلوار و پیراهن)",
  "suitKurtaPajama": "کورتا و پیژامه",
  "suitSafari": "کت و شلوار سافاری",
  "suitWaistcoat": "جلیقه",
  "suitSherwani": "شروانی مجلسی",
  "deliveryDateLabel": "تاریخ تحویل",
  "quickToday": "امروز",
  "quickTomorrow": "فردا",
  "quick3Days": "۳ روز",
  "quick1Week": "۱ هفته",
  "quick10Days": "۱۰ روز",
  "orderStatusLabel": "وضعیت سفارش:",
  "orderLockedNotice": "این سفارش تحویل داده شده و قفل است. آیا مایلید قفل را باز کرده و وضعیت را تغییر دهید؟",
  "orderLockedBadge": "🔒 قفل شده",
  "orderUnlockedBadge": "🔓 باز شده",
  "dueTodayBadge": "⚡ تحویل امروز",
  "lateOrderBadge": "⚠️ تاخیر دار",
  "upcomingBadge": "📅 آینده",
  "lengthLabel": "قد / بلندی",
  "shoulderLabel": "سرشانه",
  "sleevesLabel": "آستین",
  "chestLabel": "دور سینه",
  "waistLabel": "دور کمر",
  "daamanLabel": "دامن / پایین‌تنه",
  "collarLabel": "یقه",
  "shalwarLabel": "شلوار",
  "panchaLabel": "دمپای شلوار",
  "pocketLabel": "جیب",
  "specialNotesLabel": "نکات و دستورالعمل‌های خاص",
  "notesPlaceholder": "مثلاً دامن هلالی، یقه ایستاده، دوخت تک...",
  "billingHeading": "حساب و کتاب دوخت:",
  "totalAmountLabel": "مبلغ کل",
  "advanceAmountLabel": "بیعانه دریافتی",
  "balanceAmountLabel": "مانده حساب",
  "fullyPaidBadge": "✓ تسویه کامل",
  "balanceDueBadge": "⏳ مانده بدهی",
  "saveDone": "ذخیره و پایان",
  "saveClose": "ذخیره و بستن",
  "cancel": "انصراف",
  "close": "انجام شد / بستن",
  "back": "بازگشت",
  "digitalSlip": "برگه برش دیجیتال",
  "editMode": "ویرایش / حالت برش",
  "sendWhatsapp": "ارسال برگه از طریق واتساپ",
  "copySlip": "کپی برگه",
  "printSlip": "چاپ برگه",
  "delete": "حذف",
  "copySuccess": "برگه در حافظه کپی شد!",
  "bookedDateLabel": "تاریخ ثبت:",
  "deliveryDatePrefix": "تاریخ تحویل:",
  "tailorStamp": "مهر استاد خیاط",
  "customerDetailsHeading": "مشخصات مشتری",
  "measurementsHeading": "جزئیات اندازه‌ها",
  "accountSummaryHeading": "خلاصه مالی و حساب",
  "menuTitle": "منوی استاد آزاد",
  "profileSettings": "پروفایل و تنظیمات",
  "changeLanguage": "تغییر زبان",
  "dataBackup": "پشتیبان‌گیری ابری و همگام‌سازی",
  "helpSupport": "راهنمای استفاده و پشتیبانی",
  "developerInfo": "اطلاعات توسعه‌دهنده",
  "settingsTitle": "پروفایل و تنظیمات برنامه",
  "selectAppLanguage": "زبان برنامه",
  "allSupportedLanguages": "همه ۲۲ زبان پشتیبانی شده:",
  "aiVoiceAssistant": "دستیار صوتی هوشمند آزاد",
  "aiVoiceAssistantSub": "اندازه‌ها را بگویید یا بنویسید برای محاسبه خودکار برش",
  "appGuide": "راهنمای استفاده",
  "appGuideSub": "ثبت اندازه‌ها، اسکن تصویر، پیگیری و واتساپ",
  "cloudAutoSave": "ذخیره ابری خودکار (Firebase Cloud)",
  "cloudAutoSaveLive": "فعال و ایمن",
  "cloudDatabaseLabel": "پایگاه داده ابری:",
  "cloudRecordsLabel": "سوابق ابری:",
  "lastSyncedLabel": "آخرین همگام‌سازی:",
  "syncAllNow": "همگام‌سازی فوری تمام داده‌ها در ابر",
  "syncingToCloud": "در حال ذخیره در فضای ابری...",
  "dataBackupRestore": "پشتیبان‌گیری و بازیابی اطلاعات",
  "recordsCount": "رکورد",
  "backupData": "ایجاد فایل پشتیبان (JSON)",
  "restoreData": "بازیابی داده‌ها (JSON)",
  "developerCredit": "توسعه‌دهنده: نصیب سئو (پیر بخش)",
  "copyrightNotice": "تمامی حقوق محفوظ است © ۲۰۲۶ استاد آزاد",
  "resetAllRecords": "پاک کردن تمام برگه‌های برش",
  "resetRecordsConfirm": "آیا از حذف تمام سوابق مشتریان اطمینان دارید؟",
  "savedSuccess": "با موفقیت ذخیره شد!",
  "cloudSyncSuccess": "رکوردها با موفقیت در فضای ابری ذخیره شدند!",
  "noRecordsToBackup": "هیچ رکوردی برای پشتیبان‌گیری وجود ندارد!",
  "backupFileDownloaded": "فایل پشتیبان با موفقیت دانلود شد!",
  "recordsRestoredSuccess": "سوابق با موفقیت بازیابی شدند!",
  "noValidRecordsFound": "هیچ رکورد معتبری در فایل یافت نشد.",
  "invalidBackupFile": "فایل پشتیبان نامعتبر است. لطفاً فایل صحیح JSON را انتخاب کنید.",
  "needHelpTitle": "نیاز به راهنمایی دارید؟ / پشتیبانی",
  "contactWhatsApp": "تماس در واتساپ",
  "contactEmail": "پشتیبانی ایمیل",
  "appGuideTitle": "راهنمای استفاده از استاد آزاد",
  "guideStep1Title": "۱. ثبت اندازه جدید",
  "guideStep1Desc": "روی دکمه (+) ضربه بزنید و نام، شماره و مقادیر اندازه مشتری را وارد کنید.",
  "guideStep2Title": "۲. ✂️ حالت کاربردی برش",
  "guideStep2Desc": "هنگام کار روی میز برش، حالت برش را فعال کنید تا اعداد بزرگ و خوانا نمایش داده شوند.",
  "guideStep3Title": "۳. اسکن عکس برگه با هوش مصنوعی",
  "guideStep3Desc": "از برگه کاغذی قدیمی عکس بگیرید، هوش مصنوعی سریعاً اندازه‌ها را استخراج می‌کند.",
  "guideStep4Title": "۴. برگه دیجیتال واتساپ و فضای ابری",
  "guideStep4Desc": "با یک کلیک برگه کامل را در واتساپ بفرستید و از ذخیره دائمی در ابر لذت ببرید.",
  "closeGuide": "متوجه شدم / بستن",
  "privacyModalTitle": "سیاست حفظ حریم خصوصی و امنیت داده‌ها",
  "privacyPolicyP1": "اندازه‌ها، مخاطبین و اطلاعات مالی مشتریان شما در حساب ابری اختصاصی و امن نگهداری می‌شوند.",
  "privacyPolicyP2": "هیچ شخص ثالثی به اطلاعات خیاطی شما دسترسی ندارد. تمام اطلاعات رمزگذاری شده است.",
  "closePrivacy": "تأیید و بستن",
  "secureStorage100": "۱۰۰٪ فضای ابری امن و خصوصی",
  "safeBadge": "امن و مطمئن",
  "chatbotHeaderTitle": "دستیار استاد آزاد",
  "chatbotHeaderSub": "دستیار آنلاین خیاطی و برش",
  "voiceReplyActive": "پاسخ صوتی فعال",
  "voiceReplyMuted": "پاسخ صوتی بی‌صدا",
  "typingInputPlaceholder": "اندازه‌ها را بنویسید یا سوال خیاطی بپرسید...",
  "detectedMeasurementsHeading": "اندازه‌های تشخیص داده شده",
  "confirmAndApplySlip": "تأیید و اعمال در برگه",
  "confirmedMeasurement": "تأیید شد",
  "micListeningState": "در حال شنیدن... بفرمایید",
  "micStartState": "صحبت کنید",
  "voiceScreenTitle": "دستیار صوتی آزاد",
  "voiceScreenSub": "گفتگوی صوتی زنده",
  "tapToSpeak": "برای صحبت ضربه بزنید",
  "listeningVoice": "در حال گوش دادن...",
  "processingVoice": "در حال پردازش...",
  "botSpeaking": "در حال خواندن پاسخ...",
  "closeVoiceMode": "خروج از حالت صوتی",
  "browserNoVoice": "تشخیص صدا در این مرورگر پشتیبانی نمی‌شود.",
  "chatbotGreeting": "سلام! من دستیار استاد آزاد هستم. می‌توانید اندازه‌ها را بگویید یا بنویسید (قد، سرشانه، آستین، سینه، کمر، دامن، یقه، شلوار، دمپا). من آن‌ها را مرتب کرده و در برگه ثبت می‌کنم.",
  "quickPrompt1": "قد ۴۲، سرشانه ۱۸.۵، آستین ۲۳، سینه ۳۸، دامن ۲۴، یقه ۱۵.۵، شلوار ۳۸",
  "quickPrompt2": "برای یک دست لباس مردانه چقدر پارچه نیاز است؟",
  "quickPrompt3": "فرمول دقیق برش سرشانه و حلقه آستین چیست؟",
  "quickPrompt4": "چگونه گودی یقه را به طور دقیق برش دهیم؟",
  "login": "ورود",
  "codePlaceholder": "شماره واتساپ یا کد را وارد کنید...",
  "pinHint": "پین پیش‌فرض: 123456 (یا خالی بگذارید)",
  "signingIn": "در حال ورود...",
  "signInWithGoogle": "ورود ایمن با حساب Google",
  "openInNewTab": "باز کردن در تب جدید",
  "tryRedirectLogin": "امتحان ورود با تغییر مسیر",
  "openInNewWindow": "ورود مستقیم در پنجره جدید",
  "secureRecords": "سوابق ۱۰۰٪ امن و خصوصی",
  "loginPrivacyNotice": "هر استاد خیاط با حساب گوگل خود وارد می‌شود و سوابق مشتریان کاملاً اختصاصی می‌ماند.",
  "currentDomainLabel": "دامنه فعلی (Firebase Authorized Domains):",
  "copyDomainBtn": "کپی دامنه",
  "copiedDomainMsg": "کپی شد!",
  "authorizedDomainTip": "این دامنه را در پنل فایربیس در مسیر Authentication > Settings > Authorized Domains اضافه کنید.",
  "deleteConfirm": "آیا از حذف این برگه اطمینان دارید؟",
  "deleteSuccess": "برگه مشتری با موفقیت حذف شد.",
  "saveSuccess": "برگه مشتری با موفقیت ذخیره شد.",
  "syncSuccess": "تمام رکوردها با موفقیت در ابر ذخیره شدند."
}

# PASHTO (ps)
ps = {
  "title": "آزاد ماسټر",
  "subtitle": "د خیاطۍ خوندي حساب او کټنګ ډیجیټل راجستر",
  "appSubtitle": "د مسلکي درزي ډیجیټل کلاوډ راجستر",
  "defaultMasterTitle": "استاد صاحب",
  "masterNameLabel": "د استاد نوم:",
  "masterPhotoLabel": "د استاد انځور:",
  "masterDefaultName": "استاد صاحب",
  "navHome": "کور",
  "navSettings": "ترتیبات",
  "navAdd": "اندازه ولیکئ",
  "searchPlaceholder": "د پیرودونکي نوم یا شمیره ولټوئ...",
  "searchAction": "لټون",
  "clear": "پاکول",
  "recentSearches": "وروستي لټونونه",
  "clearHistory": "تاریخچه پاکه کړئ",
  "openSlip": "پاڼه پرانیزئ",
  "addMeasurementBtn": "اندازه ولیکئ",
  "photoOcrBtn": "د پرچې / ټوکر انځور",
  "cuttingMode": "✂️ کټنګ موډ",
  "normalMode": "عادي حالت",
  "voiceInput": "په غږ سره ثبت",
  "chatbot": "د آزاد ماسټر مرستیال",
  "assistant": "مرستیال",
  "settings": "ترتیبات او پروفایل",
  "privacy": "د محرمیت تګلاره",
  "logout": "وتل",
  "customerSlipsHeading": "د پیرودونکو د کټنګ پاڼې:",
  "statusFiltersHeading": "د آرډر حالت فلټرونه:",
  "showingCount": "ښودل شوي:",
  "allFilter": "ټول",
  "statusPending": "تر کار لاندې",
  "statusCutting": "کټنګ",
  "statusStitching": "ګنډل روان دي",
  "statusReady": "تیار دی",
  "statusDelivered": "سپارل شوی",
  "todayDelivery": "د نن ورځې سپارل:",
  "lateOrders": "ځنډیدلي آرډرونه:",
  "totalCustomers": "ټول پیرودونکي",
  "quickStats": "لنډیز",
  "recentOrders": "وروستي آرډرونه (ګړندۍ لید)",
  "recentOrdersCount": "خورا نوي",
  "show": "ښودل",
  "hide": "پټول",
  "noRecords": "هیڅ ریکارډ ونه موندل شو.",
  "noCustomerFound": "هیڅ پیرودونکی ونه موندل شو",
  "noCustomersSaved": "تر اوسه هیڅ پیرودونکی ندی خوندي شوی",
  "searchHintEmpty": "په بل نوم یا تلیفون شمیره لټون وکړئ.",
  "addFirstCustomerHint": "د لومړۍ اندازې زیاتولو لپاره لاندې تڼۍ کیکاږئ.",
  "addFirstCustomer": "لومړی پیرودونکی ثبت کړئ",
  "tapToAdd": "د نوې اندازې ثبتولو لپاره لاندې (+) تڼۍ کیکاږئ.",
  "tapToAddCustomer": "د نوي پیرودونکي زیاتولو لپاره دلته کلیک وکړئ.",
  "addAsNewCustomer": "د نوي پیرودونکي په توګه",
  "unnamedCustomer": "بې نومه پیرودونکی",
  "date": "نیټه:",
  "delivery": "سپارل:",
  "balance": "پاتې:",
  "cleared": "پوره تادیه",
  "syncing": "همغږي کیږي...",
  "cloudSynced": "په کلاوډ کې خوندي",
  "syncNow": "اوس همغږي کړئ",
  "cloudSyncError": "د کلاوډ ستونزه",
  "online": "آنلاین",
  "selectPhotoSource": "د پرچې یا ټوکر عکس وټاکئ",
  "camera": "کیمره",
  "gallery": "ګالري",
  "fillManually": "خپله فورمه ډکه کړئ",
  "uploadPhotoTitle": "د کاغذي پرچې عکس:",
  "galleryBtn": "🖼️ ګالري",
  "cameraBtn": "📸 کیمره",
  "removePhoto": "انځور لیرې کړئ",
  "extractingOcr": "له انځور څخه اندازې لوستل کیږي...",
  "addSlip": "نوې اندازه ثبت کړئ",
  "editSlip": "اندازه کې بدلون",
  "customerName": "د پیرودونکي نوم *",
  "phoneNumber": "د واټساپ شمیره (اختیاري)",
  "countryCodeLabel": "د هیواد کوډ",
  "suitTypeLabel": "د کالیو ډول",
  "suitGents": "د سړیو جامې (پرتوګ او کمیس)",
  "suitKurtaPajama": "کرتا پاجامه",
  "suitSafari": "سفاري سوټ",
  "suitWaistcoat": "واسکت",
  "suitSherwani": "شیرواني",
  "deliveryDateLabel": "د بیرته ورکولو نیټه",
  "quickToday": "نن",
  "quickTomorrow": "سبا",
  "quick3Days": "۳ ورځې",
  "quick1Week": "۱ اونۍ",
  "quick10Days": "۱۰ ورځې",
  "orderStatusLabel": "د آرډر حالت:",
  "orderLockedNotice": "دا آرډر بشپړ او قفل دی. ایا تاسو غواړئ قفل خلاص کړئ او حالت بدل کړئ؟",
  "orderLockedBadge": "🔒 قفل شوی",
  "orderUnlockedBadge": "🔓 خلاص شوی",
  "dueTodayBadge": "⚡ نن ورځ سپارل",
  "lateOrderBadge": "⚠️ ناوخته شوی",
  "upcomingBadge": "📅 راتلونکی",
  "lengthLabel": "اوږدوالی",
  "shoulderLabel": "اوږه / تیره",
  "sleevesLabel": "لستوڼي",
  "chestLabel": "سینه",
  "waistLabel": "ملا / چیل",
  "daamanLabel": "لمن / ګیره",
  "collarLabel": "کالر / بین",
  "shalwarLabel": "پرتوګ / شلوار",
  "panchaLabel": "پنچه",
  "pocketLabel": "جیب",
  "specialNotesLabel": "ځانګړي یادښتونه او لارښوونې",
  "notesPlaceholder": "لکه ګرد لمن، بین کالر، یو ګنډل...",
  "billingHeading": "د ګنډلو حساب او بل:",
  "totalAmountLabel": "ټوله پیسې",
  "advanceAmountLabel": "مخکې ترلاسه شوې (بیعانه)",
  "balanceAmountLabel": "پاتې پیسې",
  "fullyPaidBadge": "✓ پوره ورکړل شوې",
  "balanceDueBadge": "⏳ پاتې پیسې",
  "saveDone": "خوندي او بشپړ",
  "saveClose": "خوندي او بند کړئ",
  "cancel": "لغوه کول",
  "close": "وشو / وتل",
  "back": "شاته",
  "digitalSlip": "ډیجیټل کټنګ پاڼه",
  "editMode": "سمون / کټنګ موډ",
  "sendWhatsapp": "په واټساپ کې پاڼه واستوئ",
  "copySlip": "پاڼه کاپي کړئ",
  "printSlip": "چاپ کړئ",
  "delete": "حذف کړئ",
  "copySuccess": "پاڼه کاپي شوه!",
  "bookedDateLabel": "ثبت نیټه:",
  "deliveryDatePrefix": "د سپارلو نیټه:",
  "tailorStamp": "د استاد ټاپه",
  "customerDetailsHeading": "د پیرودونکي معلومات",
  "measurementsHeading": "د اندازو تفصیل",
  "accountSummaryHeading": "د حساب لنډیز",
  "menuTitle": "د آزاد ماسټر مینو",
  "profileSettings": "پروفایل او ترتیبات",
  "changeLanguage": "ژبه بدله کړئ",
  "dataBackup": "کلاوډ بیک اپ او همغږي",
  "helpSupport": "لارښود او مرسته",
  "developerInfo": "د جوړونکي معلومات",
  "settingsTitle": "پروفایل او ترتیبات",
  "selectAppLanguage": "د پروګرام ژبه",
  "allSupportedLanguages": "ټولې ۲۲ ژبې:",
  "aiVoiceAssistant": "د آزاد ماسټر غږیز مرستیال",
  "aiVoiceAssistantSub": "اندازې ووایاست یا ولیکئ د اتومات محاسبې لپاره",
  "appGuide": "د کارولو لارښود",
  "appGuideSub": "اندازه لیکل، انځور لوستل، ټریکنګ او واټساپ",
  "cloudAutoSave": "کلاوډ اوتومات ساتنه (Firebase Cloud)",
  "cloudAutoSaveLive": "فعال او خوندي",
  "cloudDatabaseLabel": "کلاوډ ډیټابیس:",
  "cloudRecordsLabel": "کلاوډ ریکارډونه:",
  "lastSyncedLabel": "وروستی سنک:",
  "syncAllNow": "ټول معلومات اوس کلاوډ ته واستوئ",
  "syncingToCloud": "په کلاوډ کې ثبت کیږي...",
  "dataBackupRestore": "د معلوماتو بیک اپ او بیا رغونه",
  "recordsCount": "ریکارډونه",
  "backupData": "بیک اپ جوړ کړئ (JSON)",
  "restoreData": "معلومات بیرته راولئ (JSON)",
  "developerCredit": "جوړونکی: نصیب سئو (پیر بخش)",
  "copyrightNotice": "ټول حقوق خوندي دي © ۲۰۲۶ آزاد ماسټر",
  "resetAllRecords": "د اندازو ټولې پاڼې پاکې کړئ",
  "resetRecordsConfirm": "ایا تاسو ډاډه یاست چې ټول ریکارډونه پاک کړئ؟",
  "savedSuccess": "خوندي شو!",
  "cloudSyncSuccess": "ریکارډونه په بریالیتوب سره کلاوډ ته واستول شول!",
  "noRecordsToBackup": "د بیک اپ لپاره هیڅ ریکارډ نشته!",
  "backupFileDownloaded": "بیک اپ فایل ډانلوډ شو!",
  "recordsRestoredSuccess": "ریکارډونه په بریالیتوب سره بیرته راغلل!",
  "noValidRecordsFound": "په فایل کې هیڅ سم ریکارډ ونه موندل شو.",
  "invalidBackupFile": "ناسم فایل دی. مهرباني وکړئ سم JSON فایل وټاکئ.",
  "needHelpTitle": "مرستې ته اړتیا لرئ؟ / ملاتړ",
  "contactWhatsApp": "په واټساپ اړیکه ونیسئ",
  "contactEmail": "بریښنالیک ملاتړ",
  "appGuideTitle": "د آزاد ماسټر کارولو لارښود",
  "guideStep1Title": "۱. د نوې اندازې ثبتول",
  "guideStep1Desc": "د (+) تڼۍ کیکاږئ او د پیرودونکي نوم، شمیره او اندازې ولیکئ.",
  "guideStep2Title": "۲. ✂️ د کټنګ موډ ښیګڼه",
  "guideStep2Desc": "د کټنګ په میز د کټنګ موډ چالان کړئ ترڅو شمیرې لویې او له لرې ښکاره شي.",
  "guideStep3Title": "۳. د پرچې انځور او اتومات لوستل",
  "guideStep3Desc": "د کاغذي پرچې عکس واخلئ، هوښیار مرستیال به پخپله اندازې فورمه کې ځای په ځای کړي.",
  "guideStep4Title": "۴. ډیجیټل واټساپ پاڼه او کلاوډ",
  "guideStep4Desc": "په یوه کلیک سره پیرودونکي ته په واټساپ پاڼه واستوئ او هرڅه په کلاوډ کې خوندي وساتئ.",
  "closeGuide": "پوه شوم / بند کړئ",
  "privacyModalTitle": "د محرمیت تګلاره او د معلوماتو خوندیتوب",
  "privacyPolicyP1": "ستاسو د ټولو پیرودونکو اندازې او حسابونه ستاسو په شخصي کلاوډ اکاونټ کې خوندي دي.",
  "privacyPolicyP2": "هیڅ بهرنی کس نشي کولی ستاسو د درزۍ ریکارډونه وګوري. ټول معلومات پټ او کوډ شوي دي.",
  "closePrivacy": "سمه ده، پوه شوم",
  "secureStorage100": "۱۰۰٪ خوندي کلاوډ ذخیره",
  "safeBadge": "خوندي او مطمئن",
  "chatbotHeaderTitle": "د آزاد ماسټر مرستیال",
  "chatbotHeaderSub": "آنلاین د ګنډلو او کټنګ مرستیال",
  "voiceReplyActive": "غږیز ځواب فعال دی",
  "voiceReplyMuted": "غږ خاموش دی",
  "typingInputPlaceholder": "اندازه ولیکئ یا د کټنګ پوښتنه وکړئ...",
  "detectedMeasurementsHeading": "پیژندل شوې اندازې",
  "confirmAndApplySlip": "تایید او په پاڼه کې ولګوئ",
  "confirmedMeasurement": "تایید شو",
  "micListeningState": "اورم... ووایاست",
  "micStartState": "خبرې وکړئ",
  "voiceScreenTitle": "د آزاد غږیز مرستیال",
  "voiceScreenSub": "ژوندۍ غږیزه خبرې اترې",
  "tapToSpeak": "د خبرو لپاره کیکاږئ",
  "listeningVoice": "اورم...",
  "processingVoice": "پروسس کیږي...",
  "botSpeaking": "ځواب وایی...",
  "closeVoiceMode": "غږیز حالت بند کړئ",
  "browserNoVoice": "دا براوزر د غږ پیژندلو ملاتړ نه کوي.",
  "chatbotGreeting": "سلام! زه د آزاد ماسټر مرستیال یم. تاسو کولی شئ اندازې په غږ یا لیکلو ووایاست (اوږدوالی، اوږه، لستوڼي، سینه، ملا، لمن، کالر، پرتوګ، پنچه). زه به یې تنظیم او په پاڼه کې درج کړم.",
  "quickPrompt1": "اوږدوالی ۴۲، اوږه ۱۸.۵، لستوڼي ۲۳، سینه ۳۸، لمن ۲۴، کالر ۱۵.۵، پرتوګ ۳۸",
  "quickPrompt2": "د سړیو د جامو لپاره څومره ټوکر پکار دی؟",
  "quickPrompt3": "د اوږې او تخرګ (موډا) د ایستلو فورمول څه دی؟",
  "quickPrompt4": "د کالر او بین هاله څنګه سمه ووایستل شي؟",
  "login": "ننوتل",
  "codePlaceholder": "د واټساپ شمیره یا کوډ ولیکئ...",
  "pinHint": "ډیفالټ پن: 123456 (یا خالي پریږدئ)",
  "signingIn": "ننوځي...",
  "signInWithGoogle": "د ګوګل اکاونټ سره خوندي ننوتل",
  "openInNewTab": "په نوې پاڼه کې پرانیزئ",
  "tryRedirectLogin": "د ری ډائرکټ ننوتل هڅه وکړئ",
  "openInNewWindow": "نیغ په نیغه په نوې کړکۍ کې پرانیزئ",
  "secureRecords": "۱۰۰٪ خوندي او شخصي ریکارډونه",
  "loginPrivacyNotice": "هر درزي په خپل ګوګل اکاونټ ننوځي او د پیرودونکو ریکارډونه یې په بشپړ ډول پټ پاتې کیږي.",
  "currentDomainLabel": "اوسنی ډومین (Firebase Authorized Domains):",
  "copyDomainBtn": "ډومین کاپي کړئ",
  "copiedDomainMsg": "کاپي شو!",
  "authorizedDomainTip": "دا ډومین په Firebase Console > Authentication > Settings > Authorized Domains کې شامل کړئ.",
  "deleteConfirm": "ایا تاسو واقعیا غواړئ دا پاڼه حذف کړئ؟",
  "deleteSuccess": "پاڼه په بریالیتوب سره حذف شوه.",
  "saveSuccess": "پاڼه په بریالیتوب سره خوندي شوه.",
  "syncSuccess": "ټول ریکارډونه کلاوډ ته واستول شول."
}

print("Part 1: ur, sd, ar, fa, ps ready!")
