#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# PART 3: it, ru, zh, ja, ko, ms, id, pt, th, en

# ITALIAN (it)
it = {
  "title": "AZAD MASTER",
  "subtitle": "Gestione Sartoriale Sicura e Registro Taglio Digitale",
  "appSubtitle": "Registro Cloud Digitale per Sarti Professionisti",
  "defaultMasterTitle": "Maestro Sarto",
  "masterNameLabel": "Nome del Maestro:",
  "masterPhotoLabel": "Foto del Maestro:",
  "masterDefaultName": "Maestro Sarto",
  "navHome": "Home",
  "navSettings": "Impostazioni",
  "navAdd": "Aggiungi Misura",
  "searchPlaceholder": "Cerca per nome o telefono...",
  "searchAction": "Cerca",
  "clear": "Cancella",
  "recentSearches": "Ricerche Recenti",
  "clearHistory": "Cancella Cronologia",
  "openSlip": "Apri Scheda",
  "addMeasurementBtn": "Aggiungi Misura",
  "photoOcrBtn": "Foto Scheda / Tessuto",
  "cuttingMode": "✂️ Modalità Taglio",
  "normalMode": "Modalità Normale",
  "voiceInput": "Inserimento Vocale",
  "chatbot": "Assistente Azad IA",
  "assistant": "Assistente",
  "settings": "Impostazioni e Profilo",
  "privacy": "Informativa sulla Privacy",
  "logout": "Disconnetti",
  "customerSlipsHeading": "Schede Taglio Clienti:",
  "statusFiltersHeading": "Filtri Stato Ordine:",
  "showingCount": "Visualizzati:",
  "allFilter": "Tutti",
  "statusPending": "In Attesa",
  "statusCutting": "In Taglio",
  "statusStitching": "In Cucitura",
  "statusReady": "Pronto",
  "statusDelivered": "Consegnato",
  "todayDelivery": "Consegne di Oggi:",
  "lateOrders": "Ordini in Ritardo:",
  "totalCustomers": "Totale Clienti",
  "quickStats": "Panoramica",
  "recentOrders": "Ordini Recenti (Vista Rapida)",
  "recentOrdersCount": "Più Recenti",
  "show": "Mostra",
  "hide": "Nascondi",
  "noRecords": "Nessun record trovato.",
  "noCustomerFound": "Nessun cliente trovato",
  "noCustomersSaved": "Nessun cliente ancora salvato",
  "searchHintEmpty": "Prova a cercare con un altro nome o numero.",
  "addFirstCustomerHint": "Tocca il pulsante qui sotto per aggiungere la tua prima scheda.",
  "addFirstCustomer": "Aggiungi Primo Cliente",
  "tapToAdd": "Tocca il pulsante (+) in basso per inserire una nuova scheda.",
  "tapToAddCustomer": "Tocca qui per aggiungere un nuovo cliente.",
  "addAsNewCustomer": "come Nuovo Cliente",
  "unnamedCustomer": "Cliente Senza Nome",
  "date": "Data:",
  "delivery": "Consegna:",
  "balance": "Saldo:",
  "cleared": "Saldato",
  "syncing": "Sincronizzazione...",
  "cloudSynced": "Salvato sul Cloud",
  "syncNow": "Sincronizza Ora",
  "cloudSyncError": "Errore Cloud",
  "online": "Online",
  "selectPhotoSource": "Scegli Foto Scheda o Tessuto",
  "camera": "Fotocamera",
  "gallery": "Galleria",
  "fillManually": "Compila Manualmente",
  "uploadPhotoTitle": "Foto Scheda Cartacea:",
  "galleryBtn": "🖼️ Galleria",
  "cameraBtn": "📸 Fotocamera",
  "removePhoto": "Rimuovi Foto",
  "extractingOcr": "Riconoscimento misure tramite IA...",
  "addSlip": "Nuova Scheda Misura",
  "editSlip": "Modifica Scheda Misura",
  "customerName": "Nome del Cliente *",
  "phoneNumber": "Numero WhatsApp (Opzionale)",
  "countryCodeLabel": "Prefisso Paese",
  "suitTypeLabel": "Tipo di Abito",
  "suitGents": "Abito Uomo (Camicia e Pantalone)",
  "suitKurtaPajama": "Kurta e Pigiama",
  "suitSafari": "Abito Safari",
  "suitWaistcoat": "Gilet",
  "suitSherwani": "Sherwani da Cerimonia",
  "deliveryDateLabel": "Data di Consegna",
  "quickToday": "Oggi",
  "quickTomorrow": "Domani",
  "quick3Days": "3 Giorni",
  "quick1Week": "1 Settimana",
  "quick10Days": "10 Giorni",
  "orderStatusLabel": "Stato Ordine:",
  "orderLockedNotice": "Questo ordine è contrassegnato come Consegnato ed è bloccato. Vuoi sbloccarlo per modificare lo stato?",
  "orderLockedBadge": "🔒 Bloccato",
  "orderUnlockedBadge": "🔓 Sbloccato",
  "dueTodayBadge": "⚡ Consegna Oggi",
  "lateOrderBadge": "⚠️ In Ritardo",
  "upcomingBadge": "📅 Prossimo",
  "lengthLabel": "Lunghezza",
  "shoulderLabel": "Spalle",
  "sleevesLabel": "Manica",
  "chestLabel": "Torace / Seno",
  "waistLabel": "Vita",
  "daamanLabel": "Fondo / Giro",
  "collarLabel": "Collo",
  "shalwarLabel": "Pantalone",
  "panchaLabel": "Fondo Pantalone",
  "pocketLabel": "Tasca",
  "specialNotesLabel": "Note e Istruzioni Speciali",
  "notesPlaceholder": "Es: Fondo tondo, collo alla coreana, cucitura singola...",
  "billingHeading": "Conto e Fatturazione:",
  "totalAmountLabel": "Importo Totale",
  "advanceAmountLabel": "Acconto Versato",
  "balanceAmountLabel": "Saldo Residuo",
  "fullyPaidBadge": "✓ Saldato Interamente",
  "balanceDueBadge": "⏳ Saldo Pendente",
  "saveDone": "Salva e Completa",
  "saveClose": "Salva e Chiudi",
  "cancel": "Annulla",
  "close": "Fatto / Chiudi",
  "back": "Indietro",
  "digitalSlip": "Scheda Taglio Digitale",
  "editMode": "Modifica / Modalità Taglio",
  "sendWhatsapp": "Invia Scheda su WhatsApp",
  "copySlip": "Copia Scheda",
  "printSlip": "Stampa",
  "delete": "Elimina",
  "copySuccess": "Scheda copiata negli appunti!",
  "bookedDateLabel": "Data Ordine:",
  "deliveryDatePrefix": "Data Consegna:",
  "tailorStamp": "Timbro Maestro Sarto",
  "customerDetailsHeading": "Dati Cliente",
  "measurementsHeading": "Dettaglio Misure",
  "accountSummaryHeading": "Riepilogo Conto",
  "menuTitle": "Menu Azad Master",
  "profileSettings": "Profilo e Impostazioni",
  "changeLanguage": "Cambia Lingua",
  "dataBackup": "Backup Cloud e Sincronizzazione",
  "helpSupport": "Guida all'uso e Assistenza",
  "developerInfo": "Info Sviluppatore",
  "settingsTitle": "Profilo e Impostazioni App",
  "selectAppLanguage": "Lingua dell'App",
  "allSupportedLanguages": "Tutte le 22 Lingue Supportate:",
  "aiVoiceAssistant": "Assistente Vocale Azad IA",
  "aiVoiceAssistantSub": "Pronuncia o digita le misure per il calcolo automatico del taglio",
  "appGuide": "Guida all'Uso",
  "appGuideSub": "Inserimento misure, scansione OCR, monitoraggio e WhatsApp",
  "cloudAutoSave": "Salvataggio Automatico Cloud (Firebase)",
  "cloudAutoSaveLive": "Attivo e Sicuro",
  "cloudDatabaseLabel": "Database Cloud:",
  "cloudRecordsLabel": "Record Cloud:",
  "lastSyncedLabel": "Ultima Sincronizzazione:",
  "syncAllNow": "Sincronizza Tutti i Dati sul Cloud",
  "syncingToCloud": "Sincronizzazione in corso sul Cloud...",
  "dataBackupRestore": "Backup e Ripristino Dati",
  "recordsCount": "Record",
  "backupData": "Crea Backup (JSON)",
  "restoreData": "Ripristina Dati (JSON)",
  "developerCredit": "Sviluppato da: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "Tutti i diritti riservati © 2026 Azad Master",
  "resetAllRecords": "Cancella Tutte le Schede",
  "resetRecordsConfirm": "Sei sicuro di voler eliminare tutti i dati dei clienti?",
  "savedSuccess": "Salvato con successo!",
  "cloudSyncSuccess": "Schede sincronizzate con successo sul Cloud!",
  "noRecordsToBackup": "Nessun record da salvare nel backup!",
  "backupFileDownloaded": "File di backup scaricato con successo!",
  "recordsRestoredSuccess": "Schede ripristinate con successo!",
  "noValidRecordsFound": "Nessun record valido trovato nel file.",
  "invalidBackupFile": "File non valido. Seleziona un file JSON corretto.",
  "needHelpTitle": "Hai bisogno di aiuto? / Supporto",
  "contactWhatsApp": "Contatta su WhatsApp",
  "contactEmail": "Assistenza Email",
  "appGuideTitle": "Come Usare Azad Master",
  "guideStep1Title": "1. Inserimento Nuova Misura",
  "guideStep1Desc": "Tocca il pulsante (+) o 'Aggiungi Misura' per inserire anagrafica, misure e data di consegna.",
  "guideStep2Title": "2. ✂️ Il Vantaggio della Modalità Taglio",
  "guideStep2Desc": "Attiva la Modalità Taglio al tavolo da lavoro per ingrandire i numeri e leggerli da lontano.",
  "guideStep3Title": "3. Foto della Scheda e Scansione IA",
  "guideStep3Desc": "Scatta una foto della scheda cartacea tradizionale; l'IA riempirà le misure automaticamente.",
  "guideStep4Title": "4. Scheda Digitale WhatsApp e Cloud",
  "guideStep4Desc": "Invia con un tocco la scheda su WhatsApp e mantieni tutto al sicuro sul Cloud.",
  "closeGuide": "Ho Capito / Chiudi",
  "privacyModalTitle": "Privacy e Protezione dei Dati",
  "privacyPolicyP1": "Tutte le misure, contatti e dati finanziari sono memorizzati in modo cifrato sul tuo account Cloud.",
  "privacyPolicyP2": "Nessun terzo può accedere ai tuoi dati di sartoria. Tutto è privato e protetto.",
  "closePrivacy": "Accetta e Chiudi",
  "secureStorage100": "Archiviazione Cloud Sicura al 100%",
  "safeBadge": "Sicuro",
  "chatbotHeaderTitle": "Assistente Azad IA",
  "chatbotHeaderSub": "Assistente Virtuale per Taglio e Sartoria",
  "voiceReplyActive": "Risposta Vocale Attiva",
  "voiceReplyMuted": "Risposta Vocale Disattivata",
  "typingInputPlaceholder": "Digita misure o fai una domanda di sartoria...",
  "detectedMeasurementsHeading": "Misure Rilevate",
  "confirmAndApplySlip": "Conferma e Applica alla Scheda",
  "confirmedMeasurement": "Confermato",
  "micListeningState": "In ascolto... Parla ora",
  "micStartState": "Parla",
  "voiceScreenTitle": "Assistente Vocale Azad",
  "voiceScreenSub": "Conversazione Vocale dal Vivo",
  "tapToSpeak": "Tocca per Parlare",
  "listeningVoice": "Ascolto in corso...",
  "processingVoice": "Elaborazione in corso...",
  "botSpeaking": "Riproduzione vocale della risposta...",
  "closeVoiceMode": "Esci dalla Modalità Voce",
  "browserNoVoice": "Riconoscimento vocale non supportato da questo browser.",
  "chatbotGreeting": "Ciao! Sono l'assistente Azad Master. Puoi dettare o digitare le misure (Lunghezza, Spalle, Manica, Torace, Vita, Fondo, Collo, Pantalone). Le organizzerò per te.",
  "quickPrompt1": "Lunghezza 42, Spalle 18.5, Manica 23, Torace 38, Fondo 24, Collo 15.5, Pantalone 38",
  "quickPrompt2": "Quanto tessuto serve per un completo da uomo?",
  "quickPrompt3": "Qual è la formula per scalfo manica e pendenza spalla?",
  "quickPrompt4": "Come tagliare la curva del collo con precisione?",
  "login": "Accedi",
  "codePlaceholder": "Inserisci WhatsApp o Codice...",
  "pinHint": "PIN predefinito: 123456 (oppure lascia vuoto)",
  "signingIn": "Accesso in corso...",
  "signInWithGoogle": "Accesso Sicuro con Google",
  "openInNewTab": "Apri in Nuova Scheda",
  "tryRedirectLogin": "Prova Accesso con Reindirizzamento",
  "openInNewWindow": "Apri direttamente in nuova finestra",
  "secureRecords": "Record 100% Sicuri e Riservati",
  "loginPrivacyNotice": "Ogni sarto accede con il proprio account Google personale e i dati restano rigorosamente riservati.",
  "currentDomainLabel": "Dominio Attuale (Firebase Authorized Domains):",
  "copyDomainBtn": "Copia Dominio",
  "copiedDomainMsg": "Copiato!",
  "authorizedDomainTip": "Aggiungi questo dominio in Firebase Console > Authentication > Settings > Authorized Domains.",
  "deleteConfirm": "Sei sicuro di voler eliminare questa scheda?",
  "deleteSuccess": "Scheda cliente eliminata con successo.",
  "saveSuccess": "Scheda cliente salvata con successo.",
  "syncSuccess": "Tutti i dati sincronizzati sul Cloud."
}

# RUSSIAN (ru)
ru = {
  "title": "АЗАД МАСТЕР",
  "subtitle": "Безопасный учет заказов и цифровой журнал закройщика",
  "appSubtitle": "Профессиональный цифровой облачный журнал портного",
  "defaultMasterTitle": "Мастер-портной",
  "masterNameLabel": "Имя мастера:",
  "masterPhotoLabel": "Фото мастера:",
  "masterDefaultName": "Мастер-портной",
  "navHome": "Главная",
  "navSettings": "Настройки",
  "navAdd": "Добавить мерку",
  "searchPlaceholder": "Поиск по имени или телефону...",
  "searchAction": "Поиск",
  "clear": "Очистить",
  "recentSearches": "Недавние поиски",
  "clearHistory": "Очистить историю",
  "openSlip": "Открыть карточку",
  "addMeasurementBtn": "Добавить мерку",
  "photoOcrBtn": "Фото бланка / ткани",
  "cuttingMode": "✂️ Режим раскроя",
  "normalMode": "Обычный режим",
  "voiceInput": "Голосовой ввод",
  "chatbot": "Ассистент Азад ИИ",
  "assistant": "Ассистент",
  "settings": "Настройки и профиль",
  "privacy": "Политика конфиденциальности",
  "logout": "Выйти",
  "customerSlipsHeading": "Карточки мерок клиентов:",
  "statusFiltersHeading": "Фильтры по статусу:",
  "showingCount": "Показано:",
  "allFilter": "Все",
  "statusPending": "В ожидании",
  "statusCutting": "Раскрой",
  "statusStitching": "Пошив",
  "statusReady": "Готово к выдаче",
  "statusDelivered": "Выдано",
  "todayDelivery": "Выдача сегодня:",
  "lateOrders": "Просроченные заказы:",
  "totalCustomers": "Всего клиентов",
  "quickStats": "Обзор",
  "recentOrders": "Недавние заказы (быстрый просмотр)",
  "recentOrdersCount": "Новейшие",
  "show": "Показать",
  "hide": "Скрыть",
  "noRecords": "Записей не найдено.",
  "noCustomerFound": "Клиент не найден",
  "noCustomersSaved": "Клиентов пока не добавлено",
  "searchHintEmpty": "Попробуйте поискать по другому имени или номеру.",
  "addFirstCustomerHint": "Нажмите кнопку ниже, чтобы добавить первую карточку мерки.",
  "addFirstCustomer": "Добавить первого клиента",
  "tapToAdd": "Нажмите (+) внизу, чтобы внести новые мерки.",
  "tapToAddCustomer": "Нажмите здесь, чтобы добавить клиента.",
  "addAsNewCustomer": "как нового клиента",
  "unnamedCustomer": "Клиент без имени",
  "date": "Дата:",
  "delivery": "Выдача:",
  "balance": "Остаток:",
  "cleared": "Оплачено",
  "syncing": "Синхронизация...",
  "cloudSynced": "Сохранено в облаке",
  "syncNow": "Синхронизировать сейчас",
  "cloudSyncError": "Ошибка облака",
  "online": "В сети",
  "selectPhotoSource": "Выберите фото бланка или ткани",
  "camera": "Камера",
  "gallery": "Галерея",
  "fillManually": "Заполнить вручную",
  "uploadPhotoTitle": "Фото бумажного бланка:",
  "galleryBtn": "🖼️ Галерея",
  "cameraBtn": "📸 Камера",
  "removePhoto": "Удалить фото",
  "extractingOcr": "Распознавание мерок искусственным интеллектом...",
  "addSlip": "Новая карточка мерки",
  "editSlip": "Редактировать карточку",
  "customerName": "Имя клиента *",
  "phoneNumber": "WhatsApp (необязательно)",
  "countryCodeLabel": "Код страны",
  "suitTypeLabel": "Тип одежды",
  "suitGents": "Мужской костюм (рубашка и брюки)",
  "suitKurtaPajama": "Курта и пижама",
  "suitSafari": "Костюм Сафари",
  "suitWaistcoat": "Жилет",
  "suitSherwani": "Праздничный Шервани",
  "deliveryDateLabel": "Дата готовности",
  "quickToday": "Сегодня",
  "quickTomorrow": "Завтра",
  "quick3Days": "3 дня",
  "quick1Week": "1 неделя",
  "quick10Days": "10 дней",
  "orderStatusLabel": "Статус заказа:",
  "orderLockedNotice": "Заказ отмечен как Выдан и заблокирован. Разблокировать для смены статуса?",
  "orderLockedBadge": "🔒 Заблокировано",
  "orderUnlockedBadge": "🔓 Разблокировано",
  "dueTodayBadge": "⚡ Выдача сегодня",
  "lateOrderBadge": "⚠️ Просрочен",
  "upcomingBadge": "📅 Скоро",
  "lengthLabel": "Длина изделия",
  "shoulderLabel": "Ширина плеч",
  "sleevesLabel": "Длина рукава",
  "chestLabel": "Обхват груди",
  "waistLabel": "Обхват талии",
  "daamanLabel": "Ширина низа",
  "collarLabel": "Воротник",
  "shalwarLabel": "Длина брюк",
  "panchaLabel": "Ширина штанины",
  "pocketLabel": "Карман",
  "specialNotesLabel": "Особые указания",
  "notesPlaceholder": "Напр: круглый низ, воротник-стойка, одна строчка...",
  "billingHeading": "Стоимость и расчет:",
  "totalAmountLabel": "Итоговая сумма",
  "advanceAmountLabel": "Аванс получен",
  "balanceAmountLabel": "Остаток к оплате",
  "fullyPaidBadge": "✓ Оплачено полностью",
  "balanceDueBadge": "⏳ Остаток долга",
  "saveDone": "Сохранить и завершить",
  "saveClose": "Сохранить и закрыть",
  "cancel": "Отмена",
  "close": "Готово / Закрыть",
  "back": "Назад",
  "digitalSlip": "Цифровая карточка раскроя",
  "editMode": "Правка / Режим раскроя",
  "sendWhatsapp": "Отправить карточку в WhatsApp",
  "copySlip": "Копировать карточку",
  "printSlip": "Печать",
  "delete": "Удалить",
  "copySuccess": "Карточка скопирована в буфер!",
  "bookedDateLabel": "Дата заказа:",
  "deliveryDatePrefix": "Дата выдачи:",
  "tailorStamp": "Печать мастера-портного",
  "customerDetailsHeading": "Данные клиента",
  "measurementsHeading": "Мерки",
  "accountSummaryHeading": "Взаиморасчеты",
  "menuTitle": "Меню Азад Мастер",
  "profileSettings": "Профиль и настройки",
  "changeLanguage": "Сменить язык",
  "dataBackup": "Облачное резервное копирование",
  "helpSupport": "Руководство и помощь",
  "developerInfo": "О разработчике",
  "settingsTitle": "Профиль и настройки приложения",
  "selectAppLanguage": "Язык приложения",
  "allSupportedLanguages": "Все 22 поддерживаемых языка:",
  "aiVoiceAssistant": "Голосовой ИИ-ассистент Азад",
  "aiVoiceAssistantSub": "Диктуйте или пишите мерки для автоматического расчета",
  "appGuide": "Руководство пользователя",
  "appGuideSub": "Ввод мерок, распознавание фото, учет и WhatsApp",
  "cloudAutoSave": "Автосохранение в облако (Firebase)",
  "cloudAutoSaveLive": "Активно и надежно",
  "cloudDatabaseLabel": "База данных:",
  "cloudRecordsLabel": "Записей в облаке:",
  "lastSyncedLabel": "Последняя синхронизация:",
  "syncAllNow": "Синхронизировать все данные с облаком",
  "syncingToCloud": "Синхронизация с облаком...",
  "dataBackupRestore": "Резервное копирование и восстановление",
  "recordsCount": "Записей",
  "backupData": "Создать резервную копию (JSON)",
  "restoreData": "Восстановить данные (JSON)",
  "developerCredit": "Разработчик: Naseeb SEO (Пир Бакхаш)",
  "copyrightNotice": "Все права защищены © 2026 Азад Мастер",
  "resetAllRecords": "Очистить все карточки мерок",
  "resetRecordsConfirm": "Вы действительно хотите удалить все записи клиентов?",
  "savedSuccess": "Успешно сохранено!",
  "cloudSyncSuccess": "Записи успешно синхронизированы с облаком!",
  "noRecordsToBackup": "Нет записей для создания резервной копии!",
  "backupFileDownloaded": "Файл резервной копии успешно скачан!",
  "recordsRestoredSuccess": "Записи успешно восстановлены!",
  "noValidRecordsFound": "В файле не найдено корректных записей.",
  "invalidBackupFile": "Неверный файл. Выберите правильный JSON-файл.",
  "needHelpTitle": "Нужна помощь? / Поддержка",
  "contactWhatsApp": "Связаться в WhatsApp",
  "contactEmail": "Поддержка по почте",
  "appGuideTitle": "Как пользоваться Азад Мастер",
  "guideStep1Title": "1. Добавление новой мерки",
  "guideStep1Desc": "Нажмите (+) или 'Добавить мерку', чтобы ввести данные клиента, размеры и дату.",
  "guideStep2Title": "2. ✂️ Преимущество режима раскроя",
  "guideStep2Desc": "Включите режим раскроя за столом закройщика: цифры станут крупными и четкими.",
  "guideStep3Title": "3. Фото бланка и ИИ-сканирование",
  "guideStep3Desc": "Сфотографируйте бумажный бланк, и ИИ моментально заполнит все поля мерок.",
  "guideStep4Title": "4. Цифровая карточка WhatsApp и облако",
  "guideStep4Desc": "Отправляйте готовую карточку в WhatsApp одним кликом и храните данные в облаке.",
  "closeGuide": "Понятно / Закрыть",
  "privacyModalTitle": "Конфиденциальность и защита данных",
  "privacyPolicyP1": "Все мерки, контакты и расчеты с клиентами зашифрованы и хранятся в вашем личном облаке.",
  "privacyPolicyP2": "Никто из посторонних лиц не имеет доступа к вашей базе заказов.",
  "closePrivacy": "Принять и закрыть",
  "secureStorage100": "100% безопасное облачное хранилище",
  "safeBadge": "Безопасно",
  "chatbotHeaderTitle": "Ассистент Азад ИИ",
  "chatbotHeaderSub": "Онлайн-помощник по крою и шитью",
  "voiceReplyActive": "Голосовой ответ включен",
  "voiceReplyMuted": "Голосовой ответ выключен",
  "typingInputPlaceholder": "Введите мерки или задайте вопрос по пошиву...",
  "detectedMeasurementsHeading": "Распознанные мерки",
  "confirmAndApplySlip": "Подтвердить и внести в карточку",
  "confirmedMeasurement": "Подтверждено",
  "micListeningState": "Слушаю... Говорите",
  "micStartState": "Говорить",
  "voiceScreenTitle": "Голосовой ассистент Азад",
  "voiceScreenSub": "Живой голосовой диалог",
  "tapToSpeak": "Нажмите, чтобы сказать",
  "listeningVoice": "Слушаю...",
  "processingVoice": "Обработка...",
  "botSpeaking": "Озвучивание ответа...",
  "closeVoiceMode": "Выйти из голосового режима",
  "browserNoVoice": "Распознавание речи не поддерживается данным браузером.",
  "chatbotGreeting": "Здравствуйте! Я ассистент Азад Мастер. Вы можете продиктовать или написать мерки (длина, плечи, рукав, грудь, талия, низ, воротник, брюки). Я распределю их по полям.",
  "quickPrompt1": "Длина 42, плечи 18.5, рукав 23, грудь 38, низ 24, воротник 15.5, брюки 38",
  "quickPrompt2": "Сколько ткани требуется на мужской костюм?",
  "quickPrompt3": "Какова формула расчета проймы и наклона плеча?",
  "quickPrompt4": "Как правильно вырезать горловину для воротника?",
  "login": "Войти",
  "codePlaceholder": "Введите номер WhatsApp или код...",
  "pinHint": "PIN по умолчанию: 123456 (или оставьте пустым)",
  "signingIn": "Выполняется вход...",
  "signInWithGoogle": "Безопасный вход через Google",
  "openInNewTab": "Открыть в новой вкладке",
  "tryRedirectLogin": "Попробовать вход через перенаправление",
  "openInNewWindow": "Открыть напрямую в новом окне",
  "secureRecords": "100% безопасные и конфиденциальные данные",
  "loginPrivacyNotice": "Каждый мастер входит под своей учетной записью Google, данные полностью конфиденциальны.",
  "currentDomainLabel": "Текущий домен (Firebase Authorized Domains):",
  "copyDomainBtn": "Копировать домен",
  "copiedDomainMsg": "Скопировано!",
  "authorizedDomainTip": "Добавьте этот домен в Firebase Console > Authentication > Settings > Authorized Domains.",
  "deleteConfirm": "Вы уверены, что хотите удалить эту карточку?",
  "deleteSuccess": "Карточка клиента успешно удалена.",
  "saveSuccess": "Карточка клиента успешно сохранена.",
  "syncSuccess": "Все записи успешно синхронизированы с облаком."
}

# CHINESE (zh)
zh = {
  "title": "阿扎德师傅",
  "subtitle": "安全裁缝账本与数字化裁剪登记簿",
  "appSubtitle": "专业裁缝云端数字化登记簿",
  "defaultMasterTitle": "师傅",
  "masterNameLabel": "师傅姓名:",
  "masterPhotoLabel": "上传师傅照片:",
  "masterDefaultName": "师傅",
  "navHome": "首页",
  "navSettings": "设置",
  "navAdd": "录入尺寸",
  "searchPlaceholder": "搜索客户姓名或电话号码...",
  "searchAction": "搜索",
  "clear": "清除",
  "recentSearches": "最近搜索",
  "clearHistory": "清除历史记录",
  "openSlip": "打开单据",
  "addMeasurementBtn": "录入尺寸",
  "photoOcrBtn": "纸条 / 布料拍照",
  "cuttingMode": "✂️ 裁剪模式",
  "normalMode": "普通模式",
  "voiceInput": "语音录入",
  "chatbot": "阿扎德 AI 助手",
  "assistant": "助手",
  "settings": "设置与个人资料",
  "privacy": "隐私政策",
  "logout": "退出登录",
  "customerSlipsHeading": "客户裁剪量体单:",
  "statusFiltersHeading": "订单状态筛选:",
  "showingCount": "显示:",
  "allFilter": "全部",
  "statusPending": "待处理",
  "statusCutting": "裁剪中",
  "statusStitching": "缝制中",
  "statusReady": "已就绪",
  "statusDelivered": "已交付",
  "todayDelivery": "今日交付:",
  "lateOrders": "逾期订单:",
  "totalCustomers": "总客户数",
  "quickStats": "概览",
  "recentOrders": "近期订单 (快速查看)",
  "recentOrdersCount": "最新",
  "show": "显示",
  "hide": "隐藏",
  "noRecords": "未找到记录。",
  "noCustomerFound": "未找到客户",
  "noCustomersSaved": "暂无保存的客户记录",
  "searchHintEmpty": "请尝试使用其他姓名或手机号码搜索。",
  "addFirstCustomerHint": "点击下方按钮添加第一张量体单据。",
  "addFirstCustomer": "添加首位客户",
  "tapToAdd": "点击下方 (+) 按钮添加新的量体单。",
  "tapToAddCustomer": "点击此处添加新客户。",
  "addAsNewCustomer": "作为新客户",
  "unnamedCustomer": "未命名客户",
  "date": "日期:",
  "delivery": "交期:",
  "balance": "余款:",
  "cleared": "已结清",
  "syncing": "同步中...",
  "cloudSynced": "已安全保存至云端",
  "syncNow": "立即同步",
  "cloudSyncError": "云端同步错误",
  "online": "在线",
  "selectPhotoSource": "选择纸质单据或布料照片",
  "camera": "相机",
  "gallery": "相册",
  "fillManually": "手动填写表单",
  "uploadPhotoTitle": "纸质单据照片:",
  "galleryBtn": "🖼️ 相册",
  "cameraBtn": "📸 相机",
  "removePhoto": "删除照片",
  "extractingOcr": "AI 正在自动识别尺寸数据...",
  "addSlip": "新增量体尺寸单",
  "editSlip": "编辑量体单据",
  "customerName": "客户姓名 *",
  "phoneNumber": "WhatsApp / 电话 (选填)",
  "countryCodeLabel": "国家区号",
  "suitTypeLabel": "服装款式",
  "suitGents": "男士套装 (衬衫与裤子)",
  "suitKurtaPajama": "库尔塔睡裤套装",
  "suitSafari": "猎装套装",
  "suitWaistcoat": "马甲 / 背心",
  "suitSherwani": "礼服长袍",
  "deliveryDateLabel": "交货日期",
  "quickToday": "今天",
  "quickTomorrow": "明天",
  "quick3Days": "3天",
  "quick1Week": "1周",
  "quick10Days": "10天",
  "orderStatusLabel": "订单状态:",
  "orderLockedNotice": "该订单已标记为已交付并已锁定。您确定要解锁以更改状态吗？",
  "orderLockedBadge": "🔒 已锁定",
  "orderUnlockedBadge": "🔓 可更改",
  "dueTodayBadge": "⚡ 今日到期",
  "lateOrderBadge": "⚠️ 逾期",
  "upcomingBadge": "📅 即将到期",
  "lengthLabel": "衣长",
  "shoulderLabel": "肩宽",
  "sleevesLabel": "袖长",
  "chestLabel": "胸围",
  "waistLabel": "腰围",
  "daamanLabel": "下摆",
  "collarLabel": "领围",
  "shalwarLabel": "裤长",
  "panchaLabel": "裤脚口",
  "pocketLabel": "口袋",
  "specialNotesLabel": "特别说明 / 备注",
  "notesPlaceholder": "例如：圆摆、立领、单明线...",
  "billingHeading": "裁缝费用与账单:",
  "totalAmountLabel": "总金额",
  "advanceAmountLabel": "已付定金",
  "balanceAmountLabel": "待付尾款",
  "fullyPaidBadge": "✓ 已全额结清",
  "balanceDueBadge": "⏳ 待结清",
  "saveDone": "保存并完成",
  "saveClose": "保存并关闭",
  "cancel": "取消",
  "close": "完成 / 关闭",
  "back": "返回",
  "digitalSlip": "数字化裁剪量体单",
  "editMode": "编辑 / 裁剪模式",
  "sendWhatsapp": "通过 WhatsApp 发送单据",
  "copySlip": "复制单据文本",
  "printSlip": "打印",
  "delete": "删除",
  "copySuccess": "单据已复制到剪贴板！",
  "bookedDateLabel": "下单日期:",
  "deliveryDatePrefix": "交货日期:",
  "tailorStamp": "师傅印章",
  "customerDetailsHeading": "客户信息",
  "measurementsHeading": "尺寸详情",
  "accountSummaryHeading": "账目摘要",
  "menuTitle": "阿扎德师傅菜单",
  "profileSettings": "个人资料与设置",
  "changeLanguage": "切换语言",
  "dataBackup": "云端备份与同步",
  "helpSupport": "使用指南与技术支持",
  "developerInfo": "开发者信息",
  "settingsTitle": "个人资料与应用设置",
  "selectAppLanguage": "应用语言",
  "allSupportedLanguages": "全部 22 种支持的语言:",
  "aiVoiceAssistant": "阿扎德 AI 语音助手",
  "aiVoiceAssistantSub": "语音说出或打字输入尺寸，自动进行裁剪计算",
  "appGuide": "使用指南",
  "appGuideSub": "尺寸录入、OCR 拍照扫描、订单追踪与 WhatsApp 发送",
  "cloudAutoSave": "云端自动保存 (Firebase Cloud)",
  "cloudAutoSaveLive": "运行中且安全",
  "cloudDatabaseLabel": "云端数据库:",
  "cloudRecordsLabel": "云端记录数:",
  "lastSyncedLabel": "上次同步:",
  "syncAllNow": "立即将所有数据同步至云端",
  "syncingToCloud": "正在同步到云端...",
  "dataBackupRestore": "数据备份与恢复",
  "recordsCount": "条记录",
  "backupData": "创建备份文件 (JSON)",
  "restoreData": "恢复数据 (JSON)",
  "developerCredit": "开发者: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "版权所有 © 2026 阿扎德师傅",
  "resetAllRecords": "清除所有量体记录",
  "resetRecordsConfirm": "您确定要清空所有客户量体记录吗？此操作无法撤销。",
  "savedSuccess": "保存成功！",
  "cloudSyncSuccess": "数据已成功同步至云端！",
  "noRecordsToBackup": "没有可备份的数据！",
  "backupFileDownloaded": "备份文件已成功下载！",
  "recordsRestoredSuccess": "数据已成功恢复！",
  "noValidRecordsFound": "文件中未找到有效的量体记录。",
  "invalidBackupFile": "无效的备份文件，请选择正确的 JSON 文件。",
  "needHelpTitle": "需要帮助？/ 客服支持",
  "contactWhatsApp": "通过 WhatsApp 联系",
  "contactEmail": "电子邮件支持",
  "appGuideTitle": "如何使用阿扎德师傅",
  "guideStep1Title": "1. 录入新尺寸",
  "guideStep1Desc": "点击下方的 (+) 按钮或“录入尺寸”，输入客户姓名、电话、交期及尺寸数据。",
  "guideStep2Title": "2. ✂️ 裁剪模式的妙用",
  "guideStep2Desc": "在裁剪台操作时开启裁剪模式，数字将以超大高亮展示，远距离也能一目了然。",
  "guideStep3Title": "3. 纸条拍照与 AI 极速识别",
  "guideStep3Desc": "拍摄传统纸质尺寸条，AI 将自动识别并快速填入对应栏目。",
  "guideStep4Title": "4. 数字化 WhatsApp 单据与云端存储",
  "guideStep4Desc": "一键将完整的量体单发送给客户的 WhatsApp，所有数据在云端永久安全加密备份。",
  "closeGuide": "我知道了 / 关闭指南",
  "privacyModalTitle": "隐私政策与数据安全",
  "privacyPolicyP1": "您的所有客户尺寸、联系方式和账务信息均已安全加密存储在您的私人云端账户中。",
  "privacyPolicyP2": "任何未经授权的第三方都无法查看您的裁缝业务数据，保障商业私密。",
  "closePrivacy": "同意并关闭",
  "secureStorage100": "100% 安全加密云端存储",
  "safeBadge": "安全可靠",
  "chatbotHeaderTitle": "阿扎德 AI 助手",
  "chatbotHeaderSub": "在线裁剪与裁缝工艺助手",
  "voiceReplyActive": "语音回答开启",
  "voiceReplyMuted": "语音回答已静音",
  "typingInputPlaceholder": "输入尺寸或咨询裁缝工艺问题...",
  "detectedMeasurementsHeading": "识别到的尺寸数据",
  "confirmAndApplySlip": "确认并应用到量体单",
  "confirmedMeasurement": "已确认",
  "micListeningState": "正在倾听... 请说话",
  "micStartState": "说话",
  "voiceScreenTitle": "阿扎德语音助手",
  "voiceScreenSub": "实时语音交流",
  "tapToSpeak": "点击开始说话",
  "listeningVoice": "正在倾听...",
  "processingVoice": "正在处理分析...",
  "botSpeaking": "正在语音播报回答...",
  "closeVoiceMode": "退出语音模式",
  "browserNoVoice": "当前浏览器不支持语音识别功能。",
  "chatbotGreeting": "您好！我是阿扎德师傅助手。您可以口述或打字输入尺寸（衣长、肩宽、袖长、胸围、腰围、下摆、领围、裤长、裤脚口）。我会自动帮您归类并录入单据。",
  "quickPrompt1": "衣长 42，肩宽 18.5，袖长 23，胸围 38，下摆 24，领围 15.5，裤长 38",
  "quickPrompt2": "制作一套男士传统套装需要多少米布料？",
  "quickPrompt3": "肩宽与袖窿夹圈的准确裁剪计算公式是什么？",
  "quickPrompt4": "如何精确裁剪领窝弧度？",
  "login": "登录",
  "codePlaceholder": "输入 WhatsApp 手机号或验证码...",
  "pinHint": "默认 PIN 码: 123456 (或直接留空登录)",
  "signingIn": "正在登录...",
  "signInWithGoogle": "使用 Google 账号安全登录",
  "openInNewTab": "在新标签页中打开",
  "tryRedirectLogin": "尝试重定向登录",
  "openInNewWindow": "直接在新窗口中打开登录",
  "secureRecords": "100% 安全私密的记录",
  "loginPrivacyNotice": "每位裁缝师傅通过其独立的 Google 账号登录，所有客户数据完全隔离和保密。",
  "currentDomainLabel": "当前域名 (Firebase Authorized Domains):",
  "copyDomainBtn": "复制域名",
  "copiedDomainMsg": "已复制！",
  "authorizedDomainTip": "请将此域名添加至 Firebase Console > Authentication > Settings > Authorized Domains。",
  "deleteConfirm": "您确定要删除此量体单据吗？",
  "deleteSuccess": "客户量体单已成功删除。",
  "saveSuccess": "客户量体单已成功保存。",
  "syncSuccess": "所有数据已成功同步至云端。"
}

# JAPANESE (ja)
ja = {
  "title": "アザド・マスター",
  "subtitle": "安全な仕立て帳簿とデジタル裁断台帳",
  "appSubtitle": "プロの仕立て屋のためのデジタルクラウド台帳",
  "defaultMasterTitle": "マスター仕立て職人",
  "masterNameLabel": "職人の名前:",
  "masterPhotoLabel": "職人の写真を設定:",
  "masterDefaultName": "マスター仕立て職人",
  "navHome": "ホーム",
  "navSettings": "設定",
  "navAdd": "寸法を記録",
  "searchPlaceholder": "お客様のお名前または電話番号で検索...",
  "searchAction": "検索",
  "clear": "クリア",
  "recentSearches": "最近の検索",
  "clearHistory": "履歴を削除",
  "openSlip": "伝票を開く",
  "addMeasurementBtn": "寸法を記録",
  "photoOcrBtn": "寸法メモ / 生地の写真",
  "cuttingMode": "✂️ 裁断モード",
  "normalMode": "通常モード",
  "voiceInput": "音声入力",
  "chatbot": "アザド AI アシスタント",
  "assistant": "アシスタント",
  "settings": "設定とプロフィール",
  "privacy": "プライバシーポリシー",
  "logout": "ログアウト",
  "customerSlipsHeading": "お客様の裁断伝票一覧:",
  "statusFiltersHeading": "注文状況フィルター:",
  "showingCount": "表示中:",
  "allFilter": "すべて",
  "statusPending": "保留中",
  "statusCutting": "裁断中",
  "statusStitching": "縫製中",
  "statusReady": "仕上がり済み",
  "statusDelivered": "納品済み",
  "todayDelivery": "本日の納品:",
  "lateOrders": "納期遅延注文:",
  "totalCustomers": "総顧客数",
  "quickStats": "概要",
  "recentOrders": "最近の注文 (簡易表示)",
  "recentOrdersCount": "最新",
  "show": "表示",
  "hide": "非表示",
  "noRecords": "記録が見つかりませんでした。",
  "noCustomerFound": "該当するお客様が見つかりません",
  "noCustomersSaved": "まだお客様のデータが登録されていません",
  "searchHintEmpty": "別のお名前や電話番号で検索してみてください。",
  "addFirstCustomerHint": "下のボタンをタップして最初のお客様を追加しましょう。",
  "addFirstCustomer": "最初のお客様を登録",
  "tapToAdd": "下の (+) ボタンをタップして新しい伝票を作成します。",
  "tapToAddCustomer": "ここをタップして新規顧客を追加します。",
  "addAsNewCustomer": "新規顧客として登録",
  "unnamedCustomer": "お名前未設定のお客様",
  "date": "受付日:",
  "delivery": "納期:",
  "balance": "残金:",
  "cleared": "完済",
  "syncing": "同期中...",
  "cloudSynced": "クラウドに安全保存済み",
  "syncNow": "今すぐ同期",
  "cloudSyncError": "同期エラー",
  "online": "オンライン",
  "selectPhotoSource": "メモまたは生地の写真を選択",
  "camera": "カメラ",
  "gallery": "ギャラリー",
  "fillManually": "手動で入力する",
  "uploadPhotoTitle": "紙の採寸メモ写真:",
  "galleryBtn": "🖼️ ギャラリー",
  "cameraBtn": "📸 カメラ",
  "removePhoto": "写真を削除",
  "extractingOcr": "AIが寸法メモを自動認識しています...",
  "addSlip": "新規採寸伝票を追加",
  "editSlip": "採寸伝票を編集",
  "customerName": "お客様氏名 *",
  "phoneNumber": "WhatsApp / 電話番号 (任意)",
  "countryCodeLabel": "国番号",
  "suitTypeLabel": "衣服の種類",
  "suitGents": "男性用スーツ (シャツ＆パンツ)",
  "suitKurtaPajama": "クルタ＆パジャマ",
  "suitSafari": "サファリスーツ",
  "suitWaistcoat": "ベスト / ジレ",
  "suitSherwani": "礼服シェルワニ",
  "deliveryDateLabel": "お届け予定日 (納期)",
  "quickToday": "今日",
  "quickTomorrow": "明日",
  "quick3Days": "3日後",
  "quick1Week": "1週間後",
  "quick10Days": "10日後",
  "orderStatusLabel": "注文ステータス:",
  "orderLockedNotice": "この注文は納品済みとしてロックされています。ロックを解除して状態を変更しますか？",
  "orderLockedBadge": "🔒 ロック中",
  "orderUnlockedBadge": "🔓 変更可能",
  "dueTodayBadge": "⚡ 本日納期",
  "lateOrderBadge": "⚠️ 遅延",
  "upcomingBadge": "📅 近日納期",
  "lengthLabel": "着丈",
  "shoulderLabel": "肩幅",
  "sleevesLabel": "袖丈",
  "chestLabel": "胸囲 (バスト)",
  "waistLabel": "胴囲 (ウエスト)",
  "daamanLabel": "裾周り",
  "collarLabel": "首回り (衿)",
  "shalwarLabel": "股下・総丈",
  "panchaLabel": "裾幅",
  "pocketLabel": "ポケット",
  "specialNotesLabel": "特記事項・指示メモ",
  "notesPlaceholder": "例: ラウンドヘム、スタンドカラー、シングルステッチ...",
  "billingHeading": "お仕立て代金とご請求:",
  "totalAmountLabel": "合計金額",
  "advanceAmountLabel": "お預かり内金",
  "balanceAmountLabel": "差引残金",
  "fullyPaidBadge": "✓ 完済",
  "balanceDueBadge": "⏳ 未払い残額あり",
  "saveDone": "保存して完了",
  "saveClose": "保存して閉じる",
  "cancel": "キャンセル",
  "close": "完了 / 閉じる",
  "back": "戻る",
  "digitalSlip": "デジタル裁断伝票",
  "editMode": "編集 / 裁断モード",
  "sendWhatsapp": "WhatsAppで伝票を送信",
  "copySlip": "伝票をコピー",
  "printSlip": "印刷",
  "delete": "削除",
  "copySuccess": "伝票がクリップボードにコピーされました！",
  "bookedDateLabel": "受付日:",
  "deliveryDatePrefix": "仕立て納期:",
  "tailorStamp": "職人認定印",
  "customerDetailsHeading": "顧客情報",
  "measurementsHeading": "寸法詳細",
  "accountSummaryHeading": "ご請求サマリー",
  "menuTitle": "アザド・マスター メニュー",
  "profileSettings": "プロフィールと設定",
  "changeLanguage": "言語を切り替える",
  "dataBackup": "クラウドバックアップと同期",
  "helpSupport": "使い方ガイドとサポート",
  "developerInfo": "開発者情報",
  "settingsTitle": "プロフィールとアプリ設定",
  "selectAppLanguage": "アプリの言語",
  "allSupportedLanguages": "対応している全22言語:",
  "aiVoiceAssistant": "アザド AI 音声アシスタント",
  "aiVoiceAssistantSub": "寸法を声またはテキストで入力し、自動で裁断計算",
  "appGuide": "使い方ガイド",
  "appGuideSub": "採寸入力、OCR写真読取、注文管理、WhatsApp送信",
  "cloudAutoSave": "クラウド自動保存 (Firebase Cloud)",
  "cloudAutoSaveLive": "稼働中・保護済み",
  "cloudDatabaseLabel": "クラウドデータベース:",
  "cloudRecordsLabel": "クラウド保存件数:",
  "lastSyncedLabel": "最終同期:",
  "syncAllNow": "すべてのデータをクラウドに同期する",
  "syncingToCloud": "クラウドへ同期中...",
  "dataBackupRestore": "データバックアップと復元",
  "recordsCount": "件のデータ",
  "backupData": "バックアップを作成 (JSON)",
  "restoreData": "データを復元 (JSON)",
  "developerCredit": "開発者: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "無断転載を禁じます © 2026 アザド・マスター",
  "resetAllRecords": "すべての伝票データを消去",
  "resetRecordsConfirm": "本当にすべてのお客様データを削除しますか？",
  "savedSuccess": "保存が完了しました！",
  "cloudSyncSuccess": "クラウドに正常に同期されました！",
  "noRecordsToBackup": "バックアップするデータがありません！",
  "backupFileDownloaded": "バックアップファイルをダウンロードしました！",
  "recordsRestoredSuccess": "データを正常に復元しました！",
  "noValidRecordsFound": "ファイルに有効なデータが見つかりませんでした。",
  "invalidBackupFile": "無効なファイルです。正しいJSONファイルを選択してください。",
  "needHelpTitle": "お困りですか？ / お問い合わせ",
  "contactWhatsApp": "WhatsAppでお問い合わせ",
  "contactEmail": "メールサポート",
  "appGuideTitle": "アザド・マスターの使い方",
  "guideStep1Title": "1. 新規採寸の登録",
  "guideStep1Desc": "画面下の (+) または「寸法を記録」ボタンをタップしてお客様情報と寸法を入力します。",
  "guideStep2Title": "2. ✂️ 便利な裁断モード",
  "guideStep2Desc": "裁断作業台では「裁断モード」をオンに。数字が大きくはっきりと表示され、作業が捗ります。",
  "guideStep3Title": "3. メモ写真とAI自動入力",
  "guideStep3Desc": "紙の採寸メモをカメラで撮影するだけで、AIが数値を読み取り自動入力します。",
  "guideStep4Title": "4. デジタルWhatsApp伝票とクラウド保護",
  "guideStep4Desc": "ワンタップでお客様のWhatsAppへ明細を送信。データはすべてクラウドに安全に保管されます。",
  "closeGuide": "理解しました / 閉じる",
  "privacyModalTitle": "プライバシーポリシーとデータ保護",
  "privacyPolicyP1": "お客様の採寸寸法、連絡先、お会計データは暗号化され、安全に保管されます。",
  "privacyPolicyP2": "部外者がお客様の仕立てデータにアクセスすることはできません。完全な機密性が保たれます。",
  "closePrivacy": "同意して閉じる",
  "secureStorage100": "100% 安全なクラウド保管",
  "safeBadge": "安全保護",
  "chatbotHeaderTitle": "アザド AI アシスタント",
  "chatbotHeaderSub": "オンライン裁断・仕立て職人サポート",
  "voiceReplyActive": "音声読み上げ: ON",
  "voiceReplyMuted": "音声読み上げ: ミュート",
  "typingInputPlaceholder": "寸法を入力、または仕立ての質問をする...",
  "detectedMeasurementsHeading": "検出された寸法",
  "confirmAndApplySlip": "確認して伝票に反映",
  "confirmedMeasurement": "確認済み",
  "micListeningState": "音声を認識中... どうぞお話しください",
  "micStartState": "話す",
  "voiceScreenTitle": "アザド音声アシスタント",
  "voiceScreenSub": "リアルタイム音声対話",
  "tapToSpeak": "タップして話す",
  "listeningVoice": "聞いています...",
  "processingVoice": "処理中...",
  "botSpeaking": "返答を読み上げ中...",
  "closeVoiceMode": "音声モードを終了",
  "browserNoVoice": "ご利用のブラウザは音声認識に対応していません。",
  "chatbotGreeting": "こんにちは！アザド・マスターのアシスタントです。寸法（着丈、肩幅、袖丈、胸囲、胴囲、裾周り、首回り、股下）を音声またはテキストでお知らせください。自動で整理して登録します。",
  "quickPrompt1": "着丈 42、肩幅 18.5、袖丈 23、胸囲 38、裾周り 24、首回り 15.5、股下 38",
  "quickPrompt2": "男性用スーツ1着に生地は何メートル必要ですか？",
  "quickPrompt3": "肩幅とアームホールの正確な割り出し公式は？",
  "quickPrompt4": "衿ぐりのきれいなカーブの切り出し方は？",
  "login": "ログイン",
  "codePlaceholder": "WhatsApp番号またはコードを入力...",
  "pinHint": "初期PIN: 123456 (または空欄のままログイン)",
  "signingIn": "ログイン中...",
  "signInWithGoogle": "Google アカウントで安全ログイン",
  "openInNewTab": "新しいタブで開く",
  "tryRedirectLogin": "リダイレクトログインを試す",
  "openInNewWindow": "新しいウィンドウで直接開く",
  "secureRecords": "100% 安全でプライベートな顧客台帳",
  "loginPrivacyNotice": "職人ごとに個別のGoogleアカウントでログインするため、顧客データは完全に保護されます。",
  "currentDomainLabel": "現在のドメイン (Firebase Authorized Domains):",
  "copyDomainBtn": "ドメインをコピー",
  "copiedDomainMsg": "コピーしました！",
  "authorizedDomainTip": "このドメインを Firebase Console > Authentication > Settings > Authorized Domains に登録してください。",
  "deleteConfirm": "本当にこの伝票を削除しますか？",
  "deleteSuccess": "お客様の伝票を削除しました。",
  "saveSuccess": "お客様の伝票を保存しました。",
  "syncSuccess": "すべてのデータがクラウドに同期されました。"
}

# KOREAN (ko)
ko = {
  "title": "아자드 마스터",
  "subtitle": "안전한 테일러링 장부 및 디지털 재단 장부",
  "appSubtitle": "전문 재단사를 위한 디지털 클라우드 대장",
  "defaultMasterTitle": "마스터 재단사",
  "masterNameLabel": "재단사 이름:",
  "masterPhotoLabel": "사진 등록:",
  "masterDefaultName": "마스터 재단사",
  "navHome": "홈",
  "navSettings": "설정",
  "navAdd": "치수 등록",
  "searchPlaceholder": "고객 이름 또는 전화번호 검색...",
  "searchAction": "검색",
  "clear": "지우기",
  "recentSearches": "최근 검색",
  "clearHistory": "기록 지우기",
  "openSlip": "전표 열기",
  "addMeasurementBtn": "치수 등록",
  "photoOcrBtn": "치수 메모 / 원단 사진",
  "cuttingMode": "✂️ 재단 모드",
  "normalMode": "일반 모드",
  "voiceInput": "음성 입력",
  "chatbot": "아자드 AI 어시스턴트",
  "assistant": "어시스턴트",
  "settings": "설정 및 프로필",
  "privacy": "개인정보 처리방침",
  "logout": "로그아웃",
  "customerSlipsHeading": "고객 재단 전표 목록:",
  "statusFiltersHeading": "주문 상태 필터:",
  "showingCount": "표시:",
  "allFilter": "전체",
  "statusPending": "대기 중",
  "statusCutting": "재단 중",
  "statusStitching": "봉제 중",
  "statusReady": "준비 완료",
  "statusDelivered": "출고 완료",
  "todayDelivery": "오늘 출고 예정:",
  "lateOrders": "지연된 주문:",
  "totalCustomers": "총 고객 수",
  "quickStats": "요약",
  "recentOrders": "최근 주문 (빠른 보기)",
  "recentOrdersCount": "최신순",
  "show": "보기",
  "hide": "숨기기",
  "noRecords": "기록이 없습니다.",
  "noCustomerFound": "고객을 찾을 수 없습니다",
  "noCustomersSaved": "아직 저장된 고객이 없습니다",
  "searchHintEmpty": "다른 이름이나 전화번호로 검색해 보세요.",
  "addFirstCustomerHint": "아래 버튼을 눌러 첫 번째 치수 전표를 등록하세요.",
  "addFirstCustomer": "첫 고객 등록",
  "tapToAdd": "새로운 치수를 입력하려면 아래 (+) 버튼을 누르세요.",
  "tapToAddCustomer": "새 고객을 추가하려면 여기를 누르세요.",
  "addAsNewCustomer": "신규 고객으로 추가",
  "unnamedCustomer": "이름 없는 고객",
  "date": "접수일:",
  "delivery": "출고일:",
  "balance": "잔액:",
  "cleared": "완납",
  "syncing": "동기화 중...",
  "cloudSynced": "클라우드 안전 저장됨",
  "syncNow": "지금 동기화",
  "cloudSyncError": "클라우드 오류",
  "online": "온라인",
  "selectPhotoSource": "치수 메모 또는 원단 사진 선택",
  "camera": "카메라",
  "gallery": "갤러리",
  "fillManually": "직접 입력하기",
  "uploadPhotoTitle": "종이 치수 메모 사진:",
  "galleryBtn": "🖼️ 갤러리",
  "cameraBtn": "📸 카메라",
  "removePhoto": "사진 삭제",
  "extractingOcr": "AI가 치수 메모를 판독하고 있습니다...",
  "addSlip": "새 치수 전표 등록",
  "editSlip": "치수 전표 수정",
  "customerName": "고객 이름 *",
  "phoneNumber": "WhatsApp / 연락처 (선택)",
  "countryCodeLabel": "국가 번호",
  "suitTypeLabel": "의류 종류",
  "suitGents": "남성 수트 (셔츠 & 바지)",
  "suitKurtaPajama": "쿠르타 파자마",
  "suitSafari": "사파리 수트",
  "suitWaistcoat": "베스트 / 조끼",
  "suitSherwani": "예복 셰르와니",
  "deliveryDateLabel": "출고 예정일 (납기)",
  "quickToday": "오늘",
  "quickTomorrow": "내일",
  "quick3Days": "3일 후",
  "quick1Week": "1주일 후",
  "quick10Days": "10일 후",
  "orderStatusLabel": "주문 상태:",
  "orderLockedNotice": "이 주문은 출고 완료 상태로 잠겨 있습니다. 상태를 변경하기 위해 잠금을 해제하시겠습니까?",
  "orderLockedBadge": "🔒 잠김",
  "orderUnlockedBadge": "🔓 수정 가능",
  "dueTodayBadge": "⚡ 오늘 납기",
  "lateOrderBadge": "⚠️ 지연됨",
  "upcomingBadge": "📅 예정됨",
  "lengthLabel": "총기장",
  "shoulderLabel": "어깨너비",
  "sleevesLabel": "소매기장",
  "chestLabel": "가슴둘레",
  "waistLabel": "허리둘레",
  "daamanLabel": "밑단둘레",
  "collarLabel": "목둘레 (깃)",
  "shalwarLabel": "바지기장",
  "panchaLabel": "바지 밑단너비",
  "pocketLabel": "주머니",
  "specialNotesLabel": "특이사항 및 지시사항",
  "notesPlaceholder": "예: 라운드 밑단, 차이나 카라, 한 줄 스티치...",
  "billingHeading": "공임 및 결제 내역:",
  "totalAmountLabel": "총 금액",
  "advanceAmountLabel": "계약금 (선수금)",
  "balanceAmountLabel": "잔금",
  "fullyPaidBadge": "✓ 전액 완납",
  "balanceDueBadge": "⏳ 잔금 미납",
  "saveDone": "저장 및 완료",
  "saveClose": "저장 후 닫기",
  "cancel": "취소",
  "close": "완료 / 닫기",
  "back": "뒤로",
  "digitalSlip": "디지털 재단 전표",
  "editMode": "수정 / 재단 모드",
  "sendWhatsapp": "WhatsApp으로 전표 전송",
  "copySlip": "전표 복사",
  "printSlip": "인쇄",
  "delete": "삭제",
  "copySuccess": "전표가 클립보드에 복사되었습니다!",
  "bookedDateLabel": "접수일자:",
  "deliveryDatePrefix": "납품일자:",
  "tailorStamp": "마스터 테일러 직인",
  "customerDetailsHeading": "고객 정보",
  "measurementsHeading": "상세 치수",
  "accountSummaryHeading": "정산 요약",
  "menuTitle": "아자드 마스터 메뉴",
  "profileSettings": "프로필 및 설정",
  "changeLanguage": "언어 변경",
  "dataBackup": "클라우드 백업 및 동기화",
  "helpSupport": "이용 가이드 및 고객지원",
  "developerInfo": "개발자 정보",
  "settingsTitle": "프로필 및 앱 설정",
  "selectAppLanguage": "앱 언어",
  "allSupportedLanguages": "지원되는 전체 22개 언어:",
  "aiVoiceAssistant": "아자드 AI 음성 어시스턴트",
  "aiVoiceAssistantSub": "치수를 말하거나 입력하면 자동 재단 계산 지원",
  "appGuide": "사용 가이드",
  "appGuideSub": "치수 등록, 사진 스캔, 주문 관리 및 WhatsApp 전송",
  "cloudAutoSave": "클라우드 자동 저장 (Firebase)",
  "cloudAutoSaveLive": "안전하게 작동 중",
  "cloudDatabaseLabel": "클라우드 데이터베이스:",
  "cloudRecordsLabel": "클라우드 저장 건수:",
  "lastSyncedLabel": "최근 동기화:",
  "syncAllNow": "지금 모든 데이터를 클라우드에 동기화",
  "syncingToCloud": "클라우드 동기화 중...",
  "dataBackupRestore": "데이터 백업 및 복원",
  "recordsCount": "건",
  "backupData": "백업 파일 생성 (JSON)",
  "restoreData": "데이터 복원 (JSON)",
  "developerCredit": "개발자: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "All rights reserved © 2026 아자드 마스터",
  "resetAllRecords": "모든 전표 데이터 초기화",
  "resetRecordsConfirm": "정말로 모든 고객 기록을 삭제하시겠습니까?",
  "savedSuccess": "저장되었습니다!",
  "cloudSyncSuccess": "기록이 클라우드에 성공적으로 동기화되었습니다!",
  "noRecordsToBackup": "백업할 기록이 없습니다!",
  "backupFileDownloaded": "백업 파일이 다운로드되었습니다!",
  "recordsRestoredSuccess": "데이터가 성공적으로 복원되었습니다!",
  "noValidRecordsFound": "파일에서 유효한 데이터를 찾을 수 없습니다.",
  "invalidBackupFile": "유효하지 않은 파일입니다. 올바른 JSON 파일을 선택해 주세요.",
  "needHelpTitle": "도움이 필요하신가요? / 고객지원",
  "contactWhatsApp": "WhatsApp으로 문의",
  "contactEmail": "이메일 지원",
  "appGuideTitle": "아자드 마스터 사용법",
  "guideStep1Title": "1. 새 치수 등록하기",
  "guideStep1Desc": "하단의 (+) 또는 '치수 등록' 버튼을 눌러 고객 정보와 치수, 납기를 입력합니다.",
  "guideStep2Title": "2. ✂️ 유용한 재단 모드",
  "guideStep2Desc": "재단대 작업 시 '재단 모드'를 켜면 숫자가 크고 선명하게 표시되어 작업이 편리합니다.",
  "guideStep3Title": "3. 종이 메모 사진 및 AI 자동 판독",
  "guideStep3Desc": "기존 종이 메모를 촬영하면 AI가 숫자를 읽어 자동으로 입력칸을 채워줍니다.",
  "guideStep4Title": "4. 디지털 WhatsApp 전표 및 클라우드",
  "guideStep4Desc": "터치 한 번으로 고객에게 WhatsApp 전표를 보내고 모든 내역은 클라우드에 보관됩니다.",
  "closeGuide": "확인했습니다 / 닫기",
  "privacyModalTitle": "개인정보 보호 및 데이터 보안",
  "privacyPolicyP1": "모든 고객 치수와 연락처, 정산 내역은 개인 클라우드 계정에 암호화되어 안전하게 보관됩니다.",
  "privacyPolicyP2": "외부인이 귀하의 재단 기록에 접근할 수 없으며 철저히 보호됩니다.",
  "closePrivacy": "동의하고 닫기",
  "secureStorage100": "100% 안전한 클라우드 보관",
  "safeBadge": "보안 완료",
  "chatbotHeaderTitle": "아자드 AI 어시스턴트",
  "chatbotHeaderSub": "온라인 재단 및 테일러링 지원 어시스턴트",
  "voiceReplyActive": "음성 안내 켜짐",
  "voiceReplyMuted": "음성 안내 음소거",
  "typingInputPlaceholder": "치수를 입력하거나 재단 관련 질문을 하세요...",
  "detectedMeasurementsHeading": "감지된 치수",
  "confirmAndApplySlip": "확인 및 전표에 반영",
  "confirmedMeasurement": "확인됨",
  "micListeningState": "듣고 있습니다... 말씀하세요",
  "micStartState": "말하기",
  "voiceScreenTitle": "아자드 음성 어시스턴트",
  "voiceScreenSub": "실시간 음성 대화",
  "tapToSpeak": "터치하여 말하기",
  "listeningVoice": "듣는 중...",
  "processingVoice": "처리 중...",
  "botSpeaking": "답변을 읽어주는 중...",
  "closeVoiceMode": "음성 모드 종료",
  "browserNoVoice": "이 브라우저는 음성 인식을 지원하지 않습니다.",
  "chatbotGreeting": "안녕하세요! 아자드 마스터 어시스턴트입니다. 치수(기장, 어깨, 소매, 가슴, 허리, 밑단, 목둘레, 바지기장, 밑단너비)를 음성이나 텍스트로 알려주시면 정리해서 전표에 등록해 드립니다.",
  "quickPrompt1": "기장 42, 어깨 18.5, 소매 23, 가슴 38, 밑단 24, 목 15.5, 바지 38",
  "quickPrompt2": "남성 수트 1벌에 필요한 원단 길이는 얼마인가요?",
  "quickPrompt3": "어깨와 암홀 라인을 산출하는 정확한 공식은?",
  "quickPrompt4": "목둘레 깃 곡선을 정확하게 재단하는 방법은?",
  "login": "로그인",
  "codePlaceholder": "WhatsApp 번호 또는 코드 입력...",
  "pinHint": "기본 PIN: 123456 (또는 빈칸으로 로그인)",
  "signingIn": "로그인 중...",
  "signInWithGoogle": "Google 계정으로 안전하게 로그인",
  "openInNewTab": "새 탭에서 열기",
  "tryRedirectLogin": "리디렉션 로그인 시도",
  "openInNewWindow": "새 창에서 직접 로그인",
  "secureRecords": "100% 안전한 고객 기록",
  "loginPrivacyNotice": "각 재단사는 본인의 Google 계정으로 로그인하여 데이터를 안전하게 단독 관리합니다.",
  "currentDomainLabel": "현재 도메인 (Firebase Authorized Domains):",
  "copyDomainBtn": "도메인 복사",
  "copiedDomainMsg": "복사되었습니다!",
  "authorizedDomainTip": "이 도메인을 Firebase Console > Authentication > Settings > Authorized Domains에 추가하세요.",
  "deleteConfirm": "정말로 이 전표를 삭제하시겠습니까?",
  "deleteSuccess": "고객 전표가 성공적으로 삭제되었습니다.",
  "saveSuccess": "고객 전표가 성공적으로 저장되었습니다.",
  "syncSuccess": "모든 기록이 클라우드에 동기화되었습니다."
}

# MALAY (ms)
ms = {
  "title": "AZAD MASTER",
  "subtitle": "Pengurusan Jahitan Selamat & Buku Potongan Digital",
  "appSubtitle": "Buku Rekod Awan Digital Tukang Jahit Profesional",
  "defaultMasterTitle": "Tukang Jahit Mahir",
  "masterNameLabel": "Nama Tukang Jahit:",
  "masterPhotoLabel": "Foto Tukang Jahit:",
  "masterDefaultName": "Tukang Jahit Mahir",
  "navHome": "Utama",
  "navSettings": "Tetapan",
  "navAdd": "Tambah Ukuran",
  "searchPlaceholder": "Cari nama atau nombor telefon pelanggan...",
  "searchAction": "Cari",
  "clear": "Padam",
  "recentSearches": "Carian Terkini",
  "clearHistory": "Kosongkan Sejarah",
  "openSlip": "Buka Slip",
  "addMeasurementBtn": "Tambah Ukuran",
  "photoOcrBtn": "Foto Slip / Kain",
  "cuttingMode": "✂️ Mod Potongan",
  "normalMode": "Mod Biasa",
  "voiceInput": "Input Suara",
  "chatbot": "Pembantu AI Azad",
  "assistant": "Pembantu",
  "settings": "Tetapan & Profil",
  "privacy": "Dasar Privasi",
  "logout": "Log Keluar",
  "customerSlipsHeading": "Slip Potongan Pelanggan:",
  "statusFiltersHeading": "Penapis Status Pesanan:",
  "showingCount": "Dipaparkan:",
  "allFilter": "Semua",
  "statusPending": "Dalam Proses",
  "statusCutting": "Sedang Dipotong",
  "statusStitching": "Sedang Dijahit",
  "statusReady": "Sedia Diambil",
  "statusDelivered": "Telah Diserahkan",
  "todayDelivery": "Serahan Hari Ini:",
  "lateOrders": "Pesanan Lewat:",
  "totalCustomers": "Jumlah Pelanggan",
  "quickStats": "Ringkasan",
  "recentOrders": "Pesanan Terkini (Pandangan Pantas)",
  "recentOrdersCount": "Terkini",
  "show": "Papar",
  "hide": "Sembunyi",
  "noRecords": "Tiada rekod dijumpai.",
  "noCustomerFound": "Pelanggan tidak dijumpai",
  "noCustomersSaved": "Belum ada pelanggan disimpan",
  "searchHintEmpty": "Cuba cari dengan nama atau nombor telefon lain.",
  "addFirstCustomerHint": "Tekan butang di bawah untuk menambah slip ukuran pertama anda.",
  "addFirstCustomer": "Tambah Pelanggan Pertama",
  "tapToAdd": "Tekan butang (+) di bawah untuk memasukkan ukuran baharu.",
  "tapToAddCustomer": "Tekan sini untuk menambah pelanggan baharu.",
  "addAsNewCustomer": "sebagai Pelanggan Baharu",
  "unnamedCustomer": "Pelanggan Tanpa Nama",
  "date": "Tarikh:",
  "delivery": "Serahan:",
  "balance": "Baki:",
  "cleared": "Selesai",
  "syncing": "Menyelaras...",
  "cloudSynced": "Disimpan Selamat di Awan",
  "syncNow": "Selaras Sekarang",
  "cloudSyncError": "Ralat Awan",
  "online": "Dalam Talian",
  "selectPhotoSource": "Pilih Foto Kertas Ukuran atau Kain",
  "camera": "Kamera",
  "gallery": "Galeri",
  "fillManually": "Isi Borang Secara Manual",
  "uploadPhotoTitle": "Foto Kertas Ukuran:",
  "galleryBtn": "🖼️ Galeri",
  "cameraBtn": "📸 Kamera",
  "removePhoto": "Buang Foto",
  "extractingOcr": "AI sedang membaca ukuran daripada foto...",
  "addSlip": "Tambah Slip Ukuran Baharu",
  "editSlip": "Edit Slip Ukuran",
  "customerName": "Nama Pelanggan *",
  "phoneNumber": "Nombor WhatsApp (Pilihan)",
  "countryCodeLabel": "Kod Negara",
  "suitTypeLabel": "Jenis Pakaian",
  "suitGents": "Baju Melayu / Pakaian Lelaki",
  "suitKurtaPajama": "Kurta & Pajama",
  "suitSafari": "Suit Safari",
  "suitWaistcoat": "Vest / Rompi",
  "suitSherwani": "Sherwani Rasmi",
  "deliveryDateLabel": "Tarikh Siap (Serahan)",
  "quickToday": "Hari Ini",
  "quickTomorrow": "Esok",
  "quick3Days": "3 Hari",
  "quick1Week": "1 Minggu",
  "quick10Days": "10 Hari",
  "orderStatusLabel": "Status Pesanan:",
  "orderLockedNotice": "Pesanan ini ditandakan sebagai Telah Diserahkan dan dikunci. Adakah anda ingin membuka kunci untuk menukar status?",
  "orderLockedBadge": "🔒 Dikunci",
  "orderUnlockedBadge": "🔓 Boleh Diubah",
  "dueTodayBadge": "⚡ Siap Hari Ini",
  "lateOrderBadge": "⚠️ Lewat",
  "upcomingBadge": "📅 Akan Datang",
  "lengthLabel": "Labuh Baju",
  "shoulderLabel": "Bahu",
  "sleevesLabel": "Panjang Lengan",
  "chestLabel": "Dada",
  "waistLabel": "Pinggang",
  "daamanLabel": "Bawah / Kaki Baju",
  "collarLabel": "Leher / Kolar",
  "shalwarLabel": "Labuh Seluar",
  "panchaLabel": "Kaki Seluar",
  "pocketLabel": "Poket",
  "specialNotesLabel": "Nota Khas / Arahan",
  "notesPlaceholder": "Cth: Kolar cekak musang, kekek, pesak gantung...",
  "billingHeading": "Upah & Pembayaran:",
  "totalAmountLabel": "Jumlah Harga",
  "advanceAmountLabel": "Bayaran Pendahuluan (Deposit)",
  "balanceAmountLabel": "Baki Belum Bayar",
  "fullyPaidBadge": "✓ Dibayar Penuh",
  "balanceDueBadge": "⏳ Ada Baki",
  "saveDone": "Simpan dan Siap",
  "saveClose": "Simpan dan Tutup",
  "cancel": "Batal",
  "close": "Selesai / Tutup",
  "back": "Kembali",
  "digitalSlip": "Slip Potongan Digital",
  "editMode": "Edit / Mod Potongan",
  "sendWhatsapp": "Hantar Slip via WhatsApp",
  "copySlip": "Salin Slip",
  "printSlip": "Cetak",
  "delete": "Padam",
  "copySuccess": "Slip telah disalin ke papan keratan!",
  "bookedDateLabel": "Tarikh Tempah:",
  "deliveryDatePrefix": "Tarikh Ambil:",
  "tailorStamp": "Cop Tukang Jahit",
  "customerDetailsHeading": "Maklumat Pelanggan",
  "measurementsHeading": "Butiran Ukuran",
  "accountSummaryHeading": "Ringkasan Akaun",
  "menuTitle": "Menu Azad Master",
  "profileSettings": "Profil & Tetapan",
  "changeLanguage": "Tukar Bahasa",
  "dataBackup": "Sandaran & Penyelarasan Awan",
  "helpSupport": "Panduan & Bantuan",
  "developerInfo": "Maklumat Pembangun",
  "settingsTitle": "Profil & Tetapan Aplikasi",
  "selectAppLanguage": "Bahasa Aplikasi",
  "allSupportedLanguages": "Semua 22 Bahasa Disokong:",
  "aiVoiceAssistant": "Pembantu Suara AI Azad",
  "aiVoiceAssistantSub": "Sebut atau taip ukuran untuk pengiraan potongan automatik",
  "appGuide": "Panduan Pengguna",
  "appGuideSub": "Kemasukan ukuran, imbasan OCR, penjejakan pesanan & WhatsApp",
  "cloudAutoSave": "Simpanan Automatik Awan (Firebase)",
  "cloudAutoSaveLive": "Aktif & Selamat",
  "cloudDatabaseLabel": "Pangkalan Data Awan:",
  "cloudRecordsLabel": "Rekod Awan:",
  "lastSyncedLabel": "Penyelarasan Terakhir:",
  "syncAllNow": "Selaras Semua Data ke Awan Sekarang",
  "syncingToCloud": "Menyelaras ke awan...",
  "dataBackupRestore": "Sandaran & Pemulihan Data",
  "recordsCount": "Rekod",
  "backupData": "Cipta Fail Sandaran (JSON)",
  "restoreData": "Pulihkan Data (JSON)",
  "developerCredit": "Pembangun: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "Hak Cipta Terpelihara © 2026 Azad Master",
  "resetAllRecords": "Padam Semua Slip Ukuran",
  "resetRecordsConfirm": "Adakah anda pasti mahu memadamkan semua rekod pelanggan?",
  "savedSuccess": "Berjaya disimpan!",
  "cloudSyncSuccess": "Rekod berjaya diselaraskan ke awan!",
  "noRecordsToBackup": "Tiada rekod untuk disandarkan!",
  "backupFileDownloaded": "Fail sandaran berjaya dimuat turun!",
  "recordsRestoredSuccess": "Rekod berjaya dipulihkan!",
  "noValidRecordsFound": "Tiada rekod sah dijumpai dalam fail.",
  "invalidBackupFile": "Fail tidak sah. Sila pilih fail JSON yang betul.",
  "needHelpTitle": "Perlukan Bantuan? / Sokongan",
  "contactWhatsApp": "Hubungi melalui WhatsApp",
  "contactEmail": "Sokongan E-mel",
  "appGuideTitle": "Cara Menggunakan Azad Master",
  "guideStep1Title": "1. Tambah Ukuran Baharu",
  "guideStep1Desc": "Tekan butang (+) atau 'Tambah Ukuran' untuk memasukkan nama, telefon, ukuran dan tarikh serahan.",
  "guideStep2Title": "2. ✂️ Kelebihan Mod Potongan",
  "guideStep2Desc": "Aktifkan Mod Potongan semasa di meja kerja untuk melihat angka yang besar dan jelas dibaca dari jauh.",
  "guideStep3Title": "3. Foto Kertas Ukuran & Imbasan AI",
  "guideStep3Desc": "Ambil gambar kertas ukuran tradisional, AI akan mengisi ukuran secara automatik.",
  "guideStep4Title": "4. Slip Digital WhatsApp & Awan",
  "guideStep4Desc": "Hantar slip lengkap kepada pelanggan di WhatsApp dengan satu klik dan simpan segalanya di awan.",
  "closeGuide": "Faham / Tutup Panduan",
  "privacyModalTitle": "Dasar Privasi & Keselamatan Data",
  "privacyPolicyP1": "Semua ukuran, kontak dan rekod bayaran pelanggan disimpan secara disulitkan dalam akaun peribadi anda.",
  "privacyPolicyP2": "Tiada pihak ketiga yang boleh mengakses rekod jahitan anda. Semua data adalah selamat dan peribadi.",
  "closePrivacy": "Setuju & Tutup",
  "secureStorage100": "100% Simpanan Awan Selamat",
  "safeBadge": "Selamat",
  "chatbotHeaderTitle": "Pembantu AI Azad",
  "chatbotHeaderSub": "Pembantu Jahitan & Pemotongan Atas Talian",
  "voiceReplyActive": "Balasan Suara Aktif",
  "voiceReplyMuted": "Balasan Suara Senyap",
  "typingInputPlaceholder": "Taip ukuran atau tanya soalan jahitan...",
  "detectedMeasurementsHeading": "Ukuran Dikesan",
  "confirmAndApplySlip": "Sahkan & Masukkan ke Slip",
  "confirmedMeasurement": "Disahkan",
  "micListeningState": "Mendengar... Sila bercakap",
  "micStartState": "Bercakap",
  "voiceScreenTitle": "Pembantu Suara Azad",
  "voiceScreenSub": "Perbualan Suara Langsung",
  "tapToSpeak": "Tekan untuk Bercakap",
  "listeningVoice": "Sedang mendengar...",
  "processingVoice": "Sedang diproses...",
  "botSpeaking": "Membacakan jawapan...",
  "closeVoiceMode": "Tutup Mod Suara",
  "browserNoVoice": "Pengecaman suara tidak disokong pada pelayar ini.",
  "chatbotGreeting": "Salam sejahtera! Saya pembantu Azad Master. Anda boleh sebut atau taip ukuran (Labuh, Bahu, Lengan, Dada, Pinggang, Bawah, Kolar, Seluar). Saya akan susun dan masukkannya ke slip.",
  "quickPrompt1": "Labuh 42, Bahu 18.5, Lengan 23, Dada 38, Bawah 24, Kolar 15.5, Seluar 38",
  "quickPrompt2": "Berapa meter kain diperlukan untuk sepasang baju Melayu?",
  "quickPrompt3": "Apakah formula tepat untuk potongan lubang lengan dan bahu?",
  "quickPrompt4": "Bagaimana cara memotong leher kolar dengan kemas?",
  "login": "Log Masuk",
  "codePlaceholder": "Masukkan WhatsApp atau Kod...",
  "pinHint": "PIN Lalai: 123456 (atau biarkan kosong)",
  "signingIn": "Sedang log masuk...",
  "signInWithGoogle": "Log Masuk Selamat dengan Google",
  "openInNewTab": "Buka dalam Tab Baharu",
  "tryRedirectLogin": "Cuba Log Masuk Lencongan",
  "openInNewWindow": "Buka terus dalam tetingkap baharu",
  "secureRecords": "100% Rekod Selamat & Peribadi",
  "loginPrivacyNotice": "Setiap tukang jahit log masuk dengan akaun Google sendiri dan semua rekod kekal sulit.",
  "currentDomainLabel": "Domain Semasa (Firebase Authorized Domains):",
  "copyDomainBtn": "Salin Domain",
  "copiedDomainMsg": "Disalin!",
  "authorizedDomainTip": "Sila tambah domain ini dalam Firebase Console > Authentication > Settings > Authorized Domains.",
  "deleteConfirm": "Adakah anda pasti ingin memadamkan slip ini?",
  "deleteSuccess": "Slip pelanggan berjaya dipadam.",
  "saveSuccess": "Slip pelanggan berjaya disimpan.",
  "syncSuccess": "Semua rekod telah diselaraskan ke awan."
}

# INDONESIAN (id)
id = {
  "title": "AZAD MASTER",
  "subtitle": "Manajemen Jahit Aman & Buku Potong Digital",
  "appSubtitle": "Buku Kas Awan Digital Penjahit Profesional",
  "defaultMasterTitle": "Master Penjahit",
  "masterNameLabel": "Nama Penjahit:",
  "masterPhotoLabel": "Foto Penjahit:",
  "masterDefaultName": "Master Penjahit",
  "navHome": "Beranda",
  "navSettings": "Pengaturan",
  "navAdd": "Catat Ukuran",
  "searchPlaceholder": "Cari nama atau nomor telepon pelanggan...",
  "searchAction": "Cari",
  "clear": "Hapus",
  "recentSearches": "Pencarian Terkini",
  "clearHistory": "Hapus Riwayat",
  "openSlip": "Buka Nota",
  "addMeasurementBtn": "Catat Ukuran",
  "photoOcrBtn": "Foto Nota / Kain",
  "cuttingMode": "✂️ Mode Potong",
  "normalMode": "Mode Normal",
  "voiceInput": "Input Suara",
  "chatbot": "Asisten AI Azad",
  "assistant": "Asisten",
  "settings": "Pengaturan & Profil",
  "privacy": "Kebijakan Privasi",
  "logout": "Keluar",
  "customerSlipsHeading": "Nota Potong Pelanggan:",
  "statusFiltersHeading": "Filter Status Pesanan:",
  "showingCount": "Ditampilkan:",
  "allFilter": "Semua",
  "statusPending": "Menunggu",
  "statusCutting": "Sedang Dipotong",
  "statusStitching": "Sedang Dijahit",
  "statusReady": "Siap Diambil",
  "statusDelivered": "Telah Diserahkan",
  "todayDelivery": "Pengambilan Hari Ini:",
  "lateOrders": "Pesanan Terlambat:",
  "totalCustomers": "Total Pelanggan",
  "quickStats": "Ringkasan",
  "recentOrders": "Pesanan Terkini (Tampilan Cepat)",
  "recentOrdersCount": "Terbaru",
  "show": "Tampilkan",
  "hide": "Sembunyikan",
  "noRecords": "Tidak ada data ditemukan.",
  "noCustomerFound": "Pelanggan tidak ditemukan",
  "noCustomersSaved": "Belum ada pelanggan tersimpan",
  "searchHintEmpty": "Coba cari dengan nama atau nomor telepon lain.",
  "addFirstCustomerHint": "Ketuk tombol di bawah untuk menambahkan nota ukuran pertama Anda.",
  "addFirstCustomer": "Tambah Pelanggan Pertama",
  "tapToAdd": "Ketuk tombol (+) di bawah untuk mencatat ukuran baru.",
  "tapToAddCustomer": "Ketuk di sini untuk menambah pelanggan baru.",
  "addAsNewCustomer": "sebagai Pelanggan Baru",
  "unnamedCustomer": "Pelanggan Tanpa Nama",
  "date": "Tanggal:",
  "delivery": "Selesai:",
  "balance": "Sisa:",
  "cleared": "Lunas",
  "syncing": "Menyinkronkan...",
  "cloudSynced": "Tersimpan Aman di Cloud",
  "syncNow": "Sinkronkan Sekarang",
  "cloudSyncError": "Kesalahan Cloud",
  "online": "Online",
  "selectPhotoSource": "Pilih Foto Kertas Ukuran atau Kain",
  "camera": "Kamera",
  "gallery": "Galeri",
  "fillManually": "Isi Formulir Manual",
  "uploadPhotoTitle": "Foto Kertas Ukuran:",
  "galleryBtn": "🖼️ Galeri",
  "cameraBtn": "📸 Kamera",
  "removePhoto": "Hapus Foto",
  "extractingOcr": "AI sedang membaca ukuran dari foto...",
  "addSlip": "Tambah Nota Ukuran Baru",
  "editSlip": "Edit Nota Ukuran",
  "customerName": "Nama Pelanggan *",
  "phoneNumber": "Nomor WhatsApp (Opsional)",
  "countryCodeLabel": "Kode Negara",
  "suitTypeLabel": "Jenis Busana",
  "suitGents": "Setelan Pria (Kemeja & Celana)",
  "suitKurtaPajama": "Kurta & Celana",
  "suitSafari": "Setelan Safari",
  "suitWaistcoat": "Rompi",
  "suitSherwani": "Jas Resmi Sherwani",
  "deliveryDateLabel": "Tanggal Selesai (Pengambilan)",
  "quickToday": "Hari Ini",
  "quickTomorrow": "Besok",
  "quick3Days": "3 Hari",
  "quick1Week": "1 Minggu",
  "quick10Days": "10 Hari",
  "orderStatusLabel": "Status Pesanan:",
  "orderLockedNotice": "Pesanan ini ditandai Telah Diserahkan dan terkunci. Buka kunci untuk mengubah status?",
  "orderLockedBadge": "🔒 Terkunci",
  "orderUnlockedBadge": "🔓 Dapat Diubah",
  "dueTodayBadge": "⚡ Selesai Hari Ini",
  "lateOrderBadge": "⚠️ Terlambat",
  "upcomingBadge": "📅 Mendatang",
  "lengthLabel": "Panjang Baju",
  "shoulderLabel": "Pundak / Bahu",
  "sleevesLabel": "Panjang Lengan",
  "chestLabel": "Lingkar Dada",
  "waistLabel": "Lingkar Pinggang",
  "daamanLabel": "Keliman Bawah",
  "collarLabel": "Kerah / Leher",
  "shalwarLabel": "Panjang Celana",
  "panchaLabel": "Ujung Celana",
  "pocketLabel": "Saku",
  "specialNotesLabel": "Catatan Khusus / Instruksi",
  "notesPlaceholder": "Contoh: Bawah melengkung, kerah shanghai, jahitan tunggal...",
  "billingHeading": "Ongkos Jahit & Pembayaran:",
  "totalAmountLabel": "Total Biaya",
  "advanceAmountLabel": "Uang Muka (DP)",
  "balanceAmountLabel": "Sisa Pembayaran",
  "fullyPaidBadge": "✓ Lunas",
  "balanceDueBadge": "⏳ Belum Lunas",
  "saveDone": "Simpan dan Selesai",
  "saveClose": "Simpan dan Tutup",
  "cancel": "Batal",
  "close": "Selesai / Tutup",
  "back": "Kembali",
  "digitalSlip": "Nota Potong Digital",
  "editMode": "Edit / Mode Potong",
  "sendWhatsapp": "Kirim Nota via WhatsApp",
  "copySlip": "Salin Nota",
  "printSlip": "Cetak",
  "delete": "Hapus",
  "copySuccess": "Nota disalin ke papan klip!",
  "bookedDateLabel": "Tanggal Pesan:",
  "deliveryDatePrefix": "Tanggal Pengambilan:",
  "tailorStamp": "Cap Penjahit Resmi",
  "customerDetailsHeading": "Data Pelanggan",
  "measurementsHeading": "Rincian Ukuran",
  "accountSummaryHeading": "Ringkasan Pembayaran",
  "menuTitle": "Menu Azad Master",
  "profileSettings": "Profil & Pengaturan",
  "changeLanguage": "Ganti Bahasa",
  "dataBackup": "Cadangan Cloud & Sinkronisasi",
  "helpSupport": "Panduan & Bantuan",
  "developerInfo": "Info Pengembang",
  "settingsTitle": "Profil & Pengaturan Aplikasi",
  "selectAppLanguage": "Bahasa Aplikasi",
  "allSupportedLanguages": "Semua 22 Bahasa Didukung:",
  "aiVoiceAssistant": "Asisten Suara AI Azad",
  "aiVoiceAssistantSub": "Ucapkan atau ketik ukuran untuk hitungan potong otomatis",
  "appGuide": "Panduan Penggunaan",
  "appGuideSub": "Pencatatan ukuran, scan OCR, pelacakan & WhatsApp",
  "cloudAutoSave": "Simpan Otomatis Cloud (Firebase)",
  "cloudAutoSaveLive": "Aktif & Aman",
  "cloudDatabaseLabel": "Basis Data Cloud:",
  "cloudRecordsLabel": "Data Cloud:",
  "lastSyncedLabel": "Sinkronisasi Terakhir:",
  "syncAllNow": "Sinkronkan Semua Data ke Cloud Sekarang",
  "syncingToCloud": "Menyinkronkan ke cloud...",
  "dataBackupRestore": "Cadangan & Pemulihan Data",
  "recordsCount": "Data",
  "backupData": "Buat Cadangan (JSON)",
  "restoreData": "Pulihkan Data (JSON)",
  "developerCredit": "Pengembang: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "Hak Cipta Dilindungi © 2026 Azad Master",
  "resetAllRecords": "Hapus Semua Nota Ukuran",
  "resetRecordsConfirm": "Apakah Anda yakin ingin menghapus semua data pelanggan?",
  "savedSuccess": "Berhasil disimpan!",
  "cloudSyncSuccess": "Data berhasil disinkronkan ke cloud!",
  "noRecordsToBackup": "Tidak ada data untuk dicadangkan!",
  "backupFileDownloaded": "File cadangan berhasil diunduh!",
  "recordsRestoredSuccess": "Data berhasil dipulihkan!",
  "noValidRecordsFound": "Tidak ada data valid di dalam file.",
  "invalidBackupFile": "File tidak valid. Silakan pilih file JSON yang benar.",
  "needHelpTitle": "Butuh Bantuan? / Kontak",
  "contactWhatsApp": "Hubungi via WhatsApp",
  "contactEmail": "Dukungan Email",
  "appGuideTitle": "Cara Menggunakan Azad Master",
  "guideStep1Title": "1. Catat Ukuran Baru",
  "guideStep1Desc": "Ketuk tombol (+) atau 'Catat Ukuran' untuk memasukkan nama, nomor telepon, ukuran dan tanggal selesai.",
  "guideStep2Title": "2. ✂️ Keunggulan Mode Potong",
  "guideStep2Desc": "Nyalakan Mode Potong di meja kerja untuk melihat angka yang besar dan jelas dari kejauhan.",
  "guideStep3Title": "3. Foto Kertas Ukuran & Pindai AI",
  "guideStep3Desc": "Foto kertas ukuran manual, AI akan langsung mengenali dan mengisi formulir ukuran.",
  "guideStep4Title": "4. Nota Digital WhatsApp & Cloud",
  "guideStep4Desc": "Kirimkan nota rapi ke pelanggan via WhatsApp sekali klik dan simpan semua aman di cloud.",
  "closeGuide": "Paham / Tutup Panduan",
  "privacyModalTitle": "Kebijakan Privasi & Keamanan Data",
  "privacyPolicyP1": "Semua data ukuran, kontak dan catatan kas tersimpan terenkripsi di akun cloud pribadi Anda.",
  "privacyPolicyP2": "Tidak ada pihak lain yang dapat mengakses data jahit Anda. Privasi terjamin sepenuhnya.",
  "closePrivacy": "Setuju & Tutup",
  "secureStorage100": "Penyimpanan Cloud 100% Aman",
  "safeBadge": "Aman",
  "chatbotHeaderTitle": "Asisten AI Azad",
  "chatbotHeaderSub": "Asisten Jahit & Potong Daring",
  "voiceReplyActive": "Balasan Suara Aktif",
  "voiceReplyMuted": "Balasan Suara Bisu",
  "typingInputPlaceholder": "Ketik ukuran atau tanyakan tips menjahit...",
  "detectedMeasurementsHeading": "Ukuran Terdeteksi",
  "confirmAndApplySlip": "Konfirmasi & Terapkan ke Nota",
  "confirmedMeasurement": "Dikonfirmasi",
  "micListeningState": "Mendengarkan... Silakan bicara",
  "micStartState": "Bicara",
  "voiceScreenTitle": "Asisten Suara Azad",
  "voiceScreenSub": "Percakapan Suara Langsung",
  "tapToSpeak": "Ketuk untuk Bicara",
  "listeningVoice": "Mendengarkan...",
  "processingVoice": "Memproses...",
  "botSpeaking": "Membacakan jawaban...",
  "closeVoiceMode": "Keluar dari Mode Suara",
  "browserNoVoice": "Browser ini tidak mendukung pengenalan suara.",
  "chatbotGreeting": "Halo! Saya asisten Azad Master. Anda bisa mengucapkan atau mengetik ukuran (Panjang, Bahu, Lengan, Dada, Pinggang, Bawah, Kerah, Celana). Saya akan merapikan dan mencatatnya ke nota.",
  "quickPrompt1": "Panjang 42, Bahu 18.5, Lengan 23, Dada 38, Bawah 24, Kerah 15.5, Celana 38",
  "quickPrompt2": "Berapa meter kain yang dibutuhkan untuk setelan pria?",
  "quickPrompt3": "Bagaimana rumus potongan kerung lengan dan pundak?",
  "quickPrompt4": "Bagaimana cara memotong lengkungan kerah dengan presisi?",
  "login": "Masuk",
  "codePlaceholder": "Masukkan nomor WhatsApp atau kode...",
  "pinHint": "PIN Default: 123456 (atau kosongkan)",
  "signingIn": "Sedang masuk...",
  "signInWithGoogle": "Masuk Aman dengan Akun Google",
  "openInNewTab": "Buka di Tab Baru",
  "tryRedirectLogin": "Coba Masuk dengan Pengalihan",
  "openInNewWindow": "Buka langsung di jendela baru",
  "secureRecords": "100% Data Aman & Privat",
  "loginPrivacyNotice": "Setiap penjahit masuk dengan akun Google masing-masing dan catatan tetap terlindungi secara privat.",
  "currentDomainLabel": "Domain Saat Ini (Firebase Authorized Domains):",
  "copyDomainBtn": "Salin Domain",
  "copiedDomainMsg": "Disalin!",
  "authorizedDomainTip": "Tambahkan domain ini di Firebase Console > Authentication > Settings > Authorized Domains.",
  "deleteConfirm": "Apakah Anda yakin ingin menghapus nota ini?",
  "deleteSuccess": "Nota pelanggan berhasil dihapus.",
  "saveSuccess": "Nota pelanggan berhasil disimpan.",
  "syncSuccess": "Semua data berhasil disinkronkan ke cloud."
}

# PORTUGUESE (pt)
pt = {
  "title": "AZAD MASTER",
  "subtitle": "Gestão Segura de Alfaiataria e Livro Digital de Corte",
  "appSubtitle": "Registro Digital em Nuvem para Alfaiates Profissionais",
  "defaultMasterTitle": "Mestre Alfaiate",
  "masterNameLabel": "Nome do Alfaiate:",
  "masterPhotoLabel": "Foto do Alfaiate:",
  "masterDefaultName": "Mestre Alfaiate",
  "navHome": "Início",
  "navSettings": "Configurações",
  "navAdd": "Adicionar Medida",
  "searchPlaceholder": "Pesquisar por nome ou telefone...",
  "searchAction": "Pesquisar",
  "clear": "Limpar",
  "recentSearches": "Pesquisas Recentes",
  "clearHistory": "Limpar Histórico",
  "openSlip": "Abrir Ficha",
  "addMeasurementBtn": "Adicionar Medida",
  "photoOcrBtn": "Foto de Ficha / Tecido",
  "cuttingMode": "✂️ Modo Corte",
  "normalMode": "Modo Normal",
  "voiceInput": "Entrada de Voz",
  "chatbot": "Assistente Azad IA",
  "assistant": "Assistente",
  "settings": "Configurações e Perfil",
  "privacy": "Política de Privacidade",
  "logout": "Sair",
  "customerSlipsHeading": "Fichas de Corte dos Clientes:",
  "statusFiltersHeading": "Filtros por Estado do Pedido:",
  "showingCount": "Exibindo:",
  "allFilter": "Todos",
  "statusPending": "Pendente",
  "statusCutting": "Em Corte",
  "statusStitching": "Em Costura",
  "statusReady": "Pronto",
  "statusDelivered": "Entregue",
  "todayDelivery": "Entregas de Hoje:",
  "lateOrders": "Pedidos Atrasados:",
  "totalCustomers": "Total de Clientes",
  "quickStats": "Resumo",
  "recentOrders": "Pedidos Recentes (Visualização Rápida)",
  "recentOrdersCount": "Mais Recentes",
  "show": "Mostrar",
  "hide": "Ocultar",
  "noRecords": "Nenhum registro encontrado.",
  "noCustomerFound": "Nenhum cliente encontrado",
  "noCustomersSaved": "Nenhum cliente salvo ainda",
  "searchHintEmpty": "Tente pesquisar com outro nome ou telefone.",
  "addFirstCustomerHint": "Toque no botão abaixo para adicionar sua primeira ficha.",
  "addFirstCustomer": "Adicionar Primeiro Cliente",
  "tapToAdd": "Toque no botão (+) abaixo para cadastrar nova medida.",
  "tapToAddCustomer": "Toque aqui para adicionar um novo cliente.",
  "addAsNewCustomer": "como Novo Cliente",
  "unnamedCustomer": "Cliente Sem Nome",
  "date": "Data:",
  "delivery": "Entrega:",
  "balance": "Saldo:",
  "cleared": "Quitado",
  "syncing": "Sincronizando...",
  "cloudSynced": "Salvo na Nuvem com Segurança",
  "syncNow": "Sincronizar Agora",
  "cloudSyncError": "Erro de Nuvem",
  "online": "Online",
  "selectPhotoSource": "Selecionar Foto da Ficha ou Tecido",
  "camera": "Câmera",
  "gallery": "Galeria",
  "fillManually": "Preencher Manualmente",
  "uploadPhotoTitle": "Foto da Ficha em Papel:",
  "galleryBtn": "🖼️ Galeria",
  "cameraBtn": "📸 Câmera",
  "removePhoto": "Remover Foto",
  "extractingOcr": "IA extraindo medidas da foto...",
  "addSlip": "Adicionar Nova Ficha de Medida",
  "editSlip": "Editar Ficha de Medida",
  "customerName": "Nome do Cliente *",
  "phoneNumber": "WhatsApp (Opcional)",
  "countryCodeLabel": "Código do País",
  "suitTypeLabel": "Tipo de Traje",
  "suitGents": "Terno / Traje Masculino (Camisa e Calça)",
  "suitKurtaPajama": "Kurta e Pijama",
  "suitSafari": "Traje Safari",
  "suitWaistcoat": "Colete",
  "suitSherwani": "Sherwani de Gala",
  "deliveryDateLabel": "Data de Entrega",
  "quickToday": "Hoje",
  "quickTomorrow": "Amanhã",
  "quick3Days": "3 Dias",
  "quick1Week": "1 Semana",
  "quick10Days": "10 Dias",
  "orderStatusLabel": "Status do Pedido:",
  "orderLockedNotice": "Este pedido foi marcado como Entregue e está bloqueado. Deseja desbloquear para alterar o status?",
  "orderLockedBadge": "🔒 Bloqueado",
  "orderUnlockedBadge": "🔓 Desbloqueado",
  "dueTodayBadge": "⚡ Entrega Hoje",
  "lateOrderBadge": "⚠️ Atrasado",
  "upcomingBadge": "📅 Próximo",
  "lengthLabel": "Comprimento",
  "shoulderLabel": "Ombro a Ombro",
  "sleevesLabel": "Manga",
  "chestLabel": "Tórax / Busto",
  "waistLabel": "Cintura",
  "daamanLabel": "Barra / Roda",
  "collarLabel": "Colarinho",
  "shalwarLabel": "Comprimento da Calça",
  "panchaLabel": "Boca da Calça",
  "pocketLabel": "Bolso",
  "specialNotesLabel": "Instruções Especiais / Notas",
  "notesPlaceholder": "Ex: Barra arredondada, gola padre, pesponto simples...",
  "billingHeading": "Valores e Pagamento:",
  "totalAmountLabel": "Valor Total",
  "advanceAmountLabel": "Sinal Recebido",
  "balanceAmountLabel": "Saldo Devedor",
  "fullyPaidBadge": "✓ Totalmente Quitado",
  "balanceDueBadge": "⏳ Saldo Pendente",
  "saveDone": "Salvar e Concluir",
  "saveClose": "Salvar e Fechar",
  "cancel": "Cancelar",
  "close": "Concluído / Fechar",
  "back": "Voltar",
  "digitalSlip": "Ficha Digital de Corte",
  "editMode": "Editar / Modo Corte",
  "sendWhatsapp": "Enviar Ficha por WhatsApp",
  "copySlip": "Copiar Ficha",
  "printSlip": "Imprimir",
  "delete": "Excluir",
  "copySuccess": "Ficha copiada para a área de transferência!",
  "bookedDateLabel": "Data do Pedido:",
  "deliveryDatePrefix": "Data de Entrega:",
  "tailorStamp": "Carimbo Mestre Alfaiate",
  "customerDetailsHeading": "Dados do Cliente",
  "measurementsHeading": "Detalhes das Medidas",
  "accountSummaryHeading": "Resumo Financeiro",
  "menuTitle": "Menu Azad Master",
  "profileSettings": "Perfil e Configurações",
  "changeLanguage": "Mudar Idioma",
  "dataBackup": "Backup e Sincronização em Nuvem",
  "helpSupport": "Guia de Uso e Suporte",
  "developerInfo": "Informações do Desenvolvedor",
  "settingsTitle": "Perfil e Configurações do App",
  "selectAppLanguage": "Idioma do App",
  "allSupportedLanguages": "Todos os 22 Idiomas Suportados:",
  "aiVoiceAssistant": "Assistente de Voz Azad IA",
  "aiVoiceAssistantSub": "Fale ou digite as medidas para cálculo automático de corte",
  "appGuide": "Guia de Uso",
  "appGuideSub": "Registro de medidas, leitura OCR, rastreamento e WhatsApp",
  "cloudAutoSave": "Salvamento Automático em Nuvem (Firebase)",
  "cloudAutoSaveLive": "Ativo e Protegido",
  "cloudDatabaseLabel": "Banco de Dados em Nuvem:",
  "cloudRecordsLabel": "Registros em Nuvem:",
  "lastSyncedLabel": "Última Sincronização:",
  "syncAllNow": "Sincronizar Todos os Dados com a Nuvem Agora",
  "syncingToCloud": "Sincronizando com a nuvem...",
  "dataBackupRestore": "Backup e Restauração de Dados",
  "recordsCount": "Registros",
  "backupData": "Gerar Arquivo de Backup (JSON)",
  "restoreData": "Restaurar Dados (JSON)",
  "developerCredit": "Desenvolvido por: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "Todos os direitos reservados © 2026 Azad Master",
  "resetAllRecords": "Apagar Todas as Fichas de Corte",
  "resetRecordsConfirm": "Tem certeza de que deseja apagar todos os registros de clientes?",
  "savedSuccess": "Salvo com sucesso!",
  "cloudSyncSuccess": "Registros sincronizados com sucesso na nuvem!",
  "noRecordsToBackup": "Nenhum registro para backup!",
  "backupFileDownloaded": "Arquivo de backup baixado com sucesso!",
  "recordsRestoredSuccess": "Registros restaurados com sucesso!",
  "noValidRecordsFound": "Nenhum registro válido encontrado no arquivo.",
  "invalidBackupFile": "Arquivo inválido. Selecione um arquivo JSON correto.",
  "needHelpTitle": "Precisa de Ajuda? / Suporte",
  "contactWhatsApp": "Contatar via WhatsApp",
  "contactEmail": "Suporte por E-mail",
  "appGuideTitle": "Como Usar o Azad Master",
  "guideStep1Title": "1. Cadastrar Nova Medida",
  "guideStep1Desc": "Toque em (+) ou 'Adicionar Medida' para registrar nome, telefone, medidas e prazo.",
  "guideStep2Title": "2. ✂️ O Diferencial do Modo Corte",
  "guideStep2Desc": "Na mesa de corte, ative o Modo Corte para ver números grandes e bem visíveis à distância.",
  "guideStep3Title": "3. Foto da Ficha e Leitura por IA",
  "guideStep3Desc": "Fotografe a ficha de papel antiga; a IA identificará e preencherá as medidas no formulário.",
  "guideStep4Title": "4. Ficha Digital WhatsApp e Nuvem",
  "guideStep4Desc": "Envie a ficha no WhatsApp do cliente com um clique e tenha tudo armazenado em nuvem.",
  "closeGuide": "Entendi / Fechar Guia",
  "privacyModalTitle": "Privacidade e Proteção de Dados",
  "privacyPolicyP1": "Todas as medidas e contas de clientes são criptografadas e salvas na sua conta segura em nuvem.",
  "privacyPolicyP2": "Nenhum terceiro tem acesso aos seus dados de alfaiataria. Sigilo absoluto.",
  "closePrivacy": "Concordo e Fechar",
  "secureStorage100": "Armazenamento em Nuvem 100% Seguro",
  "safeBadge": "Seguro",
  "chatbotHeaderTitle": "Assistente Azad IA",
  "chatbotHeaderSub": "Assistente Virtual de Corte e Alfaiataria",
  "voiceReplyActive": "Resposta por Voz Ativada",
  "voiceReplyMuted": "Resposta por Voz Silenciada",
  "typingInputPlaceholder": "Digite medidas ou faça uma pergunta de costura...",
  "detectedMeasurementsHeading": "Medidas Detectadas",
  "confirmAndApplySlip": "Confirmar e Aplicar na Ficha",
  "confirmedMeasurement": "Confirmado",
  "micListeningState": "Ouvindo... Pode falar",
  "micStartState": "Falar",
  "voiceScreenTitle": "Assistente de Voz Azad",
  "voiceScreenSub": "Conversa de Voz em Tempo Real",
  "tapToSpeak": "Toque para Falar",
  "listeningVoice": "Ouvindo...",
  "processingVoice": "Processando...",
  "botSpeaking": "Reproduzindo resposta...",
  "closeVoiceMode": "Sair do Modo Voz",
  "browserNoVoice": "Reconhecimento de voz não suportado neste navegador.",
  "chatbotGreeting": "Olá! Sou o assistente do Azad Master. Você pode falar ou digitar as medidas (Comprimento, Ombro, Manga, Tórax, Cintura, Barra, Colarinho, Calça). Eu vou organizá-las para você.",
  "quickPrompt1": "Comprimento 42, Ombro 18.5, Manga 23, Tórax 38, Barra 24, Colarinho 15.5, Calça 38",
  "quickPrompt2": "Quantos metros de tecido são necessários para um terno masculino?",
  "quickPrompt3": "Qual a fórmula para cava e caimento do ombro?",
  "quickPrompt4": "Como cortar o decote do colarinho com perfeição?",
  "login": "Entrar",
  "codePlaceholder": "Digite o WhatsApp ou Código...",
  "pinHint": "PIN Padrão: 123456 (ou deixe em branco)",
  "signingIn": "Entrando...",
  "signInWithGoogle": "Acesso Seguro com Conta Google",
  "openInNewTab": "Abrir em Nova Aba",
  "tryRedirectLogin": "Tentar Login com Redirecionamento",
  "openInNewWindow": "Abrir diretamente em nova janela",
  "secureRecords": "Registros 100% Seguros e Privados",
  "loginPrivacyNotice": "Cada alfaiate faz login com sua conta Google própria e seus dados permanecem estritamente confidenciais.",
  "currentDomainLabel": "Domínio Atual (Firebase Authorized Domains):",
  "copyDomainBtn": "Copiar Domínio",
  "copiedDomainMsg": "Copiado!",
  "authorizedDomainTip": "Adicione este domínio em Firebase Console > Authentication > Settings > Authorized Domains.",
  "deleteConfirm": "Tem certeza de que deseja excluir esta ficha?",
  "deleteSuccess": "Ficha do cliente excluída com sucesso.",
  "saveSuccess": "Ficha do cliente salva com sucesso.",
  "syncSuccess": "Todos os registros foram sincronizados com a nuvem."
}

# THAI (th)
th = {
  "title": "อาซาด มาสเตอร์",
  "subtitle": "ระบบจัดการร้านตัดเสื้อและสมุดจดไซส์ดิจิทัลที่ปลอดภัย",
  "appSubtitle": "สมุดบัญชีคลาวด์ดิจิทัลสำหรับช่างตัดเสื้อมืออาชีพ",
  "defaultMasterTitle": "ช่างตัดเสื้อผู้เชี่ยวชาญ",
  "masterNameLabel": "ชื่อช่างตัดเสื้อ:",
  "masterPhotoLabel": "รูปถ่ายช่างตัดเสื้อ:",
  "masterDefaultName": "ช่างตัดเสื้อผู้เชี่ยวชาญ",
  "navHome": "หน้าหลัก",
  "navSettings": "ตั้งค่า",
  "navAdd": "บันทึกขนาด",
  "searchPlaceholder": "ค้นหาชื่อลูกค้าหรือเบอร์โทรศัพท์...",
  "searchAction": "ค้นหา",
  "clear": "ล้าง",
  "recentSearches": "การค้นหาล่าสุด",
  "clearHistory": "ล้างประวัติ",
  "openSlip": "เปิดใบสั่งงาน",
  "addMeasurementBtn": "บันทึกขนาด",
  "photoOcrBtn": "ถ่ายรูปใบจด / ผ้า",
  "cuttingMode": "✂️ โหมดตัดผ้า",
  "normalMode": "โหมดปกติ",
  "voiceInput": "บันทึกด้วยเสียง",
  "chatbot": "ผู้ช่วย AI อาซาด",
  "assistant": "ผู้ช่วย",
  "settings": "ตั้งค่าและโปรไฟล์",
  "privacy": "นโยบายความเป็นส่วนตัว",
  "logout": "ออกจากระบบ",
  "customerSlipsHeading": "ใบวัดตัวตัดเสื้อของลูกค้า:",
  "statusFiltersHeading": "ตัวกรองสถานะคำสั่งซื้อ:",
  "showingCount": "แสดง:",
  "allFilter": "ทั้งหมด",
  "statusPending": "รอดำเนินการ",
  "statusCutting": "กำลังตัด",
  "statusStitching": "กำลังเย็บ",
  "statusReady": "พร้อมส่งมอบ",
  "statusDelivered": "ส่งมอบแล้ว",
  "todayDelivery": "กำหนดส่งวันนี้:",
  "lateOrders": "งานที่เลยกำหนด:",
  "totalCustomers": "ลูกค้าทั้งหมด",
  "quickStats": "ภาพรวม",
  "recentOrders": "คำสั่งซื้อล่าสุด (ดูด่วน)",
  "recentOrdersCount": "ล่าสุด",
  "show": "แสดง",
  "hide": "ซ่อน",
  "noRecords": "ไม่พบข้อมูลที่บันทึกไว้",
  "noCustomerFound": "ไม่พบข้อมูลลูกค้า",
  "noCustomersSaved": "ยังไม่มีข้อมูลลูกค้าที่บันทึกไว้",
  "searchHintEmpty": "ลองค้นหาด้วยชื่อหรือหมายเลขโทรศัพท์อื่น",
  "addFirstCustomerHint": "แตะปุ่มด้านล่างเพื่อเพิ่มใบวัดตัวแรกของคุณ",
  "addFirstCustomer": "เพิ่มลูกค้าคนแรก",
  "tapToAdd": "แตะปุ่ม (+) ด้านล่างเพื่อบันทึกขนาดใหม่",
  "tapToAddCustomer": "แตะที่นี่เพื่อเพิ่มลูกค้าใหม่",
  "addAsNewCustomer": "เป็นลูกค้าใหม่",
  "unnamedCustomer": "ลูกค้าไม่ได้ระบุชื่อ",
  "date": "วันที่:",
  "delivery": "กำหนดส่ง:",
  "balance": "คงเหลือ:",
  "cleared": "ชำระครบแล้ว",
  "syncing": "กำลังซิงค์...",
  "cloudSynced": "บันทึกบนคลาวด์ปลอดภัย",
  "syncNow": "ซิงค์ทันที",
  "cloudSyncError": "ข้อผิดพลาดระบบคลาวด์",
  "online": "ออนไลน์",
  "selectPhotoSource": "เลือกรูปใบจดขนาดหรือรูปผ้า",
  "camera": "กล้องถ่ายรูป",
  "gallery": "แกลเลอรี",
  "fillManually": "กรอกข้อมูลด้วยตนเอง",
  "uploadPhotoTitle": "รูปถ่ายใบจดขนาดกระดาษ:",
  "galleryBtn": "🖼️ แกลเลอรี",
  "cameraBtn": "📸 กล้อง",
  "removePhoto": "ลบรูปภาพ",
  "extractingOcr": "AI กำลังอ่านตัวเลขขนาดจากรูปภาพ...",
  "addSlip": "เพิ่มใบวัดตัวใหม่",
  "editSlip": "แก้ไขใบวัดตัว",
  "customerName": "ชื่อลูกค้า *",
  "phoneNumber": "เบอร์ WhatsApp / โทรศัพท์ (ไม่บังคับ)",
  "countryCodeLabel": "รหัสประเทศ",
  "suitTypeLabel": "ประเภทชุด",
  "suitGents": "ชุดบุรุษ (เสื้อและกางเกง)",
  "suitKurtaPajama": "ชุดเคอร์ตาและกางเกง",
  "suitSafari": "ชุดซาฟารี",
  "suitWaistcoat": "เสื้อกั๊ก",
  "suitSherwani": "ชุดเชอร์วานีทางการ",
  "deliveryDateLabel": "กำหนดส่งมอบงาน",
  "quickToday": "วันนี้",
  "quickTomorrow": "พรุ่งนี้",
  "quick3Days": "3 วัน",
  "quick1Week": "1 สัปดาห์",
  "quick10Days": "10 วัน",
  "orderStatusLabel": "สถานะงาน:",
  "orderLockedNotice": "คำสั่งซื้อนี้ถูกทำเครื่องหมายว่าส่งมอบแล้วและถูกล็อค ต้องการปลดล็อคเพื่อเปลี่ยนสถานะหรือไม่?",
  "orderLockedBadge": "🔒 ล็อคแล้ว",
  "orderUnlockedBadge": "🔓 แก้ไขได้",
  "dueTodayBadge": "⚡ กำหนดส่งวันนี้",
  "lateOrderBadge": "⚠️ เลยกำหนด",
  "upcomingBadge": "📅 เร็วๆ นี้",
  "lengthLabel": "ความยาวเสื้อ",
  "shoulderLabel": "ไหล่กว้าง",
  "sleevesLabel": "ความยาวแขน",
  "chestLabel": "รอบอก",
  "waistLabel": "รอบเอว",
  "daamanLabel": "ความกว้างชายเสื้อ",
  "collarLabel": "รอบคอ / ปก",
  "shalwarLabel": "ความยาวกางเกง",
  "panchaLabel": "ปลายขากางเกง",
  "pocketLabel": "กระเป๋า",
  "specialNotesLabel": "หมายเหตุและคำสั่งพิเศษ",
  "notesPlaceholder": "เช่น ชายโค้ง, คอจีน, เดินตะเข็บเดี่ยว...",
  "billingHeading": "ค่าตัดเย็บและการชำระเงิน:",
  "totalAmountLabel": "ยอดรวมทั้งหมด",
  "advanceAmountLabel": "เงินมัดจำล่วงหน้า",
  "balanceAmountLabel": "ยอดค้างชำระ",
  "fullyPaidBadge": "✓ ชำระครบถ้วนแล้ว",
  "balanceDueBadge": "⏳ มียอดค้างชำระ",
  "saveDone": "บันทึกและเสร็จสิ้น",
  "saveClose": "บันทึกและปิด",
  "cancel": "ยกเลิก",
  "close": "เสร็จสิ้น / ปิด",
  "back": "ย้อนกลับ",
  "digitalSlip": "ใบวัดตัวตัดเสื้อดิจิทัล",
  "editMode": "แก้ไข / โหมดตัดผ้า",
  "sendWhatsapp": "ส่งใบงานผ่าน WhatsApp",
  "copySlip": "คัดลอกใบงาน",
  "printSlip": "พิมพ์",
  "delete": "ลบ",
  "copySuccess": "คัดลอกใบงานไปยังคลิปบอร์ดแล้ว!",
  "bookedDateLabel": "วันที่สั่งตัด:",
  "deliveryDatePrefix": "วันนัดรับสินค้า:",
  "tailorStamp": "ตราประทับช่างตัดเสื้อ",
  "customerDetailsHeading": "ข้อมูลลูกค้า",
  "measurementsHeading": "รายละเอียดขนาด",
  "accountSummaryHeading": "สรุปยอดชำระ",
  "menuTitle": "เมนู อาซาด มาสเตอร์",
  "profileSettings": "โปรไฟล์และการตั้งค่า",
  "changeLanguage": "เปลี่ยนภาษา",
  "dataBackup": "สำรองข้อมูลบนคลาวด์และซิงค์",
  "helpSupport": "คู่มือการใช้งานและความช่วยเหลือ",
  "developerInfo": "ข้อมูลผู้พัฒนา",
  "settingsTitle": "โปรไฟล์และการตั้งค่าแอป",
  "selectAppLanguage": "ภาษาของแอป",
  "allSupportedLanguages": "รองรับครบทั้ง 22 ภาษา:",
  "aiVoiceAssistant": "ผู้ช่วยเสียง AI อาซาด",
  "aiVoiceAssistantSub": "พูดหรือพิมพ์ขนาด เพื่อคำนวณการตัดเย็บอัตโนมัติ",
  "appGuide": "คู่มือการใช้งาน",
  "appGuideSub": "การบันทึกขนาด, สแกนรูปภาพ, ติดตามสถานะ และส่ง WhatsApp",
  "cloudAutoSave": "บันทึกคลาวด์อัตโนมัติ (Firebase)",
  "cloudAutoSaveLive": "ทำงานอยู่และปลอดภัย",
  "cloudDatabaseLabel": "ฐานข้อมูลคลาวด์:",
  "cloudRecordsLabel": "จำนวนรายการคลาวด์:",
  "lastSyncedLabel": "ซิงค์ล่าสุดเมื่อ:",
  "syncAllNow": "ซิงค์ข้อมูลทั้งหมดขึ้นคลาวด์ทันที",
  "syncingToCloud": "กำลังซิงค์ข้อมูลไปยังคลาวด์...",
  "dataBackupRestore": "สำรองและกู้คืนข้อมูล",
  "recordsCount": "รายการ",
  "backupData": "สร้างไฟล์สำรองข้อมูล (JSON)",
  "restoreData": "กู้คืนข้อมูล (JSON)",
  "developerCredit": "พัฒนาโดย: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "สงวนลิขสิทธิ์ © 2026 อาซาด มาสเตอร์",
  "resetAllRecords": "ลบใบงานวัดตัวทั้งหมด",
  "resetRecordsConfirm": "คุณแน่ใจหรือไม่ว่าต้องการลบข้อมูลลูกค้าทั้งหมด?",
  "savedSuccess": "บันทึกเรียบร้อยแล้ว!",
  "cloudSyncSuccess": "ซิงค์ข้อมูลไปยังคลาวด์สำเร็จแล้ว!",
  "noRecordsToBackup": "ไม่มีข้อมูลที่จะสำรอง!",
  "backupFileDownloaded": "ดาวน์โหลดไฟล์สำรองข้อมูลสำเร็จแล้ว!",
  "recordsRestoredSuccess": "กู้คืนข้อมูลสำเร็จแล้ว!",
  "noValidRecordsFound": "ไม่พบข้อมูลที่ถูกต้องในไฟล์",
  "invalidBackupFile": "ไฟล์ไม่ถูกต้อง กรุณาเลือกไฟล์ JSON ที่ถูกต้อง",
  "needHelpTitle": "ต้องการความช่วยเหลือ? / ติดต่อเรา",
  "contactWhatsApp": "ติดต่อทาง WhatsApp",
  "contactEmail": "ติดต่อทางอีเมล",
  "appGuideTitle": "วิธีใช้งาน อาซาด มาสเตอร์",
  "guideStep1Title": "1. บันทึกขนาดใหม่",
  "guideStep1Desc": "แตะปุ่ม (+) หรือ 'บันทึกขนาด' เพื่อกรอกชื่อลูกค้า เบอร์โทร สัดส่วน และวันนัดรับ",
  "guideStep2Title": "2. ✂️ จุดเด่นของโหมดตัดผ้า",
  "guideStep2Desc": "เปิดโหมดตัดผ้าบนโต๊ะทำงาน ตัวเลขจะแสดงขนาดใหญ่ชัดเจน มองเห็นได้ง่ายแม้ทำงานระยะไกล",
  "guideStep3Title": "3. ถ่ายรูปใบจดขนาดและสแกนด้วย AI",
  "guideStep3Desc": "ถ่ายภาพใบจดขนาดกระดาษดั้งเดิม AI จะอ่านค่าและกรอกขนาดให้โดยอัตโนมัติ",
  "guideStep4Title": "4. ส่งใบงาน WhatsApp ดิจิทัลและคลาวด์",
  "guideStep4Desc": "ส่งใบงานที่เรียบร้อยให้ลูกค้าทาง WhatsApp ในคลิกเดียว พร้อมจัดเก็บบนคลาวด์ปลอดภัย",
  "closeGuide": "เข้าใจแล้ว / ปิดคู่มือ",
  "privacyModalTitle": "นโยบายความเป็นส่วนตัวและความปลอดภัยของข้อมูล",
  "privacyPolicyP1": "ขนาด สัดส่วน ข้อมูลติดต่อ และบัญชีของลูกค้าคุณจะถูกเข้ารหัสและจัดเก็บบนบัญชีคลาวด์ส่วนตัวอย่างปลอดภัย",
  "privacyPolicyP2": "ไม่มีบุคคลภายนอกเข้าถึงข้อมูลการตัดเย็บของคุณได้ ข้อมูลทั้งหมดเป็นส่วนตัวอย่างแท้จริง",
  "closePrivacy": "ยอมรับและปิด",
  "secureStorage100": "จัดเก็บบนคลาวด์ปลอดภัย 100%",
  "safeBadge": "ปลอดภัย",
  "chatbotHeaderTitle": "ผู้ช่วย AI อาซาด",
  "chatbotHeaderSub": "ผู้ช่วยช่างตัดเสื้อและออกแบบออนไลน์",
  "voiceReplyActive": "เปิดการตอบกลับด้วยเสียง",
  "voiceReplyMuted": "ปิดเสียงตอบกลับ",
  "typingInputPlaceholder": "พิมพ์ขนาด หรือถามคำถามเกี่ยวกับการตัดเย็บ...",
  "detectedMeasurementsHeading": "ขนาดที่ตรวจพบ",
  "confirmAndApplySlip": "ยืนยันและนำไปใส่ในใบงาน",
  "confirmedMeasurement": "ยืนยันแล้ว",
  "micListeningState": "กำลังฟังอยู่... เชิญพูดได้เลย",
  "micStartState": "พูด",
  "voiceScreenTitle": "ผู้ช่วยเสียงอาซาด",
  "voiceScreenSub": "สนทนาด้วยเสียงสด",
  "tapToSpeak": "แตะเพื่อพูด",
  "listeningVoice": "กำลังฟัง...",
  "processingVoice": "กำลังประมวลผล...",
  "botSpeaking": "กำลังอ่านคำตอบ...",
  "closeVoiceMode": "ปิดโหมดเสียง",
  "browserNoVoice": "เบราว์เซอร์นี้ไม่รองรับการจดจำเสียง",
  "chatbotGreeting": "สวัสดีครับ! ผมคือผู้ช่วย อาซาด มาสเตอร์ คุณสามารถพูดหรือพิมพ์ขนาด (ความยาว, ไหล่, แขน, อก, เอว, ชายเสื้อ, คอ, กางเกง) ผมจะช่วยจัดหมวดหมู่และบันทึกลงในใบงานให้ครับ",
  "quickPrompt1": "ความยาว 42, ไหล่ 18.5, แขน 23, อก 38, ชาย 24, คอ 15.5, กางเกง 38",
  "quickPrompt2": "ตัดชุดผู้ชาย 1 ชุด ต้องใช้ผ้ากี่เมตร?",
  "quickPrompt3": "สูตรคำนวณวงแขนและความลาดไหล่ที่แม่นยำคืออะไร?",
  "quickPrompt4": "วิธีตัดเว้าคอเสื้อให้ได้รูปสวยงามทำอย่างไร?",
  "login": "เข้าสู่ระบบ",
  "codePlaceholder": "กรอกเบอร์ WhatsApp หรือรหัส...",
  "pinHint": "PIN เริ่มต้น: 123456 (หรือเว้นว่างเพื่อเข้าสู่ระบบ)",
  "signingIn": "กำลังเข้าสู่ระบบ...",
  "signInWithGoogle": "เข้าสู่ระบบอย่างปลอดภัยด้วย Google",
  "openInNewTab": "เปิดในแท็บใหม่",
  "tryRedirectLogin": "ลองเข้าสู่ระบบแบบเปลี่ยนหน้า",
  "openInNewWindow": "เปิดในหน้าต่างใหม่โดยตรง",
  "secureRecords": "ข้อมูลปลอดภัยและเป็นส่วนตัว 100%",
  "loginPrivacyNotice": "ช่างตัดเสื้อแต่ละท่านเข้าสู่ระบบด้วยบัญชี Google ส่วนตัว ข้อมูลลูกค้าจะถูกเก็บเป็นความลับสูงสุด",
  "currentDomainLabel": "โดเมนปัจจุบัน (Firebase Authorized Domains):",
  "copyDomainBtn": "คัดลอกโดเมน",
  "copiedDomainMsg": "คัดลอกแล้ว!",
  "authorizedDomainTip": "โปรดเพิ่มโดเมนนี้ใน Firebase Console > Authentication > Settings > Authorized Domains",
  "deleteConfirm": "คุณแน่ใจหรือไม่ว่าต้องการลบใบงานนี้?",
  "deleteSuccess": "ลบใบงานลูกค้าเรียบร้อยแล้ว",
  "saveSuccess": "บันทึกใบงานลูกค้าเรียบร้อยแล้ว",
  "syncSuccess": "ซิงค์ข้อมูลทั้งหมดไปยังคลาวด์แล้ว"
}

# ENGLISH (en)
import json
import os
_base_dir = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(_base_dir, 'base_en.json'), 'r', encoding='utf-8') as f:
    en = json.load(f)

print("Part 3: it, ru, zh, ja, ko, ms, id, pt, th, en ready!")
