#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# PART 2: Hindi, Punjabi, Bengali, Turkish, Spanish, French, German

from langs_part1 import ur

# HINDI (hi)
hi = {
  "title": "आज़ाद मास्टर",
  "subtitle": "सुरक्षित टेलरिंग प्रबंधन व डिजिटल कटिंग रजिस्टर",
  "appSubtitle": "प्रोफेशनल दर्जी डिजिटल क्लाउड रजिस्टर",
  "defaultMasterTitle": "मास्टर जी",
  "masterNameLabel": "मास्टर का नाम:",
  "masterPhotoLabel": "मास्टर फोटो लगाएं:",
  "masterDefaultName": "मास्टर जी",
  "navHome": "होम",
  "navSettings": "सेटिंग्स",
  "navAdd": "नाप दर्ज करें",
  "searchPlaceholder": "ग्राहक का नाम या मोबाइल नंबर खोजें...",
  "searchAction": "खोजें",
  "clear": "साफ़ करें",
  "recentSearches": "हालिया खोज",
  "clearHistory": "इतिहास साफ़ करें",
  "openSlip": "स्लिप खोलें",
  "addMeasurementBtn": "नाप दर्ज करें",
  "photoOcrBtn": "पर्ची / कपड़ा फोटो",
  "cuttingMode": "✂️ कटिंग मोड",
  "normalMode": "सामान्य मोड",
  "voiceInput": "आवाज़ से दर्ज करें",
  "chatbot": "आज़ाद मास्टर असिस्टेंट",
  "assistant": "असिस्टेंट",
  "settings": "सेटिंग्स व प्रोफ़ाइल",
  "privacy": "गोपनीयता नीति",
  "logout": "लॉग आउट",
  "customerSlipsHeading": "ग्राहकों की कटिंग स्लिप्स:",
  "statusFiltersHeading": "ऑर्डर स्थिति फ़िल्टर:",
  "showingCount": "प्रदर्शित:",
  "allFilter": "सभी",
  "statusPending": "लंबित",
  "statusCutting": "कटिंग",
  "statusStitching": "सिलाई जारी",
  "statusReady": "तैयार है",
  "statusDelivered": "सुपुर्द किया गया",
  "todayDelivery": "आज की डिलीवरी:",
  "lateOrders": "देरी वाले ऑर्डर:",
  "totalCustomers": "कुल ग्राहक",
  "quickStats": "अवलोकन",
  "recentOrders": "हालिया ऑर्डर (त्वरित दृश्य)",
  "recentOrdersCount": "नवीनतम",
  "show": "दिखाएं",
  "hide": "छिपाएं",
  "noRecords": "कोई रिकॉर्ड नहीं मिला।",
  "noCustomerFound": "कोई ग्राहक नहीं मिला",
  "noCustomersSaved": "अभी तक कोई ग्राहक सहेजा नहीं गया है",
  "searchHintEmpty": "किसी अन्य नाम या फोन नंबर से खोजें।",
  "addFirstCustomerHint": "पहला ग्राहक जोड़ने के लिए नीचे दिए गए बटन पर टैप करें।",
  "addFirstCustomer": "पहला ग्राहक जोड़ें",
  "tapToAdd": "नया नाप दर्ज करने के लिए नीचे (+) बटन पर टैप करें।",
  "tapToAddCustomer": "नया ग्राहक जोड़ने के लिए यहाँ टैप करें।",
  "addAsNewCustomer": "नए ग्राहक के रूप में",
  "unnamedCustomer": "अनाम ग्राहक",
  "date": "दिनांक:",
  "delivery": "डिलीवरी:",
  "balance": "बाकी:",
  "cleared": "पूर्ण भुगतान",
  "syncing": "सिंक हो रहा है...",
  "cloudSynced": "क्लाउड पर सुरक्षित",
  "syncNow": "अभी सिंक करें",
  "cloudSyncError": "क्लाउड त्रुटि",
  "online": "ऑनलाइन",
  "selectPhotoSource": "पर्ची या कपड़े की फोटो चुनें",
  "camera": "कैमरा",
  "gallery": "गैलरी",
  "fillManually": "मैन्युअल रूप से भरें",
  "uploadPhotoTitle": "कागज़ी पर्ची की फोटो:",
  "galleryBtn": "🖼️ गैलरी",
  "cameraBtn": "📸 कैमरा",
  "removePhoto": "फोटो हटाएं",
  "extractingOcr": "फोटो से नाप निकाला जा रहा है...",
  "addSlip": "नया नाप स्लिप जोड़ें",
  "editSlip": "नाप स्लिप संपादित करें",
  "customerName": "ग्राहक का नाम *",
  "phoneNumber": "व्हाट्सएप नंबर (वैकल्पिक)",
  "countryCodeLabel": "कंट्री कोड",
  "suitTypeLabel": "सूट का प्रकार",
  "suitGents": "जेंट्स सूट (सलवार कमीज)",
  "suitKurtaPajama": "कुर्ता पाजामा",
  "suitSafari": "सफारी सूट",
  "suitWaistcoat": "वास्कट / बंडी",
  "suitSherwani": "शेरवानी",
  "deliveryDateLabel": "डिलीवरी की तारीख",
  "quickToday": "आज",
  "quickTomorrow": "कल",
  "quick3Days": "3 दिन",
  "quick1Week": "1 हफ़्ता",
  "quick10Days": "10 दिन",
  "orderStatusLabel": "ऑर्डर स्थिति:",
  "orderLockedNotice": "यह ऑर्डर डिलीवर हो चुका है और लॉक है। क्या आप इसे अनलॉक करके स्थिति बदलना चाहते हैं?",
  "orderLockedBadge": "🔒 लॉक किया गया",
  "orderUnlockedBadge": "🔓 अनलॉक",
  "dueTodayBadge": "⚡ आज डिलीवरी",
  "lateOrderBadge": "⚠️ लेट ऑर्डर",
  "upcomingBadge": "📅 आगामी",
  "lengthLabel": "लंबाई",
  "shoulderLabel": "तीरा / शोल्डर",
  "sleevesLabel": "बाज़ू / आस्तीन",
  "chestLabel": "सीना / चेस्ट",
  "waistLabel": "कमर",
  "daamanLabel": "दामन / घेरा",
  "collarLabel": "कॉलर / बैन",
  "shalwarLabel": "सलवार / पैंट",
  "panchaLabel": "पाँचा / मोहरी",
  "pocketLabel": "जेब",
  "specialNotesLabel": "विशेष निर्देश / नोट",
  "notesPlaceholder": "जैसे: गोल दामन, बैन कॉलर, सिंगल सिलाई...",
  "billingHeading": "सिलाई बिल व खाता:",
  "totalAmountLabel": "कुल राशि",
  "advanceAmountLabel": "अग्रिम प्राप्त (एडवांस)",
  "balanceAmountLabel": "बकाया राशि",
  "fullyPaidBadge": "✓ पूर्ण भुगतान",
  "balanceDueBadge": "⏳ बकाया देय",
  "saveDone": "सुरक्षित करें और पूरा",
  "saveClose": "सहेजें और बंद करें",
  "cancel": "रद्द करें",
  "close": "पूर्ण / बंद करें",
  "back": "वापस",
  "digitalSlip": "डिजिटल कटिंग स्लिप",
  "editMode": "संपादन / कटिंग मोड",
  "sendWhatsapp": "व्हाट्सएप पर स्लिप भेजें",
  "copySlip": "स्लिप कॉपी करें",
  "printSlip": "प्रिंट निकालें",
  "delete": "हटाएं",
  "copySuccess": "स्लिप क्लिपबोर्ड पर कॉपी हो गई!",
  "bookedDateLabel": "बुकिंग:",
  "deliveryDatePrefix": "डिलीवरी तारीख:",
  "tailorStamp": "मास्टर टेलर मोहर",
  "customerDetailsHeading": "ग्राहक विवरण",
  "measurementsHeading": "नाप का विवरण",
  "accountSummaryHeading": "बिल सारांश",
  "menuTitle": "आज़ाद मास्टर मेनू",
  "profileSettings": "प्रोफ़ाइल व सेटिंग्स",
  "changeLanguage": "भाषा बदलें",
  "dataBackup": "क्लाउड बैकअप व सिंक",
  "helpSupport": "उपयोग गाइड व सहायता",
  "developerInfo": "डेवलपर जानकारी",
  "settingsTitle": "प्रोफ़ाइल व ऐप सेटिंग्स",
  "selectAppLanguage": "ऐप की भाषा",
  "allSupportedLanguages": "सभी 22 समर्थित भाषाएं:",
  "aiVoiceAssistant": "आज़ाद एआई वॉयस असिस्टेंट",
  "aiVoiceAssistantSub": "नाप बोलें या लिखें, स्वचालित कटिंग गणना",
  "appGuide": "उपयोग करने का तरीका (गाइड)",
  "appGuideSub": "नाप दर्ज करना, OCR स्कैन, ट्रैकिंग और व्हाट्सएप",
  "cloudAutoSave": "क्लाउड ऑटो-सेव (Firebase Cloud)",
  "cloudAutoSaveLive": "सक्रिय व सुरक्षित",
  "cloudDatabaseLabel": "क्लाउड डेटाबेस:",
  "cloudRecordsLabel": "क्लाउड रिकॉर्ड्स:",
  "lastSyncedLabel": "अंतिम सिंक:",
  "syncAllNow": "सभी डेटा अभी क्लाउड पर सुरक्षित करें",
  "syncingToCloud": "क्लाउड पर सहेजा जा रहा है...",
  "dataBackupRestore": "डेटा बैकअप व पुनर्स्थापना",
  "recordsCount": "रिकॉर्ड्स",
  "backupData": "बैकअप बनाएं (JSON)",
  "restoreData": "डेटा बहाल करें (JSON)",
  "developerCredit": "डेवलपर: नसीब एसईओ (पीर बख्श)",
  "copyrightNotice": "सर्वाधिकार सुरक्षित © 2026 आज़ाद मास्टर",
  "resetAllRecords": "सभी कटिंग स्लिप्स हटाएं",
  "resetRecordsConfirm": "क्या आप वाकई सभी ग्राहकों का रिकॉर्ड हटाना चाहते हैं?",
  "savedSuccess": "सहेज लिया गया!",
  "cloudSyncSuccess": "रिकॉर्ड्स क्लाउड पर सफलतापूर्वक सिंक हो गए!",
  "noRecordsToBackup": "बैकअप के लिए कोई रिकॉर्ड उपलब्ध नहीं है!",
  "backupFileDownloaded": "बैकअप फ़ाइल सफलतापूर्वक डाउनलोड हो गई!",
  "recordsRestoredSuccess": "रिकॉर्ड्स सफलतापूर्वक बहाल हो गए!",
  "noValidRecordsFound": "फ़ाइल में कोई मान्य रिकॉर्ड नहीं मिला।",
  "invalidBackupFile": "अमान्य बैकअप फ़ाइल। कृपया सही JSON फ़ाइल चुनें।",
  "needHelpTitle": "मदद चाहिए? / सहायता",
  "contactWhatsApp": "व्हाट्सएप पर संपर्क करें",
  "contactEmail": "ईमेल सहायता",
  "appGuideTitle": "आज़ाद मास्टर का उपयोग कैसे करें",
  "guideStep1Title": "1. नया नाप दर्ज करना",
  "guideStep1Desc": "नीचे दिए गए (+) या 'नाप दर्ज करें' बटन पर क्लिक करके ग्राहक का नाम, फ़ोन और नाप दर्ज करें।",
  "guideStep2Title": "2. ✂️ कटिंग मोड का जादू",
  "guideStep2Desc": "कटिंग टेबल पर काम करते समय 'कटिंग मोड' ऑन करें। नाप बड़े और स्पष्ट दिखेंगे ताकि दूर से भी आसानी से पढ़े जा सकें।",
  "guideStep3Title": "3. पर्ची / कपड़े की फोटो व OCR स्कैन",
  "guideStep3Desc": "कागज़ी पर्ची की फोटो खींचे, आज़ाद एआई तुरंत नाप पहचान कर फॉर्म में भर देगा।",
  "guideStep4Title": "4. डिजिटल व्हाट्सएप स्लिप व क्लाउड",
  "guideStep4Desc": "एक क्लिक में ग्राहक को व्हाट्सएप पर पूरी कटिंग स्लिप भेजें और डेटा क्लाउड पर 100% सुरक्षित रखें।",
  "closeGuide": "समझ गया / बंद करें",
  "privacyModalTitle": "गोपनीयता नीति व डेटा सुरक्षा",
  "privacyPolicyP1": "आपके सभी ग्राहकों के नाप, संपर्क और बिलिंग खाते आपके निजी क्लाउड अकाउंट में सुरक्षित हैं।",
  "privacyPolicyP2": "कोई भी बाहरी व्यक्ति आपके सिलाई रिकॉर्ड तक नहीं पहुँच सकता। पूरा डेटा एन्क्रिप्टेड और निजी है।",
  "closePrivacy": "ठीक है, समझ गया",
  "secureStorage100": "100% सुरक्षित क्लाउड स्टोरेज",
  "safeBadge": "सुरक्षित",
  "chatbotHeaderTitle": "आज़ाद मास्टर असिस्टेंट",
  "chatbotHeaderSub": "ऑनलाइन कटिंग व सिलाई असिस्टेंट",
  "voiceReplyActive": "आवाज़ जवाब चालू",
  "voiceReplyMuted": "आवाज़ बंद है",
  "typingInputPlaceholder": "नाप लिखें या सिलाई का सवाल पूछें...",
  "detectedMeasurementsHeading": "पहचाने गए नाप",
  "confirmAndApplySlip": "पुष्टि करें और स्लिप में लगाएं",
  "confirmedMeasurement": "पुष्टीकृत",
  "micListeningState": "सुन रहा हूँ... बोलिए",
  "micStartState": "बोलें",
  "voiceScreenTitle": "आज़ाद वॉयस असिस्टेंट",
  "voiceScreenSub": "लाइव वॉयस बातचीत",
  "tapToSpeak": "बोलने के लिए टैप करें",
  "listeningVoice": "सुन रहा हूँ...",
  "processingVoice": "प्रोसेसिंग हो रही है...",
  "botSpeaking": "उत्तर बोल रहा है...",
  "closeVoiceMode": "वॉयस मोड बंद करें",
  "browserNoVoice": "इस ब्राउज़र में आवाज़ पहचानने की सुविधा नहीं है।",
  "chatbotGreeting": "नमस्ते! मैं आज़ाद मास्टर असिस्टेंट हूँ। आप नाप बोलकर या लिखकर बता सकते हैं (लंबाई, तीरा, बाज़ू, सीना, कमर, दामन, कॉलर, सलवार, पाँचा)। मैं नाप को व्यवस्थित करके स्लिप में दर्ज कर दूंगा।",
  "quickPrompt1": "लंबाई 42, तीरा 18.5, बाज़ू 23, सीना 38, दामन 24, कॉलर 15.5, सलवार 38",
  "quickPrompt2": "जेंट्स सूट के लिए कितना कपड़ा चाहिए?",
  "quickPrompt3": "तीरा और आर्महोल निकालने का सही फॉर्मूला क्या है?",
  "quickPrompt4": "कॉलर और बैन की कटिंग सही कैसे करें?",
  "login": "लॉग इन",
  "codePlaceholder": "व्हाट्सएप नंबर या कोड लिखें...",
  "pinHint": "डिफ़ॉल्ट पिन: 123456 (या सीधे प्रवेश करें)",
  "signingIn": "लॉग इन हो रहा है...",
  "signInWithGoogle": "Google खाते से सुरक्षित लॉगिन",
  "openInNewTab": "नई विंडो में खोलें",
  "tryRedirectLogin": "रीडायरेक्ट लॉगिन आज़माएं",
  "openInNewWindow": "सीधे नई विंडो में खोलें",
  "secureRecords": "100% सुरक्षित और निजी रिकॉर्ड्स",
  "loginPrivacyNotice": "प्रत्येक दर्जी मास्टर अपने गूगल खाते से लॉग इन करता है और उसका पूरा डेटा पूर्णतः निजी रहता है।",
  "currentDomainLabel": "वर्तमान डोमेन (Firebase Authorized Domains):",
  "copyDomainBtn": "डोमेन कॉपी करें",
  "copiedDomainMsg": "कॉपी हो गया!",
  "authorizedDomainTip": "इस डोमेन को Firebase Console > Authentication > Settings > Authorized Domains में जोड़ें।",
  "deleteConfirm": "क्या आप वाकई इस स्लिप को हटाना चाहते हैं?",
  "deleteSuccess": "ग्राहक स्लिप सफलतापूर्वक हटा दी गई।",
  "saveSuccess": "ग्राहक स्लिप सफलतापूर्वक सहेज ली गई।",
  "syncSuccess": "सभी रिकॉर्ड्स क्लाउड पर सुरक्षित हो गए।"
}

# PUNJABI (pa)
pa = {
  "title": "ਆਜ਼ਾਦ ਮਾਸਟਰ",
  "subtitle": "ਸੁਰੱਖਿਅਤ ਦਰਜ਼ੀ ਖਾਤਾ ਤੇ ਡਿਜੀਟਲ ਕਟਿੰਗ ਰਜਿਸਟਰ",
  "appSubtitle": "ਪੇਸ਼ੇਵਰ ਦਰਜ਼ੀ ਡਿਜੀਟਲ ਕਲਾਊਡ ਰਜਿਸਟਰ",
  "defaultMasterTitle": "ਉਸਤਾਦ ਜੀ",
  "masterNameLabel": "ਉਸਤਾਦ ਦਾ ਨਾਮ:",
  "masterPhotoLabel": "ਉਸਤਾਦ ਦੀ ਫੋਟੋ ਲਗਾਓ:",
  "masterDefaultName": "ਉਸਤਾਦ ਜੀ",
  "navHome": "ਘਰ",
  "navSettings": "ਸੈਟਿੰਗਾਂ",
  "navAdd": "ਨਾਪ ਦਰਜ ਕਰੋ",
  "searchPlaceholder": "ਗਾਹਕ ਦਾ ਨਾਮ ਜਾਂ ਫ਼ੋਨ ਨੰਬਰ ਖੋਜੋ...",
  "searchAction": "ਖੋਜੋ",
  "clear": "ਸਾਫ਼ ਕਰੋ",
  "recentSearches": "ਹਾਲੀਆ ਖੋਜਾਂ",
  "clearHistory": "ਹਿਸਟਰੀ ਸਾਫ਼ ਕਰੋ",
  "openSlip": "ਸਲਿੱਪ ਖੋਲ੍ਹੋ",
  "addMeasurementBtn": "ਨਾਪ ਦਰਜ ਕਰੋ",
  "photoOcrBtn": "ਪਰਚੀ / ਕੱਪੜੇ ਦੀ ਫੋਟੋ",
  "cuttingMode": "✂️ ਕਟਿੰਗ ਮੋਡ",
  "normalMode": "ਸਧਾਰਨ ਮੋਡ",
  "voiceInput": "ਆਵਾਜ਼ ਨਾਲ ਦਰਜ ਕਰੋ",
  "chatbot": "ਆਜ਼ਾਦ ਮਾਸਟਰ ਅਸਿਸਟੈਂਟ",
  "assistant": "ਅਸਿਸਟੈਂਟ",
  "settings": "ਸੈਟਿੰਗਾਂ ਤੇ ਪ੍ਰੋਫਾਈਲ",
  "privacy": "ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ",
  "logout": "ਲਾਗ ਆਊਟ",
  "customerSlipsHeading": "ਗਾਹਕਾਂ ਦੀਆਂ ਕਟਿੰਗ ਸਲਿੱਪਾਂ:",
  "statusFiltersHeading": "ਆਰਡਰ ਸਥਿਤੀ ਫਿਲਟਰ:",
  "showingCount": "ਦਿਖਾਇਆ ਗਿਆ:",
  "allFilter": "ਸਾਰੇ",
  "statusPending": "ਲੰਬਿਤ",
  "statusCutting": "ਕਟਿੰਗ ਜਾਰੀ",
  "statusStitching": "ਸਿਲਾਈ ਜਾਰੀ",
  "statusReady": "ਤਿਆਰ ਹੈ",
  "statusDelivered": "ਸੌਂਪ ਦਿੱਤਾ ਗਿਆ",
  "todayDelivery": "ਅੱਜ ਦੀ ਡਿਲੀਵਰੀ:",
  "lateOrders": "ਦੇਰੀ ਵਾਲੇ ਆਰਡਰ:",
  "totalCustomers": "ਕੁੱਲ ਗਾਹਕ",
  "quickStats": "ਸੰਖੇਪ",
  "recentOrders": "ਤਾਜ਼ਾ ਆਰਡਰ (ਤੁਰੰਤ ਦ੍ਰਿਸ਼)",
  "recentOrdersCount": "ਨਵੀਨਤਮ",
  "show": "ਦਿਖਾਓ",
  "hide": "ਲੁਕਾਓ",
  "noRecords": "ਕੋਈ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।",
  "noCustomerFound": "ਕੋਈ ਗਾਹਕ ਨਹੀਂ ਮਿਲਿਆ",
  "noCustomersSaved": "ਅਜੇ ਤੱਕ ਕੋਈ ਗਾਹਕ ਸੁਰੱਖਿਅਤ ਨਹੀਂ ਕੀਤਾ ਗਿਆ",
  "searchHintEmpty": "ਕਿਸੇ ਹੋਰ ਨਾਮ ਜਾਂ ਫ਼ੋਨ ਨੰਬਰ ਨਾਲ ਖੋਜ ਕਰੋ।",
  "addFirstCustomerHint": "ਪਹਿਲਾ ਗਾਹਕ ਜੋੜਨ ਲਈ ਹੇਠਾਂ ਦਿੱਤੇ ਬਟਨ 'ਤੇ ਟੈਪ ਕਰੋ।",
  "addFirstCustomer": "ਪਹਿਲਾ ਗਾਹਕ ਸ਼ਾਮਲ ਕਰੋ",
  "tapToAdd": "ਨਵਾਂ ਨਾਪ ਦਰਜ ਕਰਨ ਲਈ ਹੇਠਾਂ ਦਿੱਤੇ (+) ਬਟਨ 'ਤੇ ਕਲਿੱਕ ਕਰੋ।",
  "tapToAddCustomer": "ਨਵਾਂ ਗਾਹਕ ਸ਼ਾਮਲ ਕਰਨ ਲਈ ਇੱਥੇ ਕਲਿੱਕ ਕਰੋ।",
  "addAsNewCustomer": "ਨਵੇਂ ਗਾਹਕ ਵਜੋਂ",
  "unnamedCustomer": "ਬਿਨਾਂ ਨਾਮ ਗਾਹਕ",
  "date": "ਮਿਤੀ:",
  "delivery": "ਵਾਪਸੀ:",
  "balance": "ਬਾਕੀ:",
  "cleared": "ਪੂਰਾ ਭੁਗਤਾਨ",
  "syncing": "ਸਿੰਕ ਹੋ ਰਿਹਾ ਹੈ...",
  "cloudSynced": "ਕਲਾਊਡ 'ਤੇ ਸੁਰੱਖਿਅਤ",
  "syncNow": "ਹੁਣੇ ਸਿੰਕ ਕਰੋ",
  "cloudSyncError": "ਕਲਾਊਡ ਗਲਤੀ",
  "online": "ਔਨਲਾਈਨ",
  "selectPhotoSource": "ਪਰਚੀ ਜਾਂ ਕੱਪੜੇ ਦੀ ਫੋਟੋ ਚੁਣੋ",
  "camera": "ਕੈਮਰਾ",
  "gallery": "ਗੈਲਰੀ",
  "fillManually": "ਫਾਰਮ ਖੁਦ ਭਰੋ",
  "uploadPhotoTitle": "ਕਾਗਜ਼ੀ ਪਰਚੀ ਦੀ ਫੋਟੋ:",
  "galleryBtn": "🖼️ ਗੈਲਰੀ",
  "cameraBtn": "📸 ਕੈਮਰਾ",
  "removePhoto": "ਫੋਟੋ ਹਟਾਓ",
  "extractingOcr": "ਫੋਟੋ ਤੋਂ ਨਾਪ ਪੜ੍ਹਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
  "addSlip": "ਨਵਾਂ ਨਾਪ ਦਰਜ ਕਰੋ",
  "editSlip": "ਨਾਪ ਸਲਿੱਪ ਸੋਧੋ",
  "customerName": "ਗਾਹਕ ਦਾ ਨਾਮ *",
  "phoneNumber": "ਵਟਸਐਪ ਨੰਬਰ (ਵਿਕਲਪਿਕ)",
  "countryCodeLabel": "ਦੇਸ਼ ਕੋਡ",
  "suitTypeLabel": "ਸੂਟ ਦੀ ਕਿਸਮ",
  "suitGents": "ਜੈਂਟਸ ਸੂਟ (ਕੁੜਤਾ ਪਜਾਮਾ / ਸ਼ਲਵਾਰ ਕਮੀਜ਼)",
  "suitKurtaPajama": "ਕੁੜਤਾ ਪਜਾਮਾ",
  "suitSafari": "ਸਫ਼ਾਰੀ ਸੂਟ",
  "suitWaistcoat": "ਵਾਸਕਟ",
  "suitSherwani": "ਸ਼ੇਰਵਾਨੀ",
  "deliveryDateLabel": "ਡਿਲੀਵਰੀ ਮਿਤੀ",
  "quickToday": "ਅੱਜ",
  "quickTomorrow": "ਭਲਕੇ",
  "quick3Days": "3 ਦਿਨ",
  "quick1Week": "1 ਹਫ਼ਤਾ",
  "quick10Days": "10 ਦਿਨ",
  "orderStatusLabel": "ਆਰਡਰ ਸਥਿਤੀ:",
  "orderLockedNotice": "ਇਹ ਆਰਡਰ ਮੁਕੰਮਲ ਅਤੇ ਲਾਕ ਹੈ। ਕੀ ਤੁਸੀਂ ਇਸਨੂੰ ਅਨਲਾਕ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
  "orderLockedBadge": "🔒 ਲਾਕ",
  "orderUnlockedBadge": "🔓 ਅਨਲਾਕ",
  "dueTodayBadge": "⚡ ਅੱਜ ਦੀ ਡਿਲੀਵਰੀ",
  "lateOrderBadge": "⚠️ ਲੇਟ ਆਰਡਰ",
  "upcomingBadge": "📅 ਆਉਣ ਵਾਲਾ",
  "lengthLabel": "ਲੰਬਾਈ",
  "shoulderLabel": "ਤੀਰਾ / ਮੋਢਾ",
  "sleevesLabel": "ਬਾਂਹ / ਬਾਜ਼ੂ",
  "chestLabel": "ਛਾਤੀ",
  "waistLabel": "ਕਮਰ",
  "daamanLabel": "ਘੇਰਾ / ਦਾਮਨ",
  "collarLabel": "ਕਾਲਰ / ਬੈਨ",
  "shalwarLabel": "ਸ਼ਲਵਾਰ / ਪਜਾਮਾ",
  "panchaLabel": "ਪਹੁੰਚਾ",
  "pocketLabel": "ਜੇਬ",
  "specialNotesLabel": "ਵਿਸ਼ੇਸ਼ ਹਦਾਇਤਾਂ",
  "notesPlaceholder": "ਜਿਵੇਂ: ਗੋਲ ਘੇਰਾ, ਬੈਨ ਕਾਲਰ...",
  "billingHeading": "ਸਿਲਾਈ ਬਿੱਲ ਤੇ ਖਾਤਾ:",
  "totalAmountLabel": "ਕੁੱਲ ਰਕਮ",
  "advanceAmountLabel": "ਪੇਸ਼ਗੀ (ਐਡਵਾਂਸ)",
  "balanceAmountLabel": "ਬਾਕੀ ਰਕਮ",
  "fullyPaidBadge": "✓ ਪੂਰਾ ਭੁਗਤਾਨ",
  "balanceDueBadge": "⏳ ਬਾਕੀ ਬਕਾਇਆ",
  "saveDone": "ਸੁਰੱਖਿਅਤ ਕਰੋ ਤੇ ਮੁਕੰਮਲ",
  "saveClose": "ਸੁਰੱਖਿਅਤ ਕਰੋ ਤੇ ਬੰਦ ਕਰੋ",
  "cancel": "ਰੱਦ ਕਰੋ",
  "close": "ਮੁਕੰਮਲ / ਬੰਦ",
  "back": "ਪਿੱਛੇ",
  "digitalSlip": "ਡਿਜੀਟਲ ਕਟਿੰਗ ਸਲਿੱਪ",
  "editMode": "ਸੋਧ / ਕਟਿੰਗ ਮੋਡ",
  "sendWhatsapp": "ਵਟਸਐਪ 'ਤੇ ਸਲਿੱਪ ਭੇਜੋ",
  "copySlip": "ਸਲਿੱਪ ਕਾਪੀ ਕਰੋ",
  "printSlip": "ਪ੍ਰਿੰਟ ਕਰੋ",
  "delete": "ਮਿਟਾਓ",
  "copySuccess": "ਸਲਿੱਪ ਕਲਿੱਪਬੋਰਡ 'ਤੇ ਕਾਪੀ ਹੋ ਗਈ!",
  "bookedDateLabel": "ਬੁਕਿੰਗ:",
  "deliveryDatePrefix": "ਡਿਲੀਵਰੀ ਮਿਤੀ:",
  "tailorStamp": "ਮਾਸਟਰ ਦਰਜ਼ੀ ਮੋਹਰ",
  "customerDetailsHeading": "ਗਾਹਕ ਵੇਰਵੇ",
  "measurementsHeading": "ਨਾਪ ਦੇ ਵੇਰਵੇ",
  "accountSummaryHeading": "ਬਿੱਲ ਸਾਰਾਂਸ਼",
  "menuTitle": "ਆਜ਼ਾਦ ਮਾਸਟਰ ਮੇਨੂ",
  "profileSettings": "ਪ੍ਰੋਫਾਈਲ ਤੇ ਸੈਟਿੰਗਾਂ",
  "changeLanguage": "ਭਾਸ਼ਾ ਬਦਲੋ",
  "dataBackup": "ਕਲਾਊਡ ਬੈਕਅੱਪ ਤੇ ਸਿੰਕ",
  "helpSupport": "ਵਰਤੋਂ ਗਾਈਡ ਤੇ ਸਹਾਇਤਾ",
  "developerInfo": "ਡਿਵੈਲਪਰ ਜਾਣਕਾਰੀ",
  "settingsTitle": "ਪ੍ਰੋਫਾਈਲ ਤੇ ਐਪ ਸੈਟਿੰਗਾਂ",
  "selectAppLanguage": "ਐਪ ਦੀ ਭਾਸ਼ਾ",
  "allSupportedLanguages": "ਸਾਰੀਆਂ 22 ਸਮਰਥਿਤ ਭਾਸ਼ਾਵਾਂ:",
  "aiVoiceAssistant": "ਆਜ਼ਾਦ ਏਆਈ ਵੌਇਸ ਅਸਿਸਟੈਂਟ",
  "aiVoiceAssistantSub": "ਨਾਪ ਬੋਲੋ ਜਾਂ ਲਿਖੋ, ਸਵੈਚਾਲਤ ਕਟਿੰਗ ਹਿਸਾਬ",
  "appGuide": "ਵਰਤੋਂ ਕਰਨ ਦਾ ਤਰੀਕਾ (ਗਾਈਡ)",
  "appGuideSub": "ਨਾਪ ਦਰਜ ਕਰਨਾ, OCR ਸਕੈਨ, ਟਰੈਕਿੰਗ ਤੇ ਵਟਸਐਪ",
  "cloudAutoSave": "ਕਲਾਊਡ ਆਟੋ-ਸੇਵ (Firebase Cloud)",
  "cloudAutoSaveLive": "ਸਰਗਰਮ ਤੇ ਸੁਰੱਖਿਅਤ",
  "cloudDatabaseLabel": "ਕਲਾਊਡ ਡਾਟਾਬੇਸ:",
  "cloudRecordsLabel": "ਕਲਾਊਡ ਰਿਕਾਰਡ:",
  "lastSyncedLabel": "ਆਖਰੀ ਸਿੰਕ:",
  "syncAllNow": "ਸਾਰਾ ਡਾਟਾ ਹੁਣੇ ਕਲਾਊਡ 'ਤੇ ਸੁਰੱਖਿਅਤ ਕਰੋ",
  "syncingToCloud": "ਕਲਾਊਡ 'ਤੇ ਸੁਰੱਖਿਅਤ ਹੋ ਰਿਹਾ ਹੈ...",
  "dataBackupRestore": "ਡਾਟਾ ਬੈਕਅੱਪ ਤੇ ਬਹਾਲੀ",
  "recordsCount": "ਰਿਕਾਰਡ",
  "backupData": "ਬੈਕਅੱਪ ਬਣਾਓ (JSON)",
  "restoreData": "ਡਾਟਾ ਬਹਾਲ ਕਰੋ (JSON)",
  "developerCredit": "ਡਿਵੈਲਪਰ: ਨਸੀਬ ਐਸਈਓ (ਪੀਰ ਬਖ਼ਸ਼)",
  "copyrightNotice": "ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ © 2026 ਆਜ਼ਾਦ ਮਾਸਟਰ",
  "resetAllRecords": "ਸਾਰੀਆਂ ਕਟਿੰਗ ਸਲਿੱਪਾਂ ਹਟਾਓ",
  "resetRecordsConfirm": "ਕੀ ਤੁਸੀਂ ਸਾਰੇ ਗਾਹਕਾਂ ਦਾ ਰਿਕਾਰਡ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
  "savedSuccess": "ਸੁਰੱਖਿਅਤ ਹੋ ਗਿਆ!",
  "cloudSyncSuccess": "ਰਿਕਾਰਡ ਕਲਾਊਡ 'ਤੇ ਸਫ਼ਲਤਾਪੂਰਵਕ ਸਿੰਕ ਹੋ ਗਏ!",
  "noRecordsToBackup": "ਬੈਕਅੱਪ ਲਈ ਕੋਈ ਰਿਕਾਰਡ ਨਹੀਂ ਹੈ!",
  "backupFileDownloaded": "ਬੈਕਅੱਪ ਫਾਈਲ ਡਾਊਨਲੋਡ ਹੋ ਗਈ!",
  "recordsRestoredSuccess": "ਰਿਕਾਰਡ ਬਹਾਲ ਹੋ ਗਏ!",
  "noValidRecordsFound": "ਫਾਈਲ ਵਿੱਚ ਕੋਈ ਵੈਧ ਰਿਕਾਰਡ ਨਹੀਂ ਮਿਲਿਆ।",
  "invalidBackupFile": "ਅਵੈਧ ਬੈਕਅੱਪ ਫਾਈਲ। ਕਿਰਪਾ ਕਰਕੇ ਸਹੀ JSON ਫਾਈਲ ਚੁਣੋ।",
  "needHelpTitle": "ਮਦਦ ਚਾਹੀਦੀ ਹੈ? / ਸਹਾਇਤਾ",
  "contactWhatsApp": "ਵਟਸਐਪ 'ਤੇ ਸੰਪਰਕ ਕਰੋ",
  "contactEmail": "ਈਮੇਲ ਸਹਾਇਤਾ",
  "appGuideTitle": "ਆਜ਼ਾਦ ਮਾਸਟਰ ਦੀ ਵਰਤੋਂ ਕਿਵੇਂ ਕਰੀਏ",
  "guideStep1Title": "1. ਨਵਾਂ ਨਾਪ ਦਰਜ ਕਰਨਾ",
  "guideStep1Desc": "ਹੇਠਾਂ ਦਿੱਤੇ (+) ਬਟਨ 'ਤੇ ਕਲਿੱਕ ਕਰਕੇ ਗਾਹਕ ਦਾ ਨਾਮ, ਫ਼ੋਨ ਅਤੇ ਨਾਪ ਦਰਜ ਕਰੋ।",
  "guideStep2Title": "2. ✂️ ਕਟਿੰਗ ਮੋਡ ਦੀ ਖ਼ਾਸੀਅਤ",
  "guideStep2Desc": "ਕਟਿੰਗ ਟੇਬਲ 'ਤੇ ਕੰਮ ਕਰਦੇ ਸਮੇਂ ਕਟਿੰਗ ਮੋਡ ਆਨ ਕਰੋ, ਜਿਸ ਨਾਲ ਨਾਪ ਵੱਡੇ ਤੇ ਸਪਸ਼ਟ ਦਿਖਣਗੇ।",
  "guideStep3Title": "3. ਪਰਚੀ ਫੋਟੋ ਤੇ OCR ਸਕੈਨ",
  "guideStep3Desc": "ਕਾਗਜ਼ੀ ਪਰਚੀ ਦੀ ਫੋਟੋ ਲਓ, ਏਆਈ ਤੁਰੰਤ ਨਾਪ ਪਛਾਣ ਕੇ ਫਾਰਮ ਭਰ ਦੇਵੇਗਾ।",
  "guideStep4Title": "4. ਡਿਜੀਟਲ ਵਟਸਐਪ ਸਲਿੱਪ ਤੇ ਕਲਾਊਡ",
  "guideStep4Desc": "ਇੱਕ ਕਲਿੱਕ ਵਿੱਚ ਗਾਹਕ ਨੂੰ ਵਟਸਐਪ 'ਤੇ ਪੂਰੀ ਸਲਿੱਪ ਭੇਜੋ ਅਤੇ ਡਾਟਾ ਕਲਾਊਡ 'ਤੇ ਸੁਰੱਖਿਅਤ ਰੱਖੋ।",
  "closeGuide": "ਸਮਝ ਆ ਗਿਆ / ਬੰਦ ਕਰੋ",
  "privacyModalTitle": "ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ ਤੇ ਡਾਟਾ ਸੁਰੱਖਿਆ",
  "privacyPolicyP1": "ਤੁਹਾਡੇ ਗਾਹਕਾਂ ਦੇ ਨਾਪ ਤੇ ਖਾਤੇ ਨਿੱਜੀ ਕਲਾਊਡ ਖਾਤੇ ਵਿੱਚ ਪੂਰੀ ਤਰ੍ਹਾਂ ਸੁਰੱਖਿਅਤ ਹਨ।",
  "privacyPolicyP2": "ਕੋਈ ਵੀ ਬਾਹਰੀ ਵਿਅਕਤੀ ਤੁਹਾਡੇ ਸਿਲਾਈ ਰਿਕਾਰਡ ਨਹੀਂ ਵੇਖ ਸਕਦਾ। ਪੂਰਾ ਡਾਟਾ ਐਨਕ੍ਰਿਪਟਡ ਹੈ।",
  "closePrivacy": "ਠੀਕ ਹੈ, ਸਮਝ ਗਿਆ",
  "secureStorage100": "100% ਸੁਰੱਖਿਅਤ ਕਲਾਊਡ ਸਟੋਰੇਜ",
  "safeBadge": "ਸੁਰੱਖਿਅਤ",
  "chatbotHeaderTitle": "ਆਜ਼ਾਦ ਮਾਸਟਰ ਅਸਿਸਟੈਂਟ",
  "chatbotHeaderSub": "ਆਨਲਾਈਨ ਕਟਿੰਗ ਤੇ ਸਿਲਾਈ ਅਸਿਸਟੈਂਟ",
  "voiceReplyActive": "ਆਵਾਜ਼ ਜਵਾਬ ਚਾਲੂ",
  "voiceReplyMuted": "ਆਵਾਜ਼ ਬੰਦ ਹੈ",
  "typingInputPlaceholder": "ਨਾਪ ਲਿਖੋ ਜਾਂ ਸਿਲਾਈ ਸਬੰਧੀ ਸਵਾਲ ਪੁੱਛੋ...",
  "detectedMeasurementsHeading": "ਪਛਾਣੇ ਗਏ ਨਾਪ",
  "confirmAndApplySlip": "ਪੁਸ਼ਟੀ ਕਰੋ ਤੇ ਸਲਿੱਪ ਵਿੱਚ ਲਗਾਓ",
  "confirmedMeasurement": "ਪੁਸ਼ਟੀ ਹੋਈ",
  "micListeningState": "ਸੁਣ ਰਿਹਾ ਹਾਂ... ਬੋਲੋ",
  "micStartState": "ਬੋਲੋ",
  "voiceScreenTitle": "ਆਜ਼ਾਦ ਵੌਇਸ ਅਸਿਸਟੈਂਟ",
  "voiceScreenSub": "ਲਾਈਵ ਗੱਲਬਾਤ",
  "tapToSpeak": "ਬੋਲਣ ਲਈ ਟੈਪ ਕਰੋ",
  "listeningVoice": "ਸੁਣ ਰਿਹਾ ਹਾਂ...",
  "processingVoice": "ਪ੍ਰੋਸੈਸਿੰਗ ਹੋ ਰਹੀ ਹੈ...",
  "botSpeaking": "ਜਵਾਬ ਬੋਲ ਰਿਹਾ ਹੈ...",
  "closeVoiceMode": "ਵੌਇਸ ਮੋਡ ਬੰਦ ਕਰੋ",
  "browserNoVoice": "ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਆਵਾਜ਼ ਪਛਾਣ ਦੀ ਸਹੂਲਤ ਨਹੀਂ ਹੈ।",
  "chatbotGreeting": "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਆਜ਼ਾਦ ਮਾਸਟਰ ਅਸਿਸਟੈਂਟ ਹਾਂ। ਤੁਸੀਂ ਨਾਪ ਬੋਲ ਕੇ ਜਾਂ ਲਿਖ ਕੇ ਦੱਸ ਸਕਦੇ ਹੋ (ਲੰਬਾਈ, ਤੀਰਾ, ਬਾਂਹ, ਛਾਤੀ, ਕਮਰ, ਘੇਰਾ, ਕਾਲਰ, ਸ਼ਲਵਾਰ, ਪਹੁੰਚਾ)। ਮੈਂ ਨਾਪ ਨੂੰ ਤਰਤੀਬ ਦੇ ਕੇ ਸਲਿੱਪ ਵਿੱਚ ਦਰਜ ਕਰ ਦਿਆਂਗਾ।",
  "quickPrompt1": "ਲੰਬਾਈ 42, ਤੀਰਾ 18.5, ਬਾਂਹ 23, ਛਾਤੀ 38, ਘੇਰਾ 24, ਕਾਲਰ 15.5, ਸ਼ਲਵਾਰ 38",
  "quickPrompt2": "ਜੈਂਟਸ ਸੂਟ ਲਈ ਕਿੰਨਾ ਕੱਪੜਾ ਚਾਹੀਦਾ ਹੈ?",
  "quickPrompt3": "ਤੀਰਾ ਅਤੇ ਮੋਢਾ ਕੱਢਣ ਦਾ ਸਹੀ ਫਾਰਮੂਲਾ ਕੀ ਹੈ?",
  "quickPrompt4": "ਕਾਲਰ ਅਤੇ ਬੈਨ ਦੀ ਕਟਿੰਗ ਸਹੀ ਕਿਵੇਂ ਕਰੀਏ?",
  "login": "ਲਾਗ ਇਨ",
  "codePlaceholder": "ਵਟਸਐਪ ਨੰਬਰ ਜਾਂ ਕੋਡ ਲਿਖੋ...",
  "pinHint": "ਡਿਫਾਲਟ ਪਿੰਨ: 123456 (ਜਾਂ ਖਾਲੀ ਛੱਡੋ)",
  "signingIn": "ਲਾਗਇਨ ਹੋ ਰਿਹਾ ਹੈ...",
  "signInWithGoogle": "Google ਖਾਤੇ ਨਾਲ ਸੁਰੱਖਿਅਤ ਲਾਗਇਨ",
  "openInNewTab": "ਨਵੀਂ ਵਿੰਡੋ ਵਿੱਚ ਖੋਲ੍ਹੋ",
  "tryRedirectLogin": "ਰੀਡਾਇਰੈਕਟ ਲਾਗਇਨ ਅਜ਼ਮਾਓ",
  "openInNewWindow": "ਸਿੱਧਾ ਨਵੀਂ ਵਿੰਡੋ ਵਿੱਚ ਲਾਗਇਨ",
  "secureRecords": "100% ਸੁਰੱਖਿਅਤ ਤੇ ਨਿੱਜੀ ਰਿਕਾਰਡ",
  "loginPrivacyNotice": "ਹਰੇਕ ਦਰਜ਼ੀ ਆਪਣੇ ਗੂਗਲ ਖਾਤੇ ਨਾਲ ਲਾਗਇਨ ਕਰਦਾ ਹੈ ਅਤੇ ਸਾਰਾ ਡਾਟਾ ਨਿੱਜੀ ਰਹਿੰਦਾ ਹੈ।",
  "currentDomainLabel": "ਮੌਜੂਦਾ ਡੋਮੇਨ (Firebase Authorized Domains):",
  "copyDomainBtn": "ਡੋਮੇਨ ਕਾਪੀ ਕਰੋ",
  "copiedDomainMsg": "ਕਾਪੀ ਹੋ ਗਿਆ!",
  "authorizedDomainTip": "ਇਸ ਡੋਮੇਨ ਨੂੰ Firebase Console > Authentication > Settings > Authorized Domains ਵਿੱਚ ਜੋੜੋ।",
  "deleteConfirm": "ਕੀ ਤੁਸੀਂ ਵਾਕਈ ਇਹ ਸਲਿੱਪ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?",
  "deleteSuccess": "ਗਾਹਕ ਸਲਿੱਪ ਸਫ਼ਲਤਾਪੂਰਵਕ ਹਟਾਈ ਗਈ।",
  "saveSuccess": "ਗਾਹਕ ਸਲਿੱਪ ਸਫ਼ਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਹੋ ਗਈ।",
  "syncSuccess": "ਸਾਰੇ ਰਿਕਾਰਡ ਕਲਾਊਡ 'ਤੇ ਸੁਰੱਖਿਅਤ ਹੋ ਗਏ।"
}

# BENGALI (bn)
bn = {
  "title": "আজাদ মাস্টার",
  "subtitle": "নিরাপদ দর্জি খাতা ও ডিজিটাল কাটিং রেজিস্টার",
  "appSubtitle": "পেশাদার দর্জি ডিজিটাল ক্লাউড রেজিস্টার",
  "defaultMasterTitle": "মাস্টার সাহেব",
  "masterNameLabel": "মাস্টার সাহেবের নাম:",
  "masterPhotoLabel": "ছবি আপলোড করুন:",
  "masterDefaultName": "মাস্টার সাহেব",
  "navHome": "হোম",
  "navSettings": "সেটিংস",
  "navAdd": "মাপ লিখুন",
  "searchPlaceholder": "গ্রাহকের নাম বা ফোন নম্বর খুঁজুন...",
  "searchAction": "অনুসন্ধান",
  "clear": "মুছুন",
  "recentSearches": "সাম্প্রতিক অনুসন্ধান",
  "clearHistory": "ইতিহাস মুছুন",
  "openSlip": "স্লিপ খুলুন",
  "addMeasurementBtn": "মাপ লিখুন",
  "photoOcrBtn": "চিরকুট / কাপড়ের ছবি",
  "cuttingMode": "✂️ কাটিং মোড",
  "normalMode": "সাধারণ মোড",
  "voiceInput": "কণ্ঠস্বর দিয়ে ইনপুট",
  "chatbot": "আজাদ মাস্টার সহকারী",
  "assistant": "সহকারী",
  "settings": "সেটিংস ও প্রোফাইল",
  "privacy": "গোপনীয়তা নীতি",
  "logout": "লগআউট",
  "customerSlipsHeading": "গ্রাহকদের কাটিং স্লিপ:",
  "statusFiltersHeading": "অর্ডার স্ট্যাটাস ফিল্টার:",
  "showingCount": "প্রদর্শিত:",
  "allFilter": "সকল",
  "statusPending": "অপেক্ষমাণ",
  "statusCutting": "কাটিং চলছে",
  "statusStitching": "সেলাই চলছে",
  "statusReady": "প্রস্তুত",
  "statusDelivered": "হস্তান্তরিত",
  "todayDelivery": "আজকের ডেলিভারি:",
  "lateOrders": "বিলম্বিত অর্ডার:",
  "totalCustomers": "মোট গ্রাহক",
  "quickStats": "একনজরে",
  "recentOrders": "সাম্প্রতিক অর্ডার (দ্রুত দৃশ্য)",
  "recentOrdersCount": "সর্বশেষ",
  "show": "দেখান",
  "hide": "লুকান",
  "noRecords": "কোনো রেকর্ড পাওয়া যায়নি।",
  "noCustomerFound": "কোনো গ্রাহক পাওয়া যায়নি",
  "noCustomersSaved": "এখনো কোনো গ্রাহক সংরক্ষিত হয়নি",
  "searchHintEmpty": "অন্য কোনো নাম বা ফোন নম্বর দিয়ে খুঁজুন।",
  "addFirstCustomerHint": "প্রথম গ্রাহক যোগ করতে নিচের বোতামে চাপুন।",
  "addFirstCustomer": "প্রথম গ্রাহক যোগ করুন",
  "tapToAdd": "নতুন মাপ যোগ করতে নিচের (+) বোতামে চাপুন।",
  "tapToAddCustomer": "নতুন গ্রাহক যোগ করতে এখানে চাপুন।",
  "addAsNewCustomer": "নতুন গ্রাহক হিসেবে",
  "unnamedCustomer": "নামহীন গ্রাহক",
  "date": "তারিখ:",
  "delivery": "ডেলিভারি:",
  "balance": "বাকি:",
  "cleared": "পরিশোধিত",
  "syncing": "সিঙ্ক হচ্ছে...",
  "cloudSynced": "ক্লাউডে সংরক্ষিত",
  "syncNow": "এখনই সিঙ্ক করুন",
  "cloudSyncError": "ক্লাউড ত্রুটি",
  "online": "অনলাইন",
  "selectPhotoSource": "চিরকুট বা কাপড়ের ছবি নির্বাচন করুন",
  "camera": "ক্যামেরা",
  "gallery": "গ্যালারি",
  "fillManually": "ম্যানুয়াল ফর্ম পূরণ",
  "uploadPhotoTitle": "কাগজের চিরকুটের ছবি:",
  "galleryBtn": "🖼️ গ্যালারি",
  "cameraBtn": "📸 ক্যামেরা",
  "removePhoto": "ছবি সরান",
  "extractingOcr": "ছবি থেকে মাপ বের করা হচ্ছে...",
  "addSlip": "নতুন মাপের স্লিপ লিখুন",
  "editSlip": "স্লিপ সম্পাদনা করুন",
  "customerName": "গ্রাহকের নাম *",
  "phoneNumber": "হোয়াটসঅ্যাপ নম্বর (ঐচ্ছিক)",
  "countryCodeLabel": "দেশের কোড",
  "suitTypeLabel": "পোশাকের ধরন",
  "suitGents": "পুরুষদের পোশাক (পাঞ্জাবি পায়জামা)",
  "suitKurtaPajama": "কুর্তা পায়জামা",
  "suitSafari": "সাফারি স্যুট",
  "suitWaistcoat": "মুজিব কোট / কটি",
  "suitSherwani": "শেরওয়ানি",
  "deliveryDateLabel": "ডেলিভারির তারিখ",
  "quickToday": "আজ",
  "quickTomorrow": "আগামীকাল",
  "quick3Days": "৩ দিন",
  "quick1Week": "১ সপ্তাহ",
  "quick10Days": "১০ দিন",
  "orderStatusLabel": "অর্ডার স্ট্যাটাস:",
  "orderLockedNotice": "এই অর্ডারটি ডেলিভার্ড হিসেবে লক করা। আপনি কি আনলক করে স্ট্যাটাস পরিবর্তন করতে চান?",
  "orderLockedBadge": "🔒 লক করা",
  "orderUnlockedBadge": "🔓 আনলক",
  "dueTodayBadge": "⚡ আজকের ডেলিভারি",
  "lateOrderBadge": "⚠️ বিলম্বিত",
  "upcomingBadge": "📅 আসন্ন",
  "lengthLabel": "লম্বা / দৈর্ঘ্য",
  "shoulderLabel": "কাঁধ / তীরা",
  "sleevesLabel": "হাতা",
  "chestLabel": "বুক / ছাতি",
  "waistLabel": "কোমর",
  "daamanLabel": "ঘের / দামান",
  "collarLabel": "কলার / ব্যান্ড",
  "shalwarLabel": "পায়জামা / সালোয়ার",
  "panchaLabel": "মোহরি / পাঞ্চা",
  "pocketLabel": "পকেট",
  "specialNotesLabel": "বিশেষ নির্দেশাবলী",
  "notesPlaceholder": "যেমন গোল ঘের, ব্যান্ড কলার, এক সেলাই...",
  "billingHeading": "মজুরি ও হিসাব:",
  "totalAmountLabel": "মোট টাকা",
  "advanceAmountLabel": "অগ্রিম গ্রহণ",
  "balanceAmountLabel": "বাকি টাকা",
  "fullyPaidBadge": "✓ সম্পূর্ণ পরিশোধিত",
  "balanceDueBadge": "⏳ বাকি বকেয়া",
  "saveDone": "সংরক্ষণ ও সম্পন্ন",
  "saveClose": "সংরক্ষণ ও বন্ধ",
  "cancel": "বাতিল",
  "close": "সম্পন্ন / বন্ধ",
  "back": "পেছনে",
  "digitalSlip": "ডিজিটাল কাটিং স্লিপ",
  "editMode": "সম্পাদনা / কাটিং মোড",
  "sendWhatsapp": "হোয়াটসঅ্যাপে স্লিপ পাঠান",
  "copySlip": "স্লিপ কপি করুন",
  "printSlip": "প্রিন্ট করুন",
  "delete": "মুছুন",
  "copySuccess": "স্লিপ ক্লিপবোর্ডে কপি হয়েছে!",
  "bookedDateLabel": "বুকিং:",
  "deliveryDatePrefix": "ডেলিভারি তারিখ:",
  "tailorStamp": "মাস্টার দর্জি সিলমোহর",
  "customerDetailsHeading": "গ্রাহকের বিবরণ",
  "measurementsHeading": "মাপের বিবরণ",
  "accountSummaryHeading": "হিসাবের সারাংশ",
  "menuTitle": "আজাদ মাস্টার মেনু",
  "profileSettings": "প্রোফাইল ও সেটিংস",
  "changeLanguage": "ভাষা পরিবর্তন করুন",
  "dataBackup": "ক্লাউড ব্যাকআপ ও সিঙ্ক",
  "helpSupport": "ব্যবহার নির্দেশিকা ও সহায়তা",
  "developerInfo": "ডেভেলপার তথ্য",
  "settingsTitle": "প্রোফাইল ও অ্যাপ সেটিংস",
  "selectAppLanguage": "অ্যাপের ভাষা",
  "allSupportedLanguages": "সমর্থিত সকল ২২টি ভাষা:",
  "aiVoiceAssistant": "আজাদ এআই ভয়েস সহকারী",
  "aiVoiceAssistantSub": "মাপ বলুন বা লিখুন, স্বয়ংক্রিয় কাটিং হিসাব",
  "appGuide": "ব্যবহারের নিয়ম (গাইড)",
  "appGuideSub": "মাপ এন্ট্রি, ছবি স্ক্যান, ট্র্যাকিং ও হোয়াটসঅ্যাপ",
  "cloudAutoSave": "ক্লাউড অটো-সেভ (Firebase Cloud)",
  "cloudAutoSaveLive": "সক্রিয় ও সুরক্ষিত",
  "cloudDatabaseLabel": "ক্লাউড ডেটাবেস:",
  "cloudRecordsLabel": "ক্লাউড রেকর্ড:",
  "lastSyncedLabel": "সর্বশেষ সিঙ্ক:",
  "syncAllNow": "সকল ডেটা এখনই ক্লাউডে সিঙ্ক করুন",
  "syncingToCloud": "ক্লাউডে সেভ হচ্ছে...",
  "dataBackupRestore": "ডেটা ব্যাকআপ ও পুনরুদ্ধার",
  "recordsCount": "রেকর্ড",
  "backupData": "ব্যাকআপ ফাইল তৈরি করুন (JSON)",
  "restoreData": "ডেটা পুনরুদ্ধার করুন (JSON)",
  "developerCredit": "নির্মাতা: নসিব এসইও (পীর বখশ)",
  "copyrightNotice": "সর্বস্বত্ব সংরক্ষিত © ২০২৬ আজাদ মাস্টার",
  "resetAllRecords": "সকল কাটিং স্লিপ মুছুন",
  "resetRecordsConfirm": "আপনি কি নিশ্চিতভাবে সব রেকর্ড মুছে ফেলতে চান?",
  "savedSuccess": "সংরক্ষিত হয়েছে!",
  "cloudSyncSuccess": "রেকর্ড সফলভাবে ক্লাউডে সিঙ্ক হয়েছে!",
  "noRecordsToBackup": "ব্যাকআপ করার মতো কোনো রেকর্ড নেই!",
  "backupFileDownloaded": "ব্যাকআপ ফাইল ডাউনলোড সফল হয়েছে!",
  "recordsRestoredSuccess": "রেকর্ড সফলভাবে পুনরুদ্ধার হয়েছে!",
  "noValidRecordsFound": "ফাইলে কোনো বৈধ রেকর্ড পাওয়া যায়নি।",
  "invalidBackupFile": "ভুল ব্যাকআপ ফাইল। অনুগ্রহ করে সঠিক JSON ফাইল নির্বাচন করুন।",
  "needHelpTitle": "সাহায্য প্রয়োজন? / সহায়তা",
  "contactWhatsApp": "হোয়াটসঅ্যাপে যোগাযোগ করুন",
  "contactEmail": "ইমেল সহায়তা",
  "appGuideTitle": "আজাদ মাস্টার ব্যবহারের নিয়ম",
  "guideStep1Title": "১. নতুন মাপ এন্ট্রি",
  "guideStep1Desc": "নিচের (+) বোতামে চাপ দিয়ে গ্রাহকের নাম, ফোন ও মাপের বিবরণ লিখুন।",
  "guideStep2Title": "২. ✂️ কাটিং মোডের জাদু",
  "guideStep2Desc": "কাটিং টেবিলে কাজ করার সময় কাটিং মোড চালু করুন যাতে সংখ্যাগুলো বড় ও পরিষ্কার দেখায়।",
  "guideStep3Title": "৩. চিরকুটের ছবি ও স্ক্যান",
  "guideStep3Desc": "পুরনো চিরকুটের ছবি তুলুন, এআই সঙ্গে সঙ্গে মাপ শনাক্ত করে ফর্মে বসিয়ে দেবে।",
  "guideStep4Title": "৪. ডিজিটাল হোয়াটসঅ্যাপ স্লিপ ও ক্লাউড",
  "guideStep4Desc": "এক ক্লিকে গ্রাহকের হোয়াটসঅ্যাপে সম্পূর্ণ স্লিপ পাঠান এবং ক্লাউডে ডেটা সুরক্ষিত রাখুন।",
  "closeGuide": "বুঝেছি / বন্ধ করুন",
  "privacyModalTitle": "গোপনীয়তা নীতি ও ডেটা সুরক্ষা",
  "privacyPolicyP1": "আপনার গ্রাহকদের মাপ ও হিসাব আপনার ব্যক্তিগত ক্লাউড অ্যাকাউন্টে সম্পূর্ণ নিরাপদ।",
  "privacyPolicyP2": "কোনো তৃতীয় পক্ষ আপনার সেলাই রেকর্ড দেখতে পারবে না। সব ডেটা এনক্রিপ্ট করা।",
  "closePrivacy": "ঠিক আছে, বুঝেছি",
  "secureStorage100": "১০০% নিরাপদ ক্লাউড স্টোরেজ",
  "safeBadge": "সুরক্ষিত",
  "chatbotHeaderTitle": "আজাদ মাস্টার সহকারী",
  "chatbotHeaderSub": "অনলাইন কাটিং ও দর্জি সহকারী",
  "voiceReplyActive": "ভয়েস উত্তর চালু",
  "voiceReplyMuted": "ভয়েস উত্তর নিঃশব্দ",
  "typingInputPlaceholder": "মাপ লিখুন বা দর্জি কাজের প্রশ্ন জিজ্ঞাসা করুন...",
  "detectedMeasurementsHeading": "শনাক্তকৃত মাপ",
  "confirmAndApplySlip": "নিশ্চিত করে স্লিপে প্রয়োগ করুন",
  "confirmedMeasurement": "নিশ্চিত",
  "micListeningState": "শুনছি... বলুন",
  "micStartState": "বলুন",
  "voiceScreenTitle": "আজাদ ভয়েস সহকারী",
  "voiceScreenSub": "সরাসরি কণ্ঠ কথোপকথন",
  "tapToSpeak": "কথা বলতে চাপুন",
  "listeningVoice": "শুনছি...",
  "processingVoice": "প্রক্রিয়াকরণ হচ্ছে...",
  "botSpeaking": "উত্তর বলা হচ্ছে...",
  "closeVoiceMode": "ভয়েস মোড বন্ধ করুন",
  "browserNoVoice": "এই ব্রাউজারে ভয়েস শনাক্তকরণ সমর্থিত নয়।",
  "chatbotGreeting": "আসসালামু আলাইকুম! আমি আজাদ মাস্টার সহকারী। আপনি মুখে বলে বা লিখে মাপ জানাতে পারেন (লম্বা, কাঁধ, হাতা, ছাতি, কোমর, ঘের, কলার, পায়জামা, মোহরি)। আমি মাপগুলো গুছিয়ে স্লিপে লিপিবদ্ধ করব।",
  "quickPrompt1": "লম্বা ৪২, কাঁধ ১৮.৫, হাতা ২৩, ছাতি ৩৮, ঘের ২৪, কলার ১৫.৫, পায়জামা ৩৮",
  "quickPrompt2": "একটি পাঞ্জাবি তৈরি করতে কত গজ কাপড় লাগে?",
  "quickPrompt3": "কাঁধ ও আর্মহোল কাটার সঠিক সূত্র কী?",
  "quickPrompt4": "কলার ও ব্যান্ডের হালা সঠিকভাবে কাটার উপায় কী?",
  "login": "লগইন",
  "codePlaceholder": "হোয়াটসঅ্যাপ নম্বর বা কোড দিন...",
  "pinHint": "ডিফল্ট পিন: 123456 (বা খালি রাখুন)",
  "signingIn": "লগইন হচ্ছে...",
  "signInWithGoogle": "Google অ্যাকাউন্ট দিয়ে নিরাপদ লগইন",
  "openInNewTab": "নতুন ট্যাবে খুলুন",
  "tryRedirectLogin": "পুনর্নির্দেশ লগইন চেষ্টা করুন",
  "openInNewWindow": "সরাসরি নতুন উইন্ডোতে খুলুন",
  "secureRecords": "১০০% নিরাপদ ও গোপনীয় রেকর্ড",
  "loginPrivacyNotice": "প্রত্যেক দর্জি মাস্টার তার গুগল অ্যাকাউন্ট দিয়ে লগইন করেন এবং তার ডেটা সম্পূর্ণ ব্যক্তিগত থাকে।",
  "currentDomainLabel": "বর্তমান ডোমেইন (Firebase Authorized Domains):",
  "copyDomainBtn": "ডোমেইন কপি করুন",
  "copiedDomainMsg": "কপি হয়েছে!",
  "authorizedDomainTip": "এই ডোমেইনটি Firebase Console > Authentication > Settings > Authorized Domains-এ যুক্ত করুন।",
  "deleteConfirm": "আপনি কি নিশ্চিতভাবে এই স্লিপটি মুছে ফেলতে চান?",
  "deleteSuccess": "গ্রাহকের স্লিপ সফলভাবে মুছে ফেলা হয়েছে।",
  "saveSuccess": "গ্রাহকের স্লিপ সফলভাবে সংরক্ষণ করা হয়েছে।",
  "syncSuccess": "সকল রেকর্ড ক্লাউডে সিঙ্ক হয়েছে।"
}

# TURKISH (tr)
tr = {
  "title": "AZAD MASTER",
  "subtitle": "Güvenli Terzi Yönetimi ve Dijital Kesim Defteri",
  "appSubtitle": "Profesyonel Terzi Dijital Bulut Defteri",
  "defaultMasterTitle": "Terzi Ustası",
  "masterNameLabel": "Usta Adı:",
  "masterPhotoLabel": "Usta Fotoğrafı Yükle:",
  "masterDefaultName": "Terzi Ustası",
  "navHome": "Ana Sayfa",
  "navSettings": "Ayarlar",
  "navAdd": "Ölçü Ekle",
  "searchPlaceholder": "Müşteri adı veya telefon no ara...",
  "searchAction": "Ara",
  "clear": "Temizle",
  "recentSearches": "Son Aramalar",
  "clearHistory": "Geçmişi Temizle",
  "openSlip": "Fişi Aç",
  "addMeasurementBtn": "Ölçü Ekle",
  "photoOcrBtn": "Kumaş / Kağıt Fotoğrafı",
  "cuttingMode": "✂️ Kesim Modu",
  "normalMode": "Normal Mod",
  "voiceInput": "Sesli Giriş",
  "chatbot": "Azad AI Asistanı",
  "assistant": "Asistan",
  "settings": "Ayarlar ve Profil",
  "privacy": "Gizlilik Politikası",
  "logout": "Çıkış Yap",
  "customerSlipsHeading": "Müşteri Kesim Fişleri:",
  "statusFiltersHeading": "Sipariş Durumu Filtreleri:",
  "showingCount": "Gösterilen:",
  "allFilter": "Tümü",
  "statusPending": "Beklemede",
  "statusCutting": "Kesimde",
  "statusStitching": "Dikimde",
  "statusReady": "Hazır",
  "statusDelivered": "Teslim Edildi",
  "todayDelivery": "Bugünkü Teslimatlar:",
  "lateOrders": "Geciken Siparişler:",
  "totalCustomers": "Toplam Müşteri",
  "quickStats": "Genel Bakış",
  "recentOrders": "Son Siparişler (Hızlı Görünüm)",
  "recentOrdersCount": "En Yeni",
  "show": "Göster",
  "hide": "Gizle",
  "noRecords": "Kayıt bulunamadı.",
  "noCustomerFound": "Müşteri bulunamadı",
  "noCustomersSaved": "Henüz kayıtlı müşteri yok",
  "searchHintEmpty": "Farklı bir isim veya telefonla aramayı deneyin.",
  "addFirstCustomerHint": "İlk ölçü fişinizi eklemek için aşağıdaki butona dokunun.",
  "addFirstCustomer": "İlk Müşteriyi Ekle",
  "tapToAdd": "Yeni bir ölçü fişi eklemek için aşağıdaki (+) butonuna dokunun.",
  "tapToAddCustomer": "Yeni müşteri eklemek için buraya dokunun.",
  "addAsNewCustomer": "Yeni Müşteri Olarak",
  "unnamedCustomer": "İsimsiz Müşteri",
  "date": "Tarih:",
  "delivery": "Teslim:",
  "balance": "Kalan:",
  "cleared": "Ödendi",
  "syncing": "Senkronize ediliyor...",
  "cloudSynced": "Buluta Kaydedildi",
  "syncNow": "Şimdi Senkronize Et",
  "cloudSyncError": "Bulut Hatası",
  "online": "Çevrimiçi",
  "selectPhotoSource": "Ölçü Fişi veya Kumaş Fotoğrafı Seçin",
  "camera": "Kamera",
  "gallery": "Galeri",
  "fillManually": "Formu Elle Doldur",
  "uploadPhotoTitle": "Kağıt Ölçü Fişi Fotoğrafı:",
  "galleryBtn": "🖼️ Galeri",
  "cameraBtn": "📸 Kamera",
  "removePhoto": "Fotoğrafı Kaldır",
  "extractingOcr": "Fotoğraftan ölçüler yapay zeka ile okunuyor...",
  "addSlip": "Yeni Ölçü Fişi Ekle",
  "editSlip": "Ölçü Fişini Düzenle",
  "customerName": "Müşteri Adı *",
  "phoneNumber": "WhatsApp Numarası (İsteğe Bağlı)",
  "countryCodeLabel": "Ülke Kodu",
  "suitTypeLabel": "Takım / Kıyafet Türü",
  "suitGents": "Erkek Takımı (Gömlek & Şalvar)",
  "suitKurtaPajama": "Kurta & Pijama",
  "suitSafari": "Safari Takım",
  "suitWaistcoat": "Yelek",
  "suitSherwani": "Şervani",
  "deliveryDateLabel": "Teslim Tarihi",
  "quickToday": "Bugün",
  "quickTomorrow": "Yarın",
  "quick3Days": "3 Gün",
  "quick1Week": "1 Hafta",
  "quick10Days": "10 Gün",
  "orderStatusLabel": "Sipariş Durumu:",
  "orderLockedNotice": "Bu sipariş Teslim Edildi olarak işaretlenmiş ve kilitlidir. Kilidi açıp durumu değiştirmek istiyor musunuz?",
  "orderLockedBadge": "🔒 Kilitli",
  "orderUnlockedBadge": "🔓 Açık",
  "dueTodayBadge": "⚡ Bugün Teslim",
  "lateOrderBadge": "⚠️ Gecikmiş",
  "upcomingBadge": "📅 Yaklaşan",
  "lengthLabel": "Boy / Uzunluk",
  "shoulderLabel": "Omuz",
  "sleevesLabel": "Kol Boyu",
  "chestLabel": "Göğüs Çevresi",
  "waistLabel": "Bel Çevresi",
  "daamanLabel": "Etek Genişliği",
  "collarLabel": "Yaka",
  "shalwarLabel": "Pantolon / Şalvar",
  "panchaLabel": "Paça Genişliği",
  "pocketLabel": "Cep",
  "specialNotesLabel": "Özel Notlar / Talimatlar",
  "notesPlaceholder": "Örn: Yuvarlak etek, hakim yaka, tek dikiş...",
  "billingHeading": "Dikiş Ücreti ve Hesap:",
  "totalAmountLabel": "Toplam Tutar",
  "advanceAmountLabel": "Alınan Kapora",
  "balanceAmountLabel": "Kalan Borç",
  "fullyPaidBadge": "✓ Tamamı Ödendi",
  "balanceDueBadge": "⏳ Kalan Bakiye",
  "saveDone": "Kaydet ve Bitir",
  "saveClose": "Kaydet ve Kapat",
  "cancel": "İptal",
  "close": "Tamam / Kapat",
  "back": "Geri",
  "digitalSlip": "Dijital Kesim Fişi",
  "editMode": "Düzenle / Kesim Modu",
  "sendWhatsapp": "WhatsApp ile Fiş Gönder",
  "copySlip": "Fişi Kopyala",
  "printSlip": "Yazdır",
  "delete": "Sil",
  "copySuccess": "Fiş panoya kopyalandı!",
  "bookedDateLabel": "Sipariş Tarihi:",
  "deliveryDatePrefix": "Teslim Tarihi:",
  "tailorStamp": "Terzi Ustası Mührü",
  "customerDetailsHeading": "Müşteri Bilgileri",
  "measurementsHeading": "Ölçü Detayları",
  "accountSummaryHeading": "Hesap Özeti",
  "menuTitle": "Azad Master Menü",
  "profileSettings": "Profil ve Ayarlar",
  "changeLanguage": "Dili Değiştir",
  "dataBackup": "Bulut Yedekleme ve Senkronizasyon",
  "helpSupport": "Kullanım Kılavuzu ve Yardım",
  "developerInfo": "Geliştirici Bilgisi",
  "settingsTitle": "Profil ve Uygulama Ayarları",
  "selectAppLanguage": "Uygulama Dili",
  "allSupportedLanguages": "Desteklenen 22 Dil:",
  "aiVoiceAssistant": "Azad AI Sesli Asistan",
  "aiVoiceAssistantSub": "Ölçüleri söyleyin veya yazın, otomatik kesim hesabı",
  "appGuide": "Kullanım Kılavuzu",
  "appGuideSub": "Ölçü girişi, OCR tarama, takip ve WhatsApp",
  "cloudAutoSave": "Bulut Otomatik Kayıt (Firebase Cloud)",
  "cloudAutoSaveLive": "Aktif ve Güvenli",
  "cloudDatabaseLabel": "Bulut Veritabanı:",
  "cloudRecordsLabel": "Bulut Kayıtları:",
  "lastSyncedLabel": "Son Senkronizasyon:",
  "syncAllNow": "Tüm Verileri Şimdi Buluta Senkronize Et",
  "syncingToCloud": "Buluta senkronize ediliyor...",
  "dataBackupRestore": "Veri Yedekleme ve Geri Yükleme",
  "recordsCount": "Kayıt",
  "backupData": "Yedek Al (JSON)",
  "restoreData": "Geri Yükle (JSON)",
  "developerCredit": "Geliştirici: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "Tüm Hakları Saklıdır © 2026 Azad Master",
  "resetAllRecords": "Tüm Kesim Fişlerini Sıfırla",
  "resetRecordsConfirm": "Tüm müşteri kayıtlarını silmek istediğinizden emin misiniz?",
  "savedSuccess": "Kaydedildi!",
  "cloudSyncSuccess": "Kayıtlar başarıyla buluta senkronize edildi!",
  "noRecordsToBackup": "Yedeklenecek müşteri kaydı yok!",
  "backupFileDownloaded": "Yedek dosyası başarıyla indirildi!",
  "recordsRestoredSuccess": "Kayıtlar başarıyla geri yüklendi!",
  "noValidRecordsFound": "Dosyada geçerli kayıt bulunamadı.",
  "invalidBackupFile": "Geçersiz yedek dosyası. Lütfen doğru bir JSON dosyası seçin.",
  "needHelpTitle": "Yardım mı Lazım? / Destek",
  "contactWhatsApp": "WhatsApp ile İletişim",
  "contactEmail": "E-posta Desteği",
  "appGuideTitle": "Azad Master Nasıl Kullanılır?",
  "guideStep1Title": "1. Yeni Ölçü Ekleme",
  "guideStep1Desc": "Aşağıdaki (+) veya 'Ölçü Ekle' butonuna basarak müşteri adı, telefon ve ölçü değerlerini girin.",
  "guideStep2Title": "2. ✂️ Kesim Modunun Avantajı",
  "guideStep2Desc": "Kesim masasında çalışırken Kesim Modu'nu açın; sayılar uzaktan bile rahatça okunacak büyüklükte görünür.",
  "guideStep3Title": "3. Kağıt Fiş Fotoğrafı ve OCR",
  "guideStep3Desc": "Müşterinin eski kağıt fişinin fotoğrafını çekin, yapay zeka ölçüleri otomatik olarak forma doldurur.",
  "guideStep4Title": "4. Dijital WhatsApp Fişi ve Bulut",
  "guideStep4Desc": "Tek tıkla müşteriye WhatsApp üzerinden eksiksiz fiş gönderin, tüm kayıtlar bulutta güvende kalsın.",
  "closeGuide": "Anladım / Kılavuzu Kapat",
  "privacyModalTitle": "Gizlilik Politikası ve Veri Güvenliği",
  "privacyPolicyP1": "Tüm müşteri ölçüleriniz, iletişim bilgileriniz ve hesaplarınız özel bulut hesabınızda şifreli saklanır.",
  "privacyPolicyP2": "Hiçbir yetkisiz üçüncü şahıs kayıtlarınıza erişemez. Verileriniz tamamen size özeldir.",
  "closePrivacy": "Kabul Ediyorum ve Kapat",
  "secureStorage100": "%100 Güvenli Bulut Depolama",
  "safeBadge": "Güvenli",
  "chatbotHeaderTitle": "Azad AI Asistanı",
  "chatbotHeaderSub": "Çevrimiçi Terzilik ve Kesim Asistanı",
  "voiceReplyActive": "Sesli Yanıt Açık",
  "voiceReplyMuted": "Sesli Yanıt Sessiz",
  "typingInputPlaceholder": "Ölçüleri yazın veya dikiş sorusu sorun...",
  "detectedMeasurementsHeading": "Algılanan Ölçüler",
  "confirmAndApplySlip": "Onayla ve Fişe Ekle",
  "confirmedMeasurement": "Onaylandı",
  "micListeningState": "Dinliyorum... Konuşun",
  "micStartState": "Konuş",
  "voiceScreenTitle": "Azad Sesli Asistan",
  "voiceScreenSub": "Canlı Sesli Sohbet",
  "tapToSpeak": "Konuşmak için Dokun",
  "listeningVoice": "Dinliyor...",
  "processingVoice": "İşleniyor...",
  "botSpeaking": "Cevap seslendiriliyor...",
  "closeVoiceMode": "Sesli Moddan Çık",
  "browserNoVoice": "Bu tarayıcı ses tanımayı desteklemiyor.",
  "chatbotGreeting": "Merhaba! Ben Azad Master Asistanıyım. Ölçüleri söyleyebilir veya yazabilirsiniz (Boy, Omuz, Kol, Göğüs, Bel, Etek, Yaka, Şalvar, Paça). Ölçüleri düzenleyip kaydetmenize yardımcı olacağım.",
  "quickPrompt1": "Boy 42, Omuz 18.5, Kol 23, Göğüs 38, Etek 24, Yaka 15.5, Şalvar 38",
  "quickPrompt2": "Bir erkek takımı için kaç metre kumaş gerekir?",
  "quickPrompt3": "Omuz ve kol evi kesim formülü nedir?",
  "quickPrompt4": "Hakim yaka ve kavis nasıl doğru kesilir?",
  "login": "Giriş Yap",
  "codePlaceholder": "WhatsApp No veya Kod girin...",
  "pinHint": "Varsayılan PIN: 123456 (veya boş bırakın)",
  "signingIn": "Giriş yapılıyor...",
  "signInWithGoogle": "Google ile Güvenli Giriş",
  "openInNewTab": "Yeni Sekmede Aç",
  "tryRedirectLogin": "Yönlendirmeli Girişi Dene",
  "openInNewWindow": "Doğrudan yeni pencerede aç",
  "secureRecords": "%100 Güvenli ve Özel Kayıtlar",
  "loginPrivacyNotice": "Her terzi ustası kendi Google hesabıyla giriş yapar ve tüm kayıtları tamamen gizli kalır.",
  "currentDomainLabel": "Mevcut Alan Adı (Firebase Authorized Domains):",
  "copyDomainBtn": "Alan Adını Kopyala",
  "copiedDomainMsg": "Kopyalandı!",
  "authorizedDomainTip": "Bu alan adını Firebase Console > Authentication > Settings > Authorized Domains bölümüne ekleyin.",
  "deleteConfirm": "Bu fişi silmek istediğinizden emin misiniz?",
  "deleteSuccess": "Müşteri fişi başarıyla silindi.",
  "saveSuccess": "Müşteri fişi başarıyla kaydedildi.",
  "syncSuccess": "Tüm kayıtlar buluta senkronize edildi."
}

# SPANISH (es)
es = {
  "title": "AZAD MASTER",
  "subtitle": "Gestión Segura de Sastrería y Registro Digital de Corte",
  "appSubtitle": "Registro Digital en la Nube para Sastres Profesionales",
  "defaultMasterTitle": "Maestro Sastre",
  "masterNameLabel": "Nombre del Maestro:",
  "masterPhotoLabel": "Foto del Maestro:",
  "masterDefaultName": "Maestro Sastre",
  "navHome": "Inicio",
  "navSettings": "Ajustes",
  "navAdd": "Añadir Medida",
  "searchPlaceholder": "Buscar por nombre o teléfono...",
  "searchAction": "Buscar",
  "clear": "Limpiar",
  "recentSearches": "Búsquedas Recientes",
  "clearHistory": "Borrar Historial",
  "openSlip": "Abrir Ficha",
  "addMeasurementBtn": "Añadir Medida",
  "photoOcrBtn": "Foto de Ficha / Tela",
  "cuttingMode": "✂️ Modo Corte",
  "normalMode": "Modo Normal",
  "voiceInput": "Entrada de Voz",
  "chatbot": "Asistente Azad IA",
  "assistant": "Asistente",
  "settings": "Ajustes y Perfil",
  "privacy": "Política de Privacidad",
  "logout": "Cerrar Sesión",
  "customerSlipsHeading": "Fichas de Corte de Clientes:",
  "statusFiltersHeading": "Filtros por Estado:",
  "showingCount": "Mostrando:",
  "allFilter": "Todos",
  "statusPending": "Pendiente",
  "statusCutting": "En Corte",
  "statusStitching": "En Costura",
  "statusReady": "Listo para Entrega",
  "statusDelivered": "Entregado",
  "todayDelivery": "Entregas de Hoy:",
  "lateOrders": "Pedidos Atrasados:",
  "totalCustomers": "Total Clientes",
  "quickStats": "Resumen",
  "recentOrders": "Pedidos Recientes (Vista Rápida)",
  "recentOrdersCount": "Más Recientes",
  "show": "Mostrar",
  "hide": "Ocultar",
  "noRecords": "No se encontraron registros.",
  "noCustomerFound": "Cliente no encontrado",
  "noCustomersSaved": "Aún no hay clientes guardados",
  "searchHintEmpty": "Prueba buscando con otro nombre o teléfono.",
  "addFirstCustomerHint": "Toca el botón abajo para añadir tu primera ficha.",
  "addFirstCustomer": "Añadir Primer Cliente",
  "tapToAdd": "Toca el botón (+) abajo para añadir una nueva ficha.",
  "tapToAddCustomer": "Toca aquí para añadir un nuevo cliente.",
  "addAsNewCustomer": "como Nuevo Cliente",
  "unnamedCustomer": "Cliente Sin Nombre",
  "date": "Fecha:",
  "delivery": "Entrega:",
  "balance": "Saldo:",
  "cleared": "Pagado",
  "syncing": "Sincronizando...",
  "cloudSynced": "Sincronizado en la Nube",
  "syncNow": "Sincronizar Ahora",
  "cloudSyncError": "Error de Sincronización",
  "online": "En Línea",
  "selectPhotoSource": "Seleccionar Foto de Ficha o Tela",
  "camera": "Cámara",
  "gallery": "Galería",
  "fillManually": "Llenar Formulario Manualmente",
  "uploadPhotoTitle": "Foto de Ficha en Papel:",
  "galleryBtn": "🖼️ Galería",
  "cameraBtn": "📸 Cámara",
  "removePhoto": "Eliminar Foto",
  "extractingOcr": "Extrayendo medidas con Inteligencia Artificial...",
  "addSlip": "Añadir Nueva Ficha de Medida",
  "editSlip": "Editar Ficha de Medida",
  "customerName": "Nombre del Cliente *",
  "phoneNumber": "WhatsApp (Opcional)",
  "countryCodeLabel": "Código de País",
  "suitTypeLabel": "Tipo de Prenda",
  "suitGents": "Traje de Caballero (Camisa y Pantalón)",
  "suitKurtaPajama": "Kurta y Pijama",
  "suitSafari": "Traje Safari",
  "suitWaistcoat": "Chaleco",
  "suitSherwani": "Sherwani de Gala",
  "deliveryDateLabel": "Fecha de Entrega",
  "quickToday": "Hoy",
  "quickTomorrow": "Mañana",
  "quick3Days": "3 Días",
  "quick1Week": "1 Semana",
  "quick10Days": "10 Días",
  "orderStatusLabel": "Estado del Pedido:",
  "orderLockedNotice": "Este pedido está marcado como Entregado y bloqueado. ¿Deseas desbloquearlo para cambiar el estado?",
  "orderLockedBadge": "🔒 Bloqueado",
  "orderUnlockedBadge": "🔓 Desbloqueado",
  "dueTodayBadge": "⚡ Entrega Hoy",
  "lateOrderBadge": "⚠️ Atrasado",
  "upcomingBadge": "📅 Próximo",
  "lengthLabel": "Largo Total",
  "shoulderLabel": "Hombro",
  "sleevesLabel": "Manga",
  "chestLabel": "Pecho / Tórax",
  "waistLabel": "Cintura",
  "daamanLabel": "Bajo / Vuelo",
  "collarLabel": "Cuello",
  "shalwarLabel": "Pantalón",
  "panchaLabel": "Boca de Pantalón",
  "pocketLabel": "Bolsillo",
  "specialNotesLabel": "Instrucciones Especiales",
  "notesPlaceholder": "Ej: Bajo redondo, cuello mao, costura sencilla...",
  "billingHeading": "Cuenta y Facturación:",
  "totalAmountLabel": "Importe Total",
  "advanceAmountLabel": "Anticipo Pagado",
  "balanceAmountLabel": "Saldo Pendiente",
  "fullyPaidBadge": "✓ Totalmente Pagado",
  "balanceDueBadge": "⏳ Saldo Pendiente",
  "saveDone": "Guardar y Finalizar",
  "saveClose": "Guardar y Cerrar",
  "cancel": "Cancelar",
  "close": "Hecho / Cerrar",
  "back": "Atrás",
  "digitalSlip": "Ficha Digital de Corte",
  "editMode": "Editar / Modo Corte",
  "sendWhatsapp": "Enviar Ficha por WhatsApp",
  "copySlip": "Copiar Ficha",
  "printSlip": "Imprimir",
  "delete": "Eliminar",
  "copySuccess": "¡Ficha copiada al portapapeles!",
  "bookedDateLabel": "Fecha de Reserva:",
  "deliveryDatePrefix": "Fecha de Entrega:",
  "tailorStamp": "Sello Maestro Sastre",
  "customerDetailsHeading": "Datos del Cliente",
  "measurementsHeading": "Detalle de Medidas",
  "accountSummaryHeading": "Resumen de Cuenta",
  "menuTitle": "Menú Azad Master",
  "profileSettings": "Perfil y Configuración",
  "changeLanguage": "Cambiar Idioma",
  "dataBackup": "Copia de Seguridad y Sincronización en la Nube",
  "helpSupport": "Guía de Uso y Soporte",
  "developerInfo": "Información del Desarrollador",
  "settingsTitle": "Perfil y Ajustes de la App",
  "selectAppLanguage": "Idioma de la App",
  "allSupportedLanguages": "Todos los 22 Idiomas Compatibles:",
  "aiVoiceAssistant": "Asistente de Voz Azad IA",
  "aiVoiceAssistantSub": "Habla o escribe medidas para cálculo automático de corte",
  "appGuide": "Guía de Uso",
  "appGuideSub": "Registro de medidas, escaneo OCR, seguimiento y WhatsApp",
  "cloudAutoSave": "Guardado Automático en la Nube (Firebase Cloud)",
  "cloudAutoSaveLive": "Activo y Seguro",
  "cloudDatabaseLabel": "Base de Datos en la Nube:",
  "cloudRecordsLabel": "Registros en la Nube:",
  "lastSyncedLabel": "Última Sincronización:",
  "syncAllNow": "Sincronizar Todos los Datos a la Nube Ahora",
  "syncingToCloud": "Sincronizando a la nube...",
  "dataBackupRestore": "Copia de Seguridad y Restauración",
  "recordsCount": "Registros",
  "backupData": "Crear Copia de Seguridad (JSON)",
  "restoreData": "Restaurar Datos (JSON)",
  "developerCredit": "Desarrollado por: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "Todos los derechos reservados © 2026 Azad Master",
  "resetAllRecords": "Borrar Todas las Fichas de Corte",
  "resetRecordsConfirm": "¿Estás seguro de que deseas borrar todos los registros?",
  "savedSuccess": "¡Guardado con éxito!",
  "cloudSyncSuccess": "¡Registros sincronizados con éxito en la nube!",
  "noRecordsToBackup": "¡No hay registros para respaldar!",
  "backupFileDownloaded": "¡Archivo de respaldo descargado con éxito!",
  "recordsRestoredSuccess": "¡Registros restaurados con éxito!",
  "noValidRecordsFound": "No se encontraron registros válidos en el archivo.",
  "invalidBackupFile": "Archivo no válido. Por favor selecciona un JSON correcto.",
  "needHelpTitle": "¿Necesitas Ayuda? / Soporte",
  "contactWhatsApp": "Contactar por WhatsApp",
  "contactEmail": "Soporte por Correo",
  "appGuideTitle": "Cómo Usar Azad Master",
  "guideStep1Title": "1. Añadir Nueva Medida",
  "guideStep1Desc": "Toca el botón (+) o 'Añadir Medida' para registrar datos del cliente, medidas y fecha.",
  "guideStep2Title": "2. ✂️ Ventaja del Modo Corte",
  "guideStep2Desc": "Activa el Modo Corte en la mesa de trabajo para ver números grandes y claros a distancia.",
  "guideStep3Title": "3. Foto de Ficha y Escaneo con IA",
  "guideStep3Desc": "Toma foto a la ficha de papel tradicional y la IA extraerá las medidas automáticamente.",
  "guideStep4Title": "4. Ficha Digital WhatsApp y Nube",
  "guideStep4Desc": "Envía la ficha completa al cliente por WhatsApp con un solo toque y guarda todo en la nube.",
  "closeGuide": "Entendido / Cerrar Guía",
  "privacyModalTitle": "Política de Privacidad y Protección de Datos",
  "privacyPolicyP1": "Las medidas, contactos y cuentas de tus clientes están cifrados en tu cuenta privada en la nube.",
  "privacyPolicyP2": "Ningún tercero tiene acceso a tus registros de sastrería. Todos los datos son privados.",
  "closePrivacy": "Acepto y Cerrar",
  "secureStorage100": "Almacenamiento en la Nube 100% Seguro",
  "safeBadge": "Seguro",
  "chatbotHeaderTitle": "Asistente Azad IA",
  "chatbotHeaderSub": "Asistente Virtual de Sastrería y Corte",
  "voiceReplyActive": "Respuesta por Voz Activada",
  "voiceReplyMuted": "Respuesta por Voz Silenciada",
  "typingInputPlaceholder": "Escribe medidas o haz una pregunta de sastrería...",
  "detectedMeasurementsHeading": "Medidas Detectadas",
  "confirmAndApplySlip": "Confirmar y Aplicar a la Ficha",
  "confirmedMeasurement": "Confirmado",
  "micListeningState": "Escuchando... Puedes hablar",
  "micStartState": "Hablar",
  "voiceScreenTitle": "Asistente de Voz Azad",
  "voiceScreenSub": "Conversación de Voz en Directo",
  "tapToSpeak": "Toca para Hablar",
  "listeningVoice": "Escuchando...",
  "processingVoice": "Procesando...",
  "botSpeaking": "Reproduciendo respuesta...",
  "closeVoiceMode": "Salir del Modo Voz",
  "browserNoVoice": "Este navegador no admite reconocimiento de voz.",
  "chatbotGreeting": "¡Hola! Soy el asistente de Azad Master. Puedes dictar o escribir las medidas (Largo, Hombro, Manga, Pecho, Cintura, Vuelo, Cuello, Pantalón). Las organizaré y aplicaré a la ficha.",
  "quickPrompt1": "Largo 42, Hombro 18.5, Manga 23, Pecho 38, Vuelo 24, Cuello 15.5, Pantalón 38",
  "quickPrompt2": "¿Cuánta tela se necesita para un traje de hombre?",
  "quickPrompt3": "¿Cuál es la fórmula para la sisa y hombro?",
  "quickPrompt4": "¿Cómo cortar el escote del cuello con precisión?",
  "login": "Iniciar Sesión",
  "codePlaceholder": "Ingresa WhatsApp o Código...",
  "pinHint": "PIN por defecto: 123456 (o dejar en blanco)",
  "signingIn": "Iniciando sesión...",
  "signInWithGoogle": "Acceso Seguro con Google",
  "openInNewTab": "Abrir en Nueva Pestaña",
  "tryRedirectLogin": "Probar Inicio con Redirección",
  "openInNewWindow": "Abrir directamente en ventana nueva",
  "secureRecords": "Registros 100% Seguros y Privados",
  "loginPrivacyNotice": "Cada sastre inicia sesión con su cuenta Google y sus registros se mantienen estrictamente privados.",
  "currentDomainLabel": "Dominio Actual (Firebase Authorized Domains):",
  "copyDomainBtn": "Copiar Dominio",
  "copiedDomainMsg": "¡Copiado!",
  "authorizedDomainTip": "Añade este dominio en Firebase Console > Authentication > Settings > Authorized Domains.",
  "deleteConfirm": "¿Estás seguro de que deseas eliminar esta ficha?",
  "deleteSuccess": "Ficha de cliente eliminada con éxito.",
  "saveSuccess": "Ficha de cliente guardada con éxito.",
  "syncSuccess": "Todos los registros sincronizados en la nube."
}

# FRENCH (fr)
fr = {
  "title": "AZAD MASTER",
  "subtitle": "Gestion Sécurisée de Couture et Registre de Coupe Numérique",
  "appSubtitle": "Registre Numérique Cloud pour Tailleur Professionnel",
  "defaultMasterTitle": "Maître Tailleur",
  "masterNameLabel": "Nom du Maître:",
  "masterPhotoLabel": "Photo du Maître:",
  "masterDefaultName": "Maître Tailleur",
  "navHome": "Accueil",
  "navSettings": "Paramètres",
  "navAdd": "Ajouter Mesure",
  "searchPlaceholder": "Rechercher par nom ou téléphone...",
  "searchAction": "Rechercher",
  "clear": "Effacer",
  "recentSearches": "Recherches Récentes",
  "clearHistory": "Effacer l'historique",
  "openSlip": "Ouvrir Fiche",
  "addMeasurementBtn": "Ajouter Mesure",
  "photoOcrBtn": "Photo de Fiche / Tissu",
  "cuttingMode": "✂️ Mode Coupe",
  "normalMode": "Mode Normal",
  "voiceInput": "Saisie Vocale",
  "chatbot": "Assistant Azad IA",
  "assistant": "Assistant",
  "settings": "Paramètres et Profil",
  "privacy": "Politique de Confidentialité",
  "logout": "Déconnexion",
  "customerSlipsHeading": "Fiches de Coupe Clients:",
  "statusFiltersHeading": "Filtres par Statut:",
  "showingCount": "Affichage:",
  "allFilter": "Tous",
  "statusPending": "En attente",
  "statusCutting": "En coupe",
  "statusStitching": "En couture",
  "statusReady": "Prêt",
  "statusDelivered": "Livré",
  "todayDelivery": "Livraisons du Jour:",
  "lateOrders": "Commandes en Retard:",
  "totalCustomers": "Total Clients",
  "quickStats": "Aperçu",
  "recentOrders": "Commandes Récentes (Vue Rapide)",
  "recentOrdersCount": "Plus Récents",
  "show": "Afficher",
  "hide": "Masquer",
  "noRecords": "Aucun enregistrement trouvé.",
  "noCustomerFound": "Aucun client trouvé",
  "noCustomersSaved": "Aucun client enregistré pour l'instant",
  "searchHintEmpty": "Essayez avec un autre nom ou numéro.",
  "addFirstCustomerHint": "Appuyez sur le bouton ci-dessous pour ajouter votre première fiche.",
  "addFirstCustomer": "Ajouter Premier Client",
  "tapToAdd": "Appuyez sur le bouton (+) pour ajouter une fiche de mesure.",
  "tapToAddCustomer": "Appuyez ici pour ajouter un nouveau client.",
  "addAsNewCustomer": "comme Nouveau Client",
  "unnamedCustomer": "Client Sans Nom",
  "date": "Date:",
  "delivery": "Livraison:",
  "balance": "Solde:",
  "cleared": "Soldé",
  "syncing": "Synchronisation...",
  "cloudSynced": "Enregistré sur le Cloud",
  "syncNow": "Synchroniser Maintenant",
  "cloudSyncError": "Erreur Cloud",
  "online": "En ligne",
  "selectPhotoSource": "Sélectionner Photo de Fiche ou Tissu",
  "camera": "Appareil Photo",
  "gallery": "Galerie",
  "fillManually": "Remplir Manuellement",
  "uploadPhotoTitle": "Photo de Fiche Papier:",
  "galleryBtn": "🖼️ Galerie",
  "cameraBtn": "📸 Caméra",
  "removePhoto": "Supprimer Photo",
  "extractingOcr": "Extraction des mesures par IA...",
  "addSlip": "Ajouter une Fiche de Mesure",
  "editSlip": "Modifier la Fiche de Mesure",
  "customerName": "Nom du Client *",
  "phoneNumber": "Numéro WhatsApp (Optionnel)",
  "countryCodeLabel": "Indicatif Pays",
  "suitTypeLabel": "Type de Vêtement",
  "suitGents": "Costume Homme (Chemise & Pantalon)",
  "suitKurtaPajama": "Kurta Pyjama",
  "suitSafari": "Costume Safari",
  "suitWaistcoat": "Gilet",
  "suitSherwani": "Sherwani de Cérémonie",
  "deliveryDateLabel": "Date de Livraison",
  "quickToday": "Aujourd'hui",
  "quickTomorrow": "Demain",
  "quick3Days": "3 Jours",
  "quick1Week": "1 Semaine",
  "quick10Days": "10 Jours",
  "orderStatusLabel": "Statut de Commande:",
  "orderLockedNotice": "Cette commande est marquée comme Livrée et verrouillée. Souhaitez-vous la déverrouiller pour modifier le statut?",
  "orderLockedBadge": "🔒 Verrouillé",
  "orderUnlockedBadge": "🔓 Déverrouillé",
  "dueTodayBadge": "⚡ Pour Aujourd'hui",
  "lateOrderBadge": "⚠️ En Retard",
  "upcomingBadge": "📅 À venir",
  "lengthLabel": "Longueur",
  "shoulderLabel": "Carrure / Épaules",
  "sleevesLabel": "Manches",
  "chestLabel": "Poitrine / Tour de poitrine",
  "waistLabel": "Taille",
  "daamanLabel": "Bas / Ourlet",
  "collarLabel": "Col",
  "shalwarLabel": "Pantalon",
  "panchaLabel": "Bas de Pantalon",
  "pocketLabel": "Poche",
  "specialNotesLabel": "Instructions Spéciales",
  "notesPlaceholder": "Ex: Bas arrondi, col officier, couture simple...",
  "billingHeading": "Facturation et Solde:",
  "totalAmountLabel": "Montant Total",
  "advanceAmountLabel": "Acompte Versé",
  "balanceAmountLabel": "Reste à Payer",
  "fullyPaidBadge": "✓ Entièrement Payé",
  "balanceDueBadge": "⏳ Solde Dû",
  "saveDone": "Enregistrer et Terminer",
  "saveClose": "Enregistrer et Fermer",
  "cancel": "Annuler",
  "close": "Terminé / Fermer",
  "back": "Retour",
  "digitalSlip": "Fiche de Coupe Numérique",
  "editMode": "Modifier / Mode Coupe",
  "sendWhatsapp": "Envoyer via WhatsApp",
  "copySlip": "Copier la Fiche",
  "printSlip": "Imprimer",
  "delete": "Supprimer",
  "copySuccess": "Fiche copiée dans le presse-papiers!",
  "bookedDateLabel": "Date de Commande:",
  "deliveryDatePrefix": "Date de Livraison:",
  "tailorStamp": "Cachet Maître Tailleur",
  "customerDetailsHeading": "Détails du Client",
  "measurementsHeading": "Détail des Mesures",
  "accountSummaryHeading": "Récapitulatif de Compte",
  "menuTitle": "Menu Azad Master",
  "profileSettings": "Profil et Paramètres",
  "changeLanguage": "Changer de Langue",
  "dataBackup": "Sauvegarde Cloud et Synchro",
  "helpSupport": "Guide d'utilisation et Aide",
  "developerInfo": "Infos Développeur",
  "settingsTitle": "Profil et Paramètres de l'Application",
  "selectAppLanguage": "Langue de l'App",
  "allSupportedLanguages": "Les 22 Langues Prises en Charge:",
  "aiVoiceAssistant": "Assistant Vocal Azad IA",
  "aiVoiceAssistantSub": "Dictez ou écrivez vos mesures pour un calcul automatique",
  "appGuide": "Guide d'Utilisation",
  "appGuideSub": "Saisie des mesures, scan OCR, suivi et WhatsApp",
  "cloudAutoSave": "Sauvegarde Automatique Cloud (Firebase)",
  "cloudAutoSaveLive": "Actif et Sécurisé",
  "cloudDatabaseLabel": "Base de Données Cloud:",
  "cloudRecordsLabel": "Enregistrements Cloud:",
  "lastSyncedLabel": "Dernière Synchro:",
  "syncAllNow": "Synchroniser Tout sur le Cloud Maintenant",
  "syncingToCloud": "Synchronisation sur le Cloud...",
  "dataBackupRestore": "Sauvegarde et Restauration",
  "recordsCount": "Fiches",
  "backupData": "Créer une Sauvegarde (JSON)",
  "restoreData": "Restaurer les Données (JSON)",
  "developerCredit": "Développé par: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "Tous droits réservés © 2026 Azad Master",
  "resetAllRecords": "Effacer Toutes les Fiches",
  "resetRecordsConfirm": "Êtes-vous sûr de vouloir supprimer tous les enregistrements?",
  "savedSuccess": "Enregistré avec succès!",
  "cloudSyncSuccess": "Fiches synchronisées avec succès sur le Cloud!",
  "noRecordsToBackup": "Aucun enregistrement à sauvegarder!",
  "backupFileDownloaded": "Fichier de sauvegarde téléchargé avec succès!",
  "recordsRestoredSuccess": "Fiches restaurées avec succès!",
  "noValidRecordsFound": "Aucun enregistrement valide trouvé dans le fichier.",
  "invalidBackupFile": "Fichier invalide. Veuillez sélectionner un fichier JSON valide.",
  "needHelpTitle": "Besoin d'aide? / Support",
  "contactWhatsApp": "Contacter sur WhatsApp",
  "contactEmail": "Support par E-mail",
  "appGuideTitle": "Comment Utiliser Azad Master",
  "guideStep1Title": "1. Ajouter une Mesure",
  "guideStep1Desc": "Appuyez sur (+) ou 'Ajouter Mesure' pour saisir les coordonnées, mesures et date.",
  "guideStep2Title": "2. ✂️ Avantage du Mode Coupe",
  "guideStep2Desc": "Activez le Mode Coupe à la table de découpe pour afficher les chiffres en grand et lisibles de loin.",
  "guideStep3Title": "3. Photo de Fiche et Scan IA",
  "guideStep3Desc": "Prenez en photo une fiche papier traditionnelle, l'IA remplit les mesures instantanément.",
  "guideStep4Title": "4. Fiche Digitale WhatsApp et Cloud",
  "guideStep4Desc": "Envoyez la fiche complète au client sur WhatsApp d'un clic et conservez tout sur le Cloud.",
  "closeGuide": "J'ai Compris / Fermer",
  "privacyModalTitle": "Confidentialité et Protection des Données",
  "privacyPolicyP1": "Vos mesures, contacts et comptes clients sont stockés de manière chiffrée sur votre compte Cloud privé.",
  "privacyPolicyP2": "Aucun tiers non autorisé ne peut accéder à vos données de couture. Tout est privé et sécurisé.",
  "closePrivacy": "J'ai Compris et Fermer",
  "secureStorage100": "Stockage Cloud 100% Sécurisé",
  "safeBadge": "Sécurisé",
  "chatbotHeaderTitle": "Assistant Azad IA",
  "chatbotHeaderSub": "Assistant Virtuel de Coupe et Couture",
  "voiceReplyActive": "Réponse Vocale Activée",
  "voiceReplyMuted": "Réponse Vocale Désactivée",
  "typingInputPlaceholder": "Tapez les mesures ou posez une question...",
  "detectedMeasurementsHeading": "Mesures Détectées",
  "confirmAndApplySlip": "Confirmer et Insérer dans la Fiche",
  "confirmedMeasurement": "Confirmé",
  "micListeningState": "À l'écoute... Parlez maintenant",
  "micStartState": "Parler",
  "voiceScreenTitle": "Assistant Vocal Azad",
  "voiceScreenSub": "Conversation Vocale en Direct",
  "tapToSpeak": "Appuyez pour Parler",
  "listeningVoice": "Écoute en cours...",
  "processingVoice": "Traitement en cours...",
  "botSpeaking": "Lecture de la réponse...",
  "closeVoiceMode": "Quitter le Mode Vocal",
  "browserNoVoice": "La reconnaissance vocale n'est pas supportée sur ce navigateur.",
  "chatbotGreeting": "Bonjour! Je suis l'assistant Azad Master. Vous pouvez dicter ou saisir vos mesures (Longueur, Épaules, Manches, Poitrine, Taille, Bas, Col, Pantalon). Je vais les classer pour vous.",
  "quickPrompt1": "Longueur 42, Épaules 18.5, Manches 23, Poitrine 38, Bas 24, Col 15.5, Pantalon 38",
  "quickPrompt2": "Combien de tissu faut-il pour un costume homme?",
  "quickPrompt3": "Quelle est la formule de coupe d'emmanchure et carrure?",
  "quickPrompt4": "Comment couper l'encolure du col avec précision?",
  "login": "Connexion",
  "codePlaceholder": "Numéro WhatsApp ou Code...",
  "pinHint": "Code PIN par défaut: 123456 (ou laisser vide)",
  "signingIn": "Connexion en cours...",
  "signInWithGoogle": "Connexion Sécurisée avec Google",
  "openInNewTab": "Ouvrir dans un Nouvel Onglet",
  "tryRedirectLogin": "Essayer la Connexion par Redirection",
  "openInNewWindow": "Ouvrir directement dans une nouvelle fenêtre",
  "secureRecords": "Fiches 100% Privées et Sécurisées",
  "loginPrivacyNotice": "Chaque tailleur se connecte avec son compte Google personnel et ses données restent strictement confidentielles.",
  "currentDomainLabel": "Domaine Actuel (Firebase Authorized Domains):",
  "copyDomainBtn": "Copier le Domaine",
  "copiedDomainMsg": "Copié!",
  "authorizedDomainTip": "Ajoutez ce domaine dans Firebase Console > Authentication > Settings > Authorized Domains.",
  "deleteConfirm": "Êtes-vous sûr de vouloir supprimer cette fiche?",
  "deleteSuccess": "Fiche client supprimée avec succès.",
  "saveSuccess": "Fiche client enregistrée avec succès.",
  "syncSuccess": "Toutes les fiches sont synchronisées sur le Cloud."
}

# GERMAN (de)
de = {
  "title": "AZAD MASTER",
  "subtitle": "Sichere Schneidereiverwaltung & Digitales Zuschneidebuch",
  "appSubtitle": "Professionelles Digitales Cloud-Register für Schneider",
  "defaultMasterTitle": "Schneidermeister",
  "masterNameLabel": "Name des Meisters:",
  "masterPhotoLabel": "Foto des Meisters:",
  "masterDefaultName": "Schneidermeister",
  "navHome": "Startseite",
  "navSettings": "Einstellungen",
  "navAdd": "Maß eintragen",
  "searchPlaceholder": "Nach Name oder Telefonnummer suchen...",
  "searchAction": "Suchen",
  "clear": "Löschen",
  "recentSearches": "Letzte Suchen",
  "clearHistory": "Verlauf leeren",
  "openSlip": "Zettel öffnen",
  "addMeasurementBtn": "Maß eintragen",
  "photoOcrBtn": "Foto von Zettel / Stoff",
  "cuttingMode": "✂️ Zuschnitt-Modus",
  "normalMode": "Normaler Modus",
  "voiceInput": "Spracheingabe",
  "chatbot": "Azad KI-Assistent",
  "assistant": "Assistent",
  "settings": "Einstellungen & Profil",
  "privacy": "Datenschutzrichtlinie",
  "logout": "Abmelden",
  "customerSlipsHeading": "Zuschnittzettel der Kunden:",
  "statusFiltersHeading": "Auftragsstatus-Filter:",
  "showingCount": "Angezeigt:",
  "allFilter": "Alle",
  "statusPending": "Ausstehend",
  "statusCutting": "Im Zuschnitt",
  "statusStitching": "In der Näherei",
  "statusReady": "Fertig zur Abholung",
  "statusDelivered": "Ausgeliefert",
  "todayDelivery": "Heutige Lieferungen:",
  "lateOrders": "Verspätete Aufträge:",
  "totalCustomers": "Gesamtkunden",
  "quickStats": "Übersicht",
  "recentOrders": "Aktuelle Aufträge (Schnellansicht)",
  "recentOrdersCount": "Neueste",
  "show": "Anzeigen",
  "hide": "Ausblenden",
  "noRecords": "Keine Datensätze gefunden.",
  "noCustomerFound": "Kein Kunde gefunden",
  "noCustomersSaved": "Bisher keine Kunden gespeichert",
  "searchHintEmpty": "Versuchen Sie die Suche mit einem anderen Namen oder einer anderen Nummer.",
  "addFirstCustomerHint": "Tippen Sie unten, um Ihren ersten Maßzettel hinzuzufügen.",
  "addFirstCustomer": "Ersten Kunden hinzufügen",
  "tapToAdd": "Tippen Sie unten auf (+), um einen neuen Zettel zu erstellen.",
  "tapToAddCustomer": "Tippen Sie hier, um einen neuen Kunden anzulegen.",
  "addAsNewCustomer": "als neuer Kunde",
  "unnamedCustomer": "Unbenannter Kunde",
  "date": "Datum:",
  "delivery": "Lieferung:",
  "balance": "Restbetrag:",
  "cleared": "Bezahlt",
  "syncing": "Wird synchronisiert...",
  "cloudSynced": "In der Cloud gespeichert",
  "syncNow": "Jetzt synchronisieren",
  "cloudSyncError": "Cloud-Fehler",
  "online": "Online",
  "selectPhotoSource": "Foto von Maßzettel oder Stoff wählen",
  "camera": "Kamera",
  "gallery": "Galerie",
  "fillManually": "Formular manuell ausfüllen",
  "uploadPhotoTitle": "Foto des Papierzettels:",
  "galleryBtn": "🖼️ Galerie",
  "cameraBtn": "📸 Kamera",
  "removePhoto": "Foto entfernen",
  "extractingOcr": "Maße werden per KI ausgelesen...",
  "addSlip": "Neuen Maßzettel anlegen",
  "editSlip": "Maßzettel bearbeiten",
  "customerName": "Kundenname *",
  "phoneNumber": "WhatsApp-Nummer (optional)",
  "countryCodeLabel": "Ländervorwahl",
  "suitTypeLabel": "Kleidungsart",
  "suitGents": "Herrenanzug (Hemd & Hose)",
  "suitKurtaPajama": "Kurta & Pyjama",
  "suitSafari": "Safari-Anzug",
  "suitWaistcoat": "Weste",
  "suitSherwani": "Festlicher Sherwani",
  "deliveryDateLabel": "Liefertermin",
  "quickToday": "Heute",
  "quickTomorrow": "Morgen",
  "quick3Days": "3 Tage",
  "quick1Week": "1 Woche",
  "quick10Days": "10 Tage",
  "orderStatusLabel": "Auftragsstatus:",
  "orderLockedNotice": "Dieser Auftrag ist als Ausgeliefert markiert und gesperrt. Möchten Sie ihn entsperren, um den Status zu ändern?",
  "orderLockedBadge": "🔒 Gesperrt",
  "orderUnlockedBadge": "🔓 Entsperrt",
  "dueTodayBadge": "⚡ Heute fällig",
  "lateOrderBadge": "⚠️ Verspätet",
  "upcomingBadge": "📅 Demnächst",
  "lengthLabel": "Länge",
  "shoulderLabel": "Schulterbreite",
  "sleevesLabel": "Ärmellänge",
  "chestLabel": "Brustumfang",
  "waistLabel": "Taillenumfang",
  "daamanLabel": "Saumweite",
  "collarLabel": "Kragenweite",
  "shalwarLabel": "Hosenlänge",
  "panchaLabel": "Fußweite",
  "pocketLabel": "Tasche",
  "specialNotesLabel": "Besondere Anweisungen",
  "notesPlaceholder": "Z.B. Runder Saum, Stehkragen, einfache Naht...",
  "billingHeading": "Rechnung & Zahlungen:",
  "totalAmountLabel": "Gesamtbetrag",
  "advanceAmountLabel": "Anzahlung",
  "balanceAmountLabel": "Restbetrag",
  "fullyPaidBadge": "✓ Vollständig bezahlt",
  "balanceDueBadge": "⏳ Restbetrag offen",
  "saveDone": "Speichern und fertig",
  "saveClose": "Speichern und schließen",
  "cancel": "Abbrechen",
  "close": "Fertig / Schließen",
  "back": "Zurück",
  "digitalSlip": "Digitaler Zuschnittzettel",
  "editMode": "Bearbeiten / Zuschnitt-Modus",
  "sendWhatsapp": "Zettel per WhatsApp senden",
  "copySlip": "Zettel kopieren",
  "printSlip": "Drucken",
  "delete": "Löschen",
  "copySuccess": "Zettel in die Zwischenablage kopiert!",
  "bookedDateLabel": "Bestelldatum:",
  "deliveryDatePrefix": "Lieferdatum:",
  "tailorStamp": "Stempel des Schneidermeisters",
  "customerDetailsHeading": "Kundendaten",
  "measurementsHeading": "Maßangaben",
  "accountSummaryHeading": "Zahlungsübersicht",
  "menuTitle": "Azad Master Menü",
  "profileSettings": "Profil & Einstellungen",
  "changeLanguage": "Sprache wechseln",
  "dataBackup": "Cloud-Backup & Synchronisation",
  "helpSupport": "Benutzerhandbuch & Hilfe",
  "developerInfo": "Entwickler-Info",
  "settingsTitle": "Profil & App-Einstellungen",
  "selectAppLanguage": "App-Sprache",
  "allSupportedLanguages": "Alle 22 unterstützten Sprachen:",
  "aiVoiceAssistant": "Azad KI-Sprachassistent",
  "aiVoiceAssistantSub": "Maße sprechen oder schreiben für automatische Berechnung",
  "appGuide": "Benutzerhandbuch",
  "appGuideSub": "Maßerfassung, OCR-Scan, Verfolgung & WhatsApp",
  "cloudAutoSave": "Automatische Cloud-Sicherung (Firebase)",
  "cloudAutoSaveLive": "Aktiv & Sicher",
  "cloudDatabaseLabel": "Cloud-Datenbank:",
  "cloudRecordsLabel": "Cloud-Datensätze:",
  "lastSyncedLabel": "Zuletzt synchronisiert:",
  "syncAllNow": "Alle Daten jetzt mit der Cloud synchronisieren",
  "syncingToCloud": "Wird mit der Cloud synchronisiert...",
  "dataBackupRestore": "Datensicherung & Wiederherstellung",
  "recordsCount": "Datensätze",
  "backupData": "Backup erstellen (JSON)",
  "restoreData": "Daten wiederherstellen (JSON)",
  "developerCredit": "Entwickelt von: Naseeb SEO (Pir Bakhash)",
  "copyrightNotice": "Alle Rechte vorbehalten © 2026 Azad Master",
  "resetAllRecords": "Alle Maßzettel löschen",
  "resetRecordsConfirm": "Sind Sie sicher, dass Sie alle Datensätze löschen möchten?",
  "savedSuccess": "Erfolgreich gespeichert!",
  "cloudSyncSuccess": "Datensätze erfolgreich mit der Cloud synchronisiert!",
  "noRecordsToBackup": "Keine Datensätze zum Sichern vorhanden!",
  "backupFileDownloaded": "Backup-Datei erfolgreich heruntergeladen!",
  "recordsRestoredSuccess": "Datensätze erfolgreich wiederhergestellt!",
  "noValidRecordsFound": "Keine gültigen Datensätze in der Datei gefunden.",
  "invalidBackupFile": "Ungültige Datei. Bitte wählen Sie eine gültige JSON-Datei.",
  "needHelpTitle": "Brauchen Sie Hilfe? / Support",
  "contactWhatsApp": "Über WhatsApp kontaktieren",
  "contactEmail": "E-Mail-Support",
  "appGuideTitle": "Anleitung zur Nutzung von Azad Master",
  "guideStep1Title": "1. Neues Maß anlegen",
  "guideStep1Desc": "Tippen Sie auf (+) oder 'Maß eintragen', um Kontaktdaten, Maße und Datum einzugeben.",
  "guideStep2Title": "2. ✂️ Der Vorteil des Zuschnitt-Modus",
  "guideStep2Desc": "Aktivieren Sie am Zuschnitttisch den Zuschnitt-Modus für große, aus der Ferne lesbare Zahlen.",
  "guideStep3Title": "3. Foto von Papierzetteln & KI-Scan",
  "guideStep3Desc": "Fotografieren Sie den traditionellen Papierzettel; die KI trägt die Maße automatisch ein.",
  "guideStep4Title": "4. Digitaler WhatsApp-Zettel & Cloud",
  "guideStep4Desc": "Senden Sie den vollständigen Zettel mit einem Klick per WhatsApp und sichern Sie alles in der Cloud.",
  "closeGuide": "Verstanden / Schließen",
  "privacyModalTitle": "Datenschutz & Datensicherheit",
  "privacyPolicyP1": "Ihre Kundenmaße, Kontakte und Abrechnungen sind sicher in Ihrem privaten Cloud-Konto gespeichert.",
  "privacyPolicyP2": "Kein unbefugter Dritter hat Zugriff auf Ihre Schneidereidaten. Alles ist verschlüsselt.",
  "closePrivacy": "Ich akzeptiere / Schließen",
  "secureStorage100": "100% sichere Cloud-Speicherung",
  "safeBadge": "Sicher",
  "chatbotHeaderTitle": "Azad KI-Assistent",
  "chatbotHeaderSub": "Online-Assistent für Zuschnitt und Schneiderei",
  "voiceReplyActive": "Sprachausgabe Aktiviert",
  "voiceReplyMuted": "Sprachausgabe Stumm",
  "typingInputPlaceholder": "Maße eingeben oder Schneiderfrage stellen...",
  "detectedMeasurementsHeading": "Erkannte Maße",
  "confirmAndApplySlip": "Bestätigen & in Zettel übernehmen",
  "confirmedMeasurement": "Bestätigt",
  "micListeningState": "Ich höre zu... Bitte sprechen",
  "micStartState": "Sprechen",
  "voiceScreenTitle": "Azad Sprachassistent",
  "voiceScreenSub": "Live-Sprachunterhaltung",
  "tapToSpeak": "Zum Sprechen tippen",
  "listeningVoice": "Höre zu...",
  "processingVoice": "Wird verarbeitet...",
  "botSpeaking": "Antwort wird gesprochen...",
  "closeVoiceMode": "Sprachmodus beenden",
  "browserNoVoice": "Spracherkennung wird in diesem Browser nicht unterstützt.",
  "chatbotGreeting": "Hallo! Ich bin der Azad Master Assistent. Sie können Maße sprechen oder tippen (Länge, Schulter, Ärmel, Brust, Taille, Saum, Kragen, Hose, Fußweite). Ich ordne sie für Sie ein.",
  "quickPrompt1": "Länge 42, Schulter 18.5, Ärmel 23, Brust 38, Saum 24, Kragen 15.5, Hose 38",
  "quickPrompt2": "Wie viel Stoff benötigt man für einen Herrenanzug?",
  "quickPrompt3": "Was ist die Formel für Armloch und Schulterabfall?",
  "quickPrompt4": "Wie schneidet man den Kragenansatz exakt zu?",
  "login": "Anmelden",
  "codePlaceholder": "WhatsApp-Nr. oder Code eingeben...",
  "pinHint": "Standard-PIN: 123456 (oder leer lassen)",
  "signingIn": "Anmeldung läuft...",
  "signInWithGoogle": "Sichere Anmeldung mit Google",
  "openInNewTab": "In neuem Tab öffnen",
  "tryRedirectLogin": "Mit Weiterleitung anmelden",
  "openInNewWindow": "Direkt in neuem Fenster anmelden",
  "secureRecords": "100% sichere und private Datensätze",
  "loginPrivacyNotice": "Jeder Schneider meldet sich mit seinem Google-Konto an. Ihre Daten bleiben streng vertraulich.",
  "currentDomainLabel": "Aktuelle Domain (Firebase Authorized Domains):",
  "copyDomainBtn": "Domain kopieren",
  "copiedDomainMsg": "Kopiert!",
  "authorizedDomainTip": "Fügen Sie diese Domain unter Firebase Console > Authentication > Settings > Authorized Domains hinzu.",
  "deleteConfirm": "Sind Sie sicher, dass Sie diesen Zettel löschen möchten?",
  "deleteSuccess": "Kundenzettel erfolgreich gelöscht.",
  "saveSuccess": "Kundenzettel erfolgreich gespeichert.",
  "syncSuccess": "Alle Datensätze mit der Cloud synchronisiert."
}

print("Part 2: hi, pa, bn, tr, es, fr, de ready!")
